const images = {
  solar: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/20cf6804e_generated_image.png",
  water: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/ae5489afe_generated_image.png",
  control: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/47e5d1a2a_generated_image.png",
  engineer: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/28c40bb8b_generated_image.png",
  wind: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/c510f25d5_generated_image.png",
  safety: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/7c191812b_generated_image.png",
  warehouse: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/bc3cc7067_generated_image.png",
  boardroom: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/6fe7873a7_generated_image.png",
  signing: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/b40de175b_generated_image.png",
  night: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/b8c5e9799_generated_image.png",
  pipelines: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/b9922efa3_generated_image.png",
  mobile: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/027edf8f2_generated_image.png",
  cyber: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/61f41c65c_generated_image.png",
  training: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/23d855a5a_generated_image.png",
  ecosystem: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/40638be79_generated_image.png",
  closing: "https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/cba02b7bf_generated_image.png",
};

const p = (eyebrow, titleAr, titleEn, summaryAr, summaryEn, bulletsAr, bulletsEn, visual, noteAr = "", noteEn = "") => ({ eyebrow, titleAr, titleEn, summaryAr, summaryEn, bulletsAr, bulletsEn, ...visual, noteAr, noteEn });
const image = (key) => ({ image: images[key] });
const screen = (screenId) => ({ screenId });

const pages = [
  p("CONFIDENTIAL • COMPREHENSIVE PROPOSAL", "PowerCare لأكوا", "PowerCare for ACWA Power", "ملف شامل يشرح المنصة، قدراتها التشغيلية، نموذج الحوكمة، وخطة مشروع تجريبي محدود وقابل للقياس.", "A comprehensive proposal covering the platform, operating capabilities, governance model and a focused, measurable pilot.", ["مقدم إلى فريق أكوا", "34 صفحة ثنائية اللغة", "منصة + تجربة عملية"], ["Prepared for ACWA Power", "34 bilingual pages", "Platform + practical pilot"], image("solar")),
  p("01 • EXECUTIVE SUMMARY", "من الرؤية إلى الإجراء", "From visibility to action", "تجمع PowerCare الأشخاص والمواقع والمهام والسلامة والمخزون والوثائق في طبقة تشغيل واحدة، وتحوّل البيانات المتفرقة إلى مسؤوليات وقرارات قابلة للمتابعة.", "PowerCare unifies people, sites, tasks, HSE, inventory and documents in one operating layer, turning fragmented data into accountable action and decisions.", ["رؤية تنفيذية لحظية", "إجراء مرتبط بمالك وموقع", "تصعيد وموافقات واضحة", "قياس قبل التوسع"], ["Live executive visibility", "Every action has an owner and site", "Clear approvals and escalation", "Measure before scaling"], screen("dashboard")),
  p("02 • ACWA CONTEXT", "مصممة لبيئات تشغيلية متعددة المواقع", "Designed for multi-site operations", "تخدم المنصة المؤسسات التي تجمع أصولًا موزعة وفرقًا ميدانية وإدارية ومتطلبات سلامة ووثائق وقرارات متسلسلة.", "The platform serves organizations combining distributed assets, field and office teams, safety requirements, documents and layered decisions.", ["مواقع وأصول متنوعة", "فرق متعددة التخصصات", "تشغيل مستمر وورديات", "حوكمة مركزية مع تنفيذ محلي"], ["Diverse sites and assets", "Multidisciplinary teams", "Continuous and shift operations", "Central governance, local execution"], image("water")),
  p("03 • THE GAP", "التشتت يستهلك زمن القرار", "Fragmentation consumes decision time", "عندما تنتقل المتابعة بين البريد والجداول والرسائل والأنظمة، يصعب معرفة النسخة الصحيحة والمالك الحالي والخطوة التالية.", "When follow-up moves across email, sheets, messages and systems, it becomes difficult to identify the right version, current owner and next step.", ["تكرار إدخال البيانات", "مسارات غير مرئية", "تأخر إغلاق الإجراءات", "تقارير يدوية"], ["Duplicate data entry", "Invisible routing", "Delayed action closure", "Manual reporting"], screen("complaints")),
  p("04 • THE VISION", "شركة تتحرك كمنظومة واحدة", "One connected operating system", "تربط PowerCare كل إجراء بسياقه: من قام به، وفي أي موقع، وبأي صلاحية، وما أثره، ومن يتصرف بعده.", "PowerCare gives every action context: who acted, at which site, under what authority, with what impact, and who responds next.", ["سياق كامل لكل معاملة", "انتقال سلس بين الميدان والإدارة", "بيانات قابلة للقياس", "تجربة موحدة متعددة اللغات"], ["Full context for every transaction", "Seamless field-to-office flow", "Measurable operating data", "Unified multilingual experience"], image("ecosystem")),
  p("05 • OPERATING MODEL", "الموقع هو وحدة التشغيل", "The site as an operating unit", "تحتفظ كل محطة بفريقها ومديرها وموقعها وعملياتها، بينما تحصل الإدارة على رؤية مجمعة ومقارنات موحدة.", "Each site retains its team, manager, location and operating records while leadership receives consolidated visibility and consistent comparisons.", ["ملكية واضحة للموقع", "مؤشرات خاصة بالمحطة", "نطاق وصول جغرافي وتنظيمي", "إدارة مركزية للمعايير"], ["Clear site ownership", "Site-level indicators", "Geographic and structural access scope", "Central standards management"], screen("stations")),
  p("06 • ORGANIZATION ENGINE", "الهيكل التنظيمي يشغل النظام", "The hierarchy runs the system", "الشجرة المرئية ليست مخططًا ثابتًا؛ فهي تحدد نطاق الصلاحية والتبعية ومسار الموافقة والتصعيد تلقائيًا.", "The visual hierarchy is not a static chart; it drives authority scope, reporting lines, approvals and escalation automatically.", ["سحب وإعادة ترتيب العقد", "ربط الأشخاص بالمواقع", "صلاحيات حسب الفرع", "تصعيد مشتق من الهيكل"], ["Drag-and-reorder nodes", "Connect people to sites", "Branch-scoped permissions", "Hierarchy-derived escalation"], screen("hr")),
  p("07 • WORKFORCE", "ملف موحد لكل موظف", "One coherent employee record", "يجمع الملف المهني البيانات والعقد والشهادات والإجازات والراتب والتواصل، مع إظهار كل جزء وفق صلاحية المشاهد.", "The professional record brings together profile data, contract, certificates, leave, salary and communications, revealing each area only to authorized viewers.", ["بيانات مهنية وشخصية", "عقود ومرفقات", "إجازات وشهادات", "وصول قائم على الدور"], ["Professional and personal data", "Contracts and attachments", "Leave and certificates", "Role-based access"], screen("employees")),
  p("08 • FIELD EXPERIENCE", "مصممة لمن يعمل في الميدان", "Built for field execution", "واجهة متجاوبة تجعل المهام والحضور والبلاغات والمرفقات متاحة من الهاتف دون تعقيد أدوات المكتب.", "A responsive experience makes tasks, attendance, reports and evidence available on mobile without desktop complexity.", ["خطوات قصيرة وواضحة", "صور وصوت وملفات", "عمل مناسب للمس", "حالات تحميل ومتابعة"], ["Short, clear flows", "Photos, voice and files", "Touch-friendly operation", "Visible progress states"], image("control")),
  p("09 • TASK EXECUTION", "من التكليف إلى إثبات الإنجاز", "From assignment to evidence", "تنظم المهام حسب الموقع والقسم، وتدعم الأولوية والمدة والتقدم والتعليقات والإثبات والمراجعة والاعتراض.", "Tasks are organized by site and section with priority, duration, progress, comments, evidence, review and dispute handling.", ["مسؤول وموعد مستهدف", "إثباتات متعددة الأنواع", "مراجعة قبول أو رفض", "تصعيد عند التعثر"], ["Owner and target date", "Multi-format evidence", "Accept or reject review", "Escalation when blocked"], screen("tasks")),
  p("10 • DAILY REPORTING", "التقرير نتيجة تلقائية للعمل", "Reporting as an operating output", "يجمع التقرير اليومي المهام والمشكلات والإجراءات من سجلاتها الأصلية بدل إعادة كتابة ملخص يدوي منفصل.", "The daily report assembles tasks, issues and actions from their original records instead of requiring a separate manual summary.", ["مؤشرات سريعة", "ربط بالسجل الأصلي", "نطاق حسب صلاحية المستخدم", "PDF وExcel ومقارنات"], ["At-a-glance indicators", "Links to source records", "Permission-aware scope", "PDF, Excel and comparisons"], screen("reports")),
  p("11 • ATTENDANCE", "حضور مرتبط بالموقع والوردية", "Location- and shift-aware attendance", "يتحقق النظام من الدخول والخروج ضمن النطاق الجغرافي، ويربط النتائج بالجدول والاستثناءات والمراجعة.", "The system validates check-in and check-out against geofences, connecting results to schedules, exceptions and review.", ["GPS ونصف قطر معتمد", "حضور وانصراف من الجوال", "تأخير وغياب واستثناءات", "تقارير يومية وشهرية"], ["Approved GPS radius", "Mobile check-in and out", "Late, absent and exceptions", "Daily and monthly reports"], screen("attendance")),
  p("12 • PAYROLL", "مسير راتب قابل للتفسير", "Explainable payroll cycles", "توحد الدورة الأساسي والبدلات والخصومات والحالة، مع مراجعة حسب الشهر والمحطة ونطاق الموارد البشرية.", "The payroll cycle combines base pay, allowances, deductions and status with monthly, site and HR-scope review.", ["قوالب مرنة", "تحقق قبل الدفع", "قفل بعد الاعتماد", "تصدير وقسائم فردية"], ["Flexible templates", "Pre-payment validation", "Lock after approval", "Exports and individual slips"], screen("payroll")),
  p("13 • EXPENSES", "المصروف من الإيصال إلى القرار", "Expenses from receipt to decision", "يرفع الموظف الإيصال ويحدد النوع والموقع والمبلغ، ثم ينتقل الطلب عبر مراجعة المدير والمالية بسجل واضح.", "Employees upload receipts and identify type, site and amount before requests move through manager and finance review with a clear history.", ["حساب الضريبة والإجمالي", "نطاق محطة أو عدة محطات", "اعتماد إداري ومالي", "تصدير حسب الفترة"], ["Tax and total calculation", "Single or multi-site scope", "Manager and finance approval", "Period-based export"], screen("expenses")),
  p("14 • INVENTORY", "مخزون موزع بأثر مركزي", "Distributed stock, central traceability", "تتابع PowerCare الرصيد والحركة بين المستودعات والمحطات والموظفين والعمل الفعلي مع حفظ المصدر والتكلفة.", "PowerCare tracks balances and movement across warehouses, sites, employees and actual work while preserving origin and cost.", ["شراء واستلام وصرف", "تحويل وإرجاع وعكس", "طلبات وأوامر توريد", "أرصدة قبل وبعد الحركة"], ["Purchase, receive and issue", "Transfer, return and reverse", "Requests and purchase orders", "Before-and-after balances"], screen("inventory")),
  p("15 • HSE", "السلامة كسجل تشغيلي يومي", "Safety as a daily operating record", "تجمع المنصة المخاطر والحوادث والتصاريح والتقييمات وقوائم الفحص وساعات العمل الآمنة في سياق الموقع.", "The platform combines risks, incidents, permits, assessments, checklists and safe working hours in site context.", ["حالة سلامة لكل موقع", "مخاطر مفتوحة وإجراءات", "تاريخ اعتماد واضح", "تقارير HSE قابلة للتصدير"], ["Safety state per site", "Open risks and actions", "Clear approval history", "Exportable HSE reports"], screen("safety")),
  p("16 • DOCUMENT CONTROL", "الوثيقة في سياقها الصحيح", "Documents in the right context", "تربط المجلدات والملفات بالموقع والمهمة والعملية، وتحافظ على تنظيم مرن ووصول سريع من الجوال.", "Folders and files connect to sites, tasks and processes, preserving flexible organization and fast mobile access.", ["مجلدات متداخلة", "ربط بالمحطات", "رفع وتنزيل وإعادة تسمية", "وصول حسب النطاق"], ["Nested folders", "Site association", "Upload, download and rename", "Scope-aware access"], screen("files")),
  p("17 • DIGITAL SIGNING", "توقيع متعدد الأطراف قابل للتحقق", "Verifiable multi-party signing", "يُرسل المستند بالتتابع أو بالتوازي، ويُحفظ موضع كل توقيع وسجل الأحداث وبصمة النسخة النهائية.", "Documents move sequentially or in parallel, preserving every signature placement, event history and final-file fingerprint.", ["توقيع مرسوم أو مكتوب", "عدة موقّعين", "روابط توقيع عامة آمنة", "تحقق من البصمة والرقم"], ["Drawn or typed signature", "Multiple signers", "Secure public signing links", "Hash and ID verification"], screen("signing")),
  p("18 • PERFORMANCE", "الأداء مرتبط بالعمل الحقيقي", "Performance grounded in real work", "تُبنى المؤشرات من الإنجاز والتأخير والمشكلات والنقاط والسجلات المرتبطة بدل تقييمات منفصلة عن التشغيل.", "Indicators derive from completion, delay, issues, points and connected records rather than evaluations detached from operations.", ["تحليل فرد ومحطة", "اتجاهات شهرية", "مقارنات عادلة", "تقارير قابلة للتصدير"], ["Employee and site analysis", "Monthly trends", "Fair comparisons", "Export-ready reports"], screen("performance")),
  p("19 • COMMUNICATION", "التواصل داخل سياق الشركة", "Communication in company context", "توحد المحادثات المباشرة وغرف المواقع والمجموعات والوسائط، وتبقي القرار قريبًا من العمل الذي نتج عنه.", "Direct messages, site rooms, groups and media stay connected, keeping decisions close to the work that produced them.", ["نص وصوت وصور وملفات", "بحث ومعرض وسائط", "مجموعات متعددة المواقع", "حذف وإخفاء محكوم"], ["Text, voice, images and files", "Search and media gallery", "Multi-site groups", "Governed deletion and hiding"], screen("chat")),
  p("20 • CAMERA OPERATIONS", "الرؤية الميدانية مرتبطة بالموقع", "Site-linked camera operations", "تجمع لوحة الكاميرات البث والحالة والخريطة والتنبيهات ضمن صلاحيات الموقع، مع إعداد واختبار اتصال منظم.", "The camera workspace combines streams, status, map and alerts within site permissions, with guided setup and connection testing.", ["بطاقة لكل كاميرا", "خريطة المواقع", "تنبيهات مرتبة بالخطورة", "استيراد وإعداد جماعي"], ["One card per camera", "Location map", "Severity-ranked alerts", "Bulk import and setup"], screen("cameras")),
  p("21 • NIRO AI", "مساعد تشغيلي يفهم السياق", "An operational copilot with context", "يحلل Niro البيانات والوثائق ويقترح تقارير أو إجراءات، لكنه يعرض الأعمال الحساسة للمراجعة قبل التنفيذ.", "Niro analyzes data and documents and proposes reports or actions, while presenting sensitive work for approval before execution.", ["أسئلة نصية وصوتية", "تحليل صور وPDF وExcel", "ذاكرة مرتبطة بالشركة", "موافقة بشرية على الإجراء"], ["Text and voice questions", "Image, PDF and Excel analysis", "Company-context memory", "Human approval for actions"], screen("niro")),
  p("22 • SECURITY", "الأمن والخصوصية من البداية", "Security and privacy by design", "تقوم التجربة على عزل بيانات الشركة وأقل صلاحية والوصول حسب الدور والهيكل وسجلات الإجراءات الحساسة.", "The pilot is built around company data isolation, least privilege, role- and hierarchy-based access, and sensitive-action audit trails.", ["جلسات وتحقق متعدد الخطوات", "صلاحيات دقيقة", "عزل مؤسسي للبيانات", "تدقيق وحذف محكوم"], ["Sessions and multi-step verification", "Granular permissions", "Enterprise data isolation", "Auditing and governed deletion"], image("cyber")),
  p("23 • GOVERNANCE", "حوكمة مشتركة وواضحة", "Clear joint governance", "تحتاج التجربة راعيًا تنفيذيًا ومالكًا تشغيليًا وممثلين للمستخدمين والبيانات، مع اجتماع أسبوعي وسجل قرارات.", "The pilot requires an executive sponsor, operational owner and user and data representatives, supported by a weekly review and decision log.", ["مالك قرار من أكوا", "فريق إعداد من PowerCare", "اعتمادات مرحلية", "إدارة تغيير النطاق"], ["ACWA decision owner", "PowerCare configuration team", "Stage-gate approvals", "Scope change control"], image("signing")),
  p("24 • ADOPTION", "التبني جزء من التصميم", "Adoption is part of delivery", "تُهيأ الأدوار والشاشات والتدريب حسب المستخدمين الفعليين، مع سفراء داخليين وقنوات ملاحظات ودعم أثناء التشغيل.", "Roles, screens and training are shaped around real users, with internal champions, feedback channels and live-operation support.", ["تدريب حسب الدور", "مواد عربية وإنجليزية", "دعم عند الإطلاق", "قياس الاستخدام الأسبوعي"], ["Role-based training", "Arabic and English materials", "Go-live support", "Weekly usage measurement"], image("training")),
  p("25 • PILOT BOUNDARY", "نطاق صغير ومقصود", "A deliberately focused scope", "يُقترح موقع تشغيلي واحد ومجموعة مستخدمين محددة وثلاث حالات استخدام، لتقليل المخاطر وتسريع التعلم.", "One operating site, a defined user group and three use cases are proposed to reduce risk and accelerate learning.", ["الهيكل والصلاحيات", "المهام والتصعيد", "الحضور أو HSE", "لوحة قياس إدارية"], ["Hierarchy and permissions", "Tasks and escalation", "Attendance or HSE", "Management measurement dashboard"], image("engineer")),
  p("26 • DISCOVERY", "الأسبوعان 1–2: فهم وقياس", "Weeks 1–2: understand and baseline", "تبدأ التجربة برسم العملية الحالية وتحديد المستخدمين والبيانات ومصادر القياس ومقاييس النجاح والمخاطر.", "The pilot begins by mapping the current process and identifying users, data, measurement sources, success criteria and risks.", ["ورشة نطاق", "خط أساس موثق", "نموذج صلاحيات", "ميثاق تجربة معتمد"], ["Scoping workshop", "Documented baseline", "Access model", "Approved pilot charter"], image("safety")),
  p("27 • CONFIGURATION", "الأسابيع 3–5: إعداد وتحقيق", "Weeks 3–5: configure and validate", "تُبنى البيئة وتُحمّل عينة البيانات وتُراجع حالات الاستخدام مع المالكين قبل إطلاقها للمستخدمين.", "The environment is configured, sample data is loaded and use cases are validated with owners before user launch.", ["تهيئة الموقع والهيكل", "إعداد المسارات", "اختبار الصلاحيات", "قبول المستخدم المبدئي"], ["Site and hierarchy setup", "Workflow configuration", "Permission testing", "Initial user acceptance"], image("warehouse")),
  p("28 • LIVE PILOT", "الأسابيع 6–9: تشغيل فعلي", "Weeks 6–9: live operation", "تعمل الحالات المختارة في بيئة الاستخدام اليومي مع دعم مباشر واجتماعات قصيرة وتحسينات محكومة لا تغير هدف التجربة.", "Selected use cases run in daily operation with direct support, short reviews and controlled tuning that preserves pilot intent.", ["تشغيل حقيقي", "دعم ومتابعة", "سجل ملاحظات", "مراجعة مؤشرات أسبوعية"], ["Real operation", "Support and follow-up", "Feedback log", "Weekly indicator review"], image("pipelines")),
  p("29 • OPERATING CONTINUITY", "التجربة لا تعطل العمل", "The pilot protects continuity", "تُحافظ المسارات الحالية كخطة رجوع، وتُستخدم بدائل يدوية مؤقتة للتكاملات غير الداخلة في نطاق التجربة.", "Current processes remain available as a fallback, with temporary manual paths for integrations outside pilot scope.", ["إطلاق مرحلي", "خطة رجوع", "عدم فرض استبدال شامل", "توثيق أي استثناء"], ["Phased launch", "Fallback plan", "No forced system replacement", "Documented exceptions"], image("night")),
  p("30 • MEASUREMENT", "الأسابيع 10–11: إثبات القيمة", "Weeks 10–11: evidence the value", "تُقارن نتائج التشغيل بخط الأساس باستخدام مصادر وطريقة احتساب متفق عليها، دون افتراض نسب تحسين مسبقة.", "Operating results are compared with the baseline using agreed sources and calculations, without assuming improvement percentages in advance.", ["زمن الإسناد والإغلاق", "اكتمال السجل والأدلة", "وقت إعداد التقارير", "التبني والرضا"], ["Assignment and closure time", "Record and evidence completeness", "Reporting preparation time", "Adoption and satisfaction"], image("wind"), "الأهداف الرقمية النهائية تعتمد بعد خط الأساس.", "Final numeric targets follow baseline approval."),
  p("31 • EXECUTIVE READOUT", "الأسبوع 12: قرار مبني على الدليل", "Week 12: an evidence-based decision", "يُعرض تقرير ختامي يوضح النتائج والتحديات والتعلم والتوصية: التوسع أو التعديل أو التوقف دون التزام إضافي.", "A final report presents results, challenges, learning and a recommendation to scale, adjust or stop without further commitment.", ["نتائج كمية ونوعية", "ملاحظات المستخدمين", "تقييم المخاطر", "خريطة توسع اختيارية"], ["Quantitative and qualitative results", "User feedback", "Risk assessment", "Optional scale roadmap"], image("boardroom")),
  p("32 • DELIVERABLES", "ما الذي تستلمه أكوا؟", "What ACWA receives", "تسلم أكوا بيئة مهيأة ووثائق تشغيل وتدريبًا ولوحة قياس وسجل دعم وتقريرًا تنفيذيًا نهائيًا.", "ACWA receives a configured environment, operating documentation, training, a measurement dashboard, support log and final executive report.", ["بيئة تجربة جاهزة", "حالات استخدام موثقة", "مواد تدريب", "تقرير نتائج وتوصية"], ["Pilot-ready environment", "Documented use cases", "Training materials", "Results and recommendation report"], image("mobile")),
  p("33 • NEXT STEP", "ابدأ صغيرًا، وتوسع بالدليل", "Start focused. Scale with evidence.", "الخطوة المقترحة هي ورشة نطاق مشتركة لمدة 90 دقيقة لتحديد الموقع والحالات والمستخدمين والبيانات وخط الأساس والجدول والمسؤوليات.", "The proposed next step is a 90-minute joint scoping workshop to define the site, use cases, users, data, baseline, schedule and responsibilities.", ["اختيار الموقع", "تسمية المالكين", "اعتماد الحالات والمقاييس", "إصدار ميثاق التجربة"], ["Select the site", "Name accountable owners", "Approve use cases and measures", "Issue the pilot charter"], image("closing"), "PowerCare • powercares.pro", "PowerCare • powercares.pro")
];

export const acwaComprehensivePages = pages.map((item, index) => ({ ...item, number: String(index + 1).padStart(2, "0"), total: pages.length }));