const bar = (title, items) => ({ title, items });
const compare = (traditionalLabel, rows) => ({ traditionalLabel, rows });
const kpis = (items) => ({ items });
const steps = (items) => ({ items });
const metric = (label, value, baseline) => ({ label, value, ...(baseline == null ? {} : { baseline }) });
const slice = (label, value) => ({ label, value });
const kpi = (value, label, labelAr, icon) => ({ value, label, labelAr, icon });
const step = (title, titleAr, detail) => ({ title, titleAr, detail });
const row = (feature, featureAr, powercare, traditional) => ({ feature, featureAr, powercare, traditional });

const page = (number, eyebrow, titleAr, titleEn, summaryAr, summaryEn, bulletsAr, bulletsEn, visualType, visualData, noteAr = "", noteEn = "") => ({ number, eyebrow, titleAr, titleEn, summaryAr, summaryEn, bulletsAr, bulletsEn, visualType, visualData, noteAr, noteEn });

const pages = [
  page("00", "CONFIDENTIAL • COMPREHENSIVE PROPOSAL", "PowerCare لأكوا", "PowerCare for ACWA Power", "وثيقة تجارية متكاملة تقدم منصة تشغيل رقمية موحدة، وتربط الرؤية التنفيذية بالعمل الميداني والحوكمة القابلة للقياس.", "A complete commercial narrative for a unified digital operating platform connecting executive visibility, field execution and measurable governance.", ["منصة تشغيل مؤسسية", "نموذج متعدد المواقع", "تجربة عملية قابلة للقياس"], ["Enterprise operating platform", "Multi-site model", "Measurable practical pilot"], "kpi", kpis([kpi("34", "Document pages", "صفحة", "file"), kpi("21", "Operating modules", "وحدة تشغيلية", "layers"), kpi("6", "Strategic pillars", "محاور استراتيجية", "target"), kpi("1", "Unified platform", "منصة موحدة", "flow"), kpi("2", "Languages", "لغتان", "users"), kpi("12", "Pilot weeks", "أسبوعاً للتجربة", "time")])),
  page("01", "EXECUTIVE SUMMARY", "من الرؤية إلى الإجراء", "From visibility to action", "توحّد PowerCare الأشخاص والمواقع والمهام والسلامة والمخزون والوثائق في طبقة تشغيل واحدة تحول البيانات إلى مسؤوليات وقرارات قابلة للمتابعة.", "PowerCare unifies people, sites, tasks, HSE, inventory and documents in one operating layer that turns data into accountable action.", ["رؤية تنفيذية لحظية", "إجراء مرتبط بمالك وموقع", "قياس قبل التوسع"], ["Live executive visibility", "Every action has an owner and site", "Measure before scaling"], "chart", bar("Operating visibility index", [metric("People", 92, 48), metric("Sites", 88, 42), metric("HSE", 95, 55), metric("Assets", 86, 46)])),
  page("02", "ACWA CONTEXT", "مصممة للتشغيل متعدد المواقع", "Designed for multi-site operations", "تعالج المنصة بيئة تجمع أصولاً موزعة وفرقاً ميدانية وإدارية ومتطلبات سلامة وقرارات متسلسلة.", "The platform addresses distributed assets, field and office teams, safety requirements and layered decisions.", ["تشغيل مستمر", "فرق متعددة التخصصات", "حوكمة مركزية وتنفيذ محلي"], ["Continuous operations", "Multidisciplinary teams", "Central governance, local execution"], "radar", bar("Operational environment fit", [metric("Scale", 88), metric("Field", 94), metric("Safety", 96), metric("Control", 91), metric("Mobility", 89)])),
  page("03", "THE GAP", "التشتت يستهلك زمن القرار", "Fragmentation consumes decision time", "الانتقال بين البريد والجداول والرسائل والأنظمة يصعّب معرفة النسخة الصحيحة والمالك الحالي والخطوة التالية.", "Moving across email, sheets, messages and systems obscures the correct version, current owner and next step.", ["تكرار إدخال البيانات", "مسارات غير مرئية", "تأخر إغلاق الإجراءات"], ["Duplicate entry", "Invisible routing", "Delayed closure"], "comparison", compare("Excel / Email", [row("Single source of truth", "مصدر موحد للحقيقة", "Connected", "Fragmented"), row("Action ownership", "ملكية الإجراء", "Named owner", "Manual follow-up"), row("Audit history", "سجل التدقيق", "Automatic", "Incomplete"), row("Live reporting", "تقارير لحظية", "Real time", "Prepared later")])),
  page("04", "THE VISION", "منظومة واحدة مترابطة", "One connected operating system", "تربط PowerCare كل إجراء بسياقه: المنفذ والموقع والصلاحية والأثر والمسؤول التالي.", "PowerCare gives every action context: actor, site, authority, impact and next accountable owner.", ["سياق كامل للمعاملة", "انتقال سلس بين الميدان والإدارة", "بيانات قابلة للقياس"], ["Complete transaction context", "Seamless field-to-office flow", "Measurable data"], "kpi", kpis([kpi("1×", "Data entry", "إدخال واحد", "data"), kpi("100%", "Named ownership", "ملكية محددة", "users"), kpi("Live", "Decision context", "سياق القرار", "gauge")])),
  page("05", "OPERATING MODEL", "الموقع هو وحدة التشغيل", "The site as an operating unit", "تحتفظ كل محطة بفريقها ومديرها وعملياتها، بينما تحصل الإدارة على رؤية مجمعة ومقارنات موحدة.", "Each site retains its team, manager and records while leadership receives consolidated visibility and consistent comparisons.", ["ملكية واضحة", "مؤشرات خاصة بالموقع", "معايير مركزية"], ["Clear ownership", "Site indicators", "Central standards"], "chart", bar("Governance coverage by level", [metric("Site", 96), metric("Cluster", 88), metric("Region", 84), metric("Corporate", 92)])),
  page("06", "ORGANIZATION ENGINE", "الهيكل التنظيمي يشغّل النظام", "The hierarchy runs the system", "الشجرة المرئية تحدد نطاق الصلاحية والتبعية ومسار الموافقة والتصعيد تلقائياً.", "The visual hierarchy drives authority scope, reporting lines, approvals and escalation automatically.", ["ربط الأشخاص بالمواقع", "صلاحيات حسب الفرع", "تصعيد مشتق من الهيكل"], ["Connect people to sites", "Branch-scoped permissions", "Hierarchy-derived escalation"], "steps", steps([step("Company", "الشركة", "Enterprise governance"), step("Region", "المنطقة", "Portfolio oversight"), step("Site", "الموقع", "Local accountability"), step("Team", "الفريق", "Daily execution")])),
  page("07", "WORKFORCE", "ملف موحد لكل موظف", "One coherent employee record", "يجمع الملف البيانات والعقد والشهادات والإجازات والراتب والتواصل مع إظهار كل جزء وفق الصلاحية.", "The record combines profile, contract, certificates, leave, salary and communications with permission-aware visibility.", ["سجل مهني كامل", "وصول قائم على الدور", "مسارات موارد بشرية"], ["Complete professional record", "Role-based access", "HR workflows"], "radar", bar("Employee record completeness", [metric("Profile", 95), metric("Contract", 88), metric("Skills", 84), metric("Leave", 92), metric("Payroll", 90)])),
  page("08", "FIELD EXPERIENCE", "مصممة لمن يعمل في الميدان", "Built for field execution", "واجهة متجاوبة تجعل الإجراءات الأساسية متاحة من الهاتف دون تعقيد أدوات المكتب.", "A responsive experience makes essential actions available on mobile without desktop complexity.", ["خطوات قصيرة", "صور وصوت وملفات", "عمل مناسب للمس"], ["Short flows", "Voice and files", "Touch-friendly operation"], "kpi", kpis([kpi("<3", "Taps to action", "لمسات للإجراء", "mobile"), kpi("24/7", "Field access", "وصول ميداني", "time"), kpi("4", "Evidence formats", "أنواع إثبات", "file")])),
  page("09", "TASK EXECUTION", "من التكليف إلى إثبات الإنجاز", "From assignment to evidence", "تنظم المهام حسب الموقع والقسم وتدعم الأولوية والمدة والتقدم والإثبات والمراجعة.", "Tasks are organized by site and section with priority, progress, evidence and review.", ["مسؤول وموعد", "إثباتات متعددة", "تصعيد عند التعثر"], ["Owner and due date", "Multi-format evidence", "Escalation when blocked"], "chart", bar("Task cycle performance", [metric("Assigned", 94, 62), metric("On time", 86, 54), metric("Verified", 91, 48), metric("Closed", 88, 45)])),
  page("10", "DAILY REPORTING", "التقرير نتيجة تلقائية للعمل", "Reporting as an operating output", "يجمع التقرير اليومي الإجراءات من سجلاتها الأصلية بدلاً من إعادة كتابة ملخص منفصل.", "Daily reporting assembles actions from source records instead of requiring a separate manual summary.", ["ربط بالسجل الأصلي", "نطاق حسب الصلاحية", "تصدير وتحليل"], ["Source-record links", "Permission-aware scope", "Export and analysis"], "radar", bar("Report quality dimensions", [metric("Speed", 94), metric("Accuracy", 92), metric("Traceability", 96), metric("Clarity", 88), metric("Coverage", 91)])),
  page("11", "ATTENDANCE", "حضور مرتبط بالموقع والوردية", "Location- and shift-aware attendance", "يتحقق النظام من الدخول والخروج ضمن النطاق الجغرافي ويربط النتائج بالجدول والاستثناءات.", "The system validates attendance against geofences and connects results to schedules and exceptions.", ["GPS معتمد", "تأخير وغياب", "تقارير شهرية"], ["Approved GPS", "Late and absent states", "Monthly reports"], "chart", bar("Attendance control", [metric("Verified", 93, 68), metric("On time", 87, 72), metric("Scheduled", 96, 80), metric("Reviewed", 91, 58)])),
  page("12", "PAYROLL", "مسير راتب قابل للتفسير", "Explainable payroll cycles", "توحد الدورة الأساسي والبدلات والخصومات والحالة مع مراجعة حسب الشهر والموقع.", "Payroll cycles combine base pay, allowances, deductions and status with month and site review.", ["قوالب مرنة", "تحقق قبل الدفع", "قفل بعد الاعتماد"], ["Flexible templates", "Pre-payment validation", "Lock after approval"], "pie", bar("Payroll cycle status", [slice("Validated", 58), slice("Approved", 27), slice("Review", 10), slice("Exception", 5)])),
  page("13", "EXPENSES", "المصروف من الإيصال إلى القرار", "Expenses from receipt to decision", "ينتقل الطلب من الإيصال والتصنيف إلى مراجعة المدير والمالية بسجل واضح.", "Requests move from receipt and classification through manager and finance review with a clear history.", ["حساب الضريبة", "نطاق متعدد المواقع", "اعتماد إداري ومالي"], ["Tax calculation", "Multi-site scope", "Manager and finance approval"], "chart", bar("Expense review time", [metric("Submit", 1, 3), metric("Manager", 2, 6), metric("Finance", 2, 7), metric("Close", 1, 4)])),
  page("14", "INVENTORY", "مخزون موزع بأثر مركزي", "Distributed stock, central traceability", "تتابع PowerCare الرصيد والحركة بين المستودعات والمواقع والعمل الفعلي مع حفظ المصدر والتكلفة.", "PowerCare tracks balances and movement across warehouses, sites and work while preserving source and cost.", ["شراء واستلام وصرف", "تحويل وإرجاع", "رصيد قبل وبعد"], ["Purchase, receive and issue", "Transfer and return", "Before-and-after balances"], "pie", bar("Stock distribution", [slice("Available", 54), slice("Reserved", 21), slice("In transit", 15), slice("Low stock", 10)])),
  page("15", "HSE", "السلامة كسجل تشغيلي يومي", "Safety as a daily operating record", "تجمع المنصة المخاطر والحوادث والتصاريح والتقييمات وقوائم الفحص في سياق الموقع.", "The platform combines risks, incidents, permits, assessments and checklists in site context.", ["حالة سلامة لكل موقع", "مخاطر وإجراءات", "تاريخ اعتماد"], ["Safety state per site", "Risks and actions", "Approval history"], "radar", bar("HSE control maturity", [metric("Permits", 94), metric("Checks", 91), metric("Actions", 86), metric("Training", 89), metric("Evidence", 95)])),
  page("16", "DOCUMENT CONTROL", "الوثيقة في سياقها الصحيح", "Documents in the right context", "تربط الملفات بالموقع والمهمة والعملية وتحافظ على تنظيم مرن ووصول سريع.", "Files connect to sites, tasks and processes while preserving flexible organization and fast access.", ["مجلدات متداخلة", "ربط بالمواقع", "وصول حسب النطاق"], ["Nested folders", "Site association", "Scope-aware access"], "chart", bar("Document control quality", [metric("Indexed", 96, 51), metric("Current", 93, 57), metric("Accessible", 89, 62), metric("Audited", 95, 39)])),
  page("17", "DIGITAL SIGNING", "توقيع متعدد الأطراف قابل للتحقق", "Verifiable multi-party signing", "يتحرك المستند بالتتابع أو التوازي مع حفظ موضع كل توقيع وسجل الأحداث وبصمة النسخة النهائية.", "Documents move sequentially or in parallel, preserving placement, event history and final fingerprint.", ["عدة موقّعين", "روابط آمنة", "تحقق من البصمة"], ["Multiple signers", "Secure links", "Hash verification"], "pie", bar("Signature request state", [slice("Completed", 64), slice("In progress", 23), slice("Pending", 9), slice("Exception", 4)])),
  page("18", "PERFORMANCE", "الأداء مرتبط بالعمل الحقيقي", "Performance grounded in real work", "تُبنى المؤشرات من الإنجاز والتأخير والمشكلات والسجلات المرتبطة بدلاً من تقييمات منفصلة.", "Indicators derive from completion, delay, issues and connected records rather than detached evaluations.", ["تحليل فرد وموقع", "اتجاهات شهرية", "مقارنات عادلة"], ["Employee and site analysis", "Monthly trends", "Fair comparisons"], "radar", bar("Performance profile", [metric("Delivery", 91), metric("Quality", 88), metric("Safety", 95), metric("Response", 84), metric("Teamwork", 90)])),
  page("19", "COMMUNICATION", "التواصل داخل سياق الشركة", "Communication in company context", "توحد المحادثات وغرف المواقع والمجموعات والوسائط وتبقي القرار قريباً من العمل.", "Messages, site rooms, groups and media stay connected, keeping decisions close to work.", ["نص وصوت وملفات", "بحث ومعرض وسائط", "مجموعات مواقع"], ["Text, voice and files", "Search and media gallery", "Site groups"], "chart", bar("Channel response index", [metric("Direct", 92, 61), metric("Site", 88, 54), metric("Group", 84, 49), metric("Alerts", 96, 68)])),
  page("20", "CAMERA OPERATIONS", "الرؤية الميدانية مرتبطة بالموقع", "Site-linked camera operations", "تجمع لوحة الكاميرات البث والحالة والخريطة والتنبيهات ضمن صلاحيات الموقع.", "The camera workspace combines streams, status, map and alerts within site permissions.", ["حالة كل كاميرا", "خريطة المواقع", "تنبيهات بالخطورة"], ["Per-camera status", "Location map", "Severity-ranked alerts"], "pie", bar("Camera fleet status", [slice("Online", 76), slice("Maintenance", 12), slice("Review", 8), slice("Offline", 4)])),
  page("21", "NIRO AI", "مساعد تشغيلي يفهم السياق", "An operational copilot with context", "يحلل Niro البيانات والوثائق ويقترح تقارير وإجراءات مع إبقاء الأعمال الحساسة تحت الموافقة البشرية.", "Niro analyzes data and documents and proposes reports and actions while keeping sensitive work under human approval.", ["أسئلة نصية وصوتية", "تحليل مستندات", "موافقة بشرية"], ["Text and voice", "Document analysis", "Human approval"], "kpi", kpis([kpi("24/7", "Context support", "دعم سياقي", "gauge"), kpi("4", "Input formats", "صيغ إدخال", "file"), kpi("100%", "Approval control", "تحكم بالموافقة", "shield")])),
  page("22", "SECURITY", "الأمن والخصوصية من البداية", "Security and privacy by design", "تقوم التجربة على عزل بيانات الشركة وأقل صلاحية والوصول حسب الدور والهيكل وسجل الإجراءات.", "The pilot is built on company isolation, least privilege, structural access and action auditing.", ["تحقق متعدد الخطوات", "صلاحيات دقيقة", "عزل مؤسسي"], ["Multi-step verification", "Granular permissions", "Enterprise isolation"], "radar", bar("Control coverage", [metric("Identity", 94), metric("Access", 96), metric("Audit", 92), metric("Data", 95), metric("Recovery", 86)])),
  page("23", "GOVERNANCE", "حوكمة مشتركة وواضحة", "Clear joint governance", "تحتاج التجربة راعياً تنفيذياً ومالكاً تشغيلياً وممثلين للمستخدمين والبيانات مع سجل قرارات.", "The pilot requires an executive sponsor, operational owner, user and data representatives, and a decision log.", ["مالك قرار", "اعتمادات مرحلية", "إدارة تغيير النطاق"], ["Decision owner", "Stage gates", "Scope change control"], "comparison", compare("Unstructured pilot", [row("Accountability", "المساءلة", "Named owners", "Shared informally"), row("Decision log", "سجل القرارات", "Central record", "Email threads"), row("Stage gates", "اعتمادات مرحلية", "Defined", "Ad hoc"), row("Scope control", "ضبط النطاق", "Governed", "Expands silently")])),
  page("24", "ADOPTION", "التبني جزء من التصميم", "Adoption is part of delivery", "تُهيأ الأدوار والتدريب حسب المستخدمين الفعليين مع سفراء داخليين ودعم أثناء التشغيل.", "Roles and training are shaped around real users, with internal champions and go-live support.", ["تدريب حسب الدور", "مواد ثنائية اللغة", "قياس الاستخدام"], ["Role-based training", "Bilingual materials", "Usage measurement"], "kpi", kpis([kpi("4", "User groups", "فئات مستخدمين", "users"), kpi("2", "Languages", "لغتان", "file"), kpi("1", "Support channel", "قناة دعم", "flow")])),
  page("25", "PILOT BOUNDARY", "نطاق صغير ومقصود", "A deliberately focused scope", "موقع واحد ومجموعة مستخدمين محددة وثلاث حالات استخدام تقلل المخاطر وتسرّع التعلم.", "One site, a defined user group and three use cases reduce risk and accelerate learning.", ["الهيكل والصلاحيات", "المهام والتصعيد", "الحضور أو السلامة"], ["Hierarchy and permissions", "Tasks and escalation", "Attendance or HSE"], "comparison", compare("Full rollout", [row("Initial footprint", "نطاق البداية", "One site", "All sites"), row("Use cases", "حالات الاستخدام", "Three", "Many at once"), row("Risk exposure", "التعرض للمخاطر", "Controlled", "High"), row("Decision basis", "أساس القرار", "Measured", "Assumed")])),

  page("26", "DISCOVERY • WEEKS 1–2", "فهم وقياس خط الأساس", "Understand and baseline", "تبدأ التجربة برسم العملية الحالية وتحديد المستخدمين والبيانات ومصادر القياس والمخاطر.", "The pilot starts by mapping the current process and defining users, data, measurement sources and risks.", ["ورشة نطاق", "خط أساس موثق", "ميثاق تجربة"], ["Scoping workshop", "Documented baseline", "Pilot charter"], "steps", steps([step("Map", "رسم العملية", "Current-state workflow"), step("Measure", "القياس", "Baseline metrics"), step("Model", "النمذجة", "Roles and access"), step("Approve", "الاعتماد", "Signed charter")])),
  page("27", "CONFIGURATION • WEEKS 3–5", "إعداد وتحقيق", "Configure and validate", "تُبنى البيئة وتُحمّل عينة البيانات وتُراجع حالات الاستخدام مع المالكين قبل الإطلاق.", "The environment is configured, sample data loaded and use cases validated with owners before launch.", ["تهيئة الموقع", "إعداد المسارات", "اختبار الصلاحيات"], ["Site setup", "Workflow configuration", "Permission testing"], "chart", bar("Configuration plan by week", [metric("W3", 35), metric("W4", 70), metric("W5", 100)])),
  page("28", "LIVE PILOT • WEEKS 6–9", "تشغيل فعلي ودعم مباشر", "Live operation and support", "تعمل الحالات المختارة يومياً مع دعم مباشر واجتماعات قصيرة وتحسينات محكومة.", "Selected use cases run daily with direct support, short reviews and controlled tuning.", ["تشغيل حقيقي", "سجل ملاحظات", "مراجعة أسبوعية"], ["Real operation", "Feedback log", "Weekly review"], "steps", steps([step("Launch", "الإطلاق", "Controlled go-live"), step("Support", "الدعم", "Daily assistance"), step("Tune", "التحسين", "Governed adjustments"), step("Review", "المراجعة", "Weekly evidence")])),
  page("29", "CONTINUITY", "التجربة لا تعطل العمل", "The pilot protects continuity", "تُحافظ المسارات الحالية كخطة رجوع مع بدائل مؤقتة لما يقع خارج نطاق التكامل.", "Current processes remain available as fallback, with temporary paths for out-of-scope integrations.", ["إطلاق مرحلي", "خطة رجوع", "توثيق الاستثناءات"], ["Phased launch", "Fallback plan", "Documented exceptions"], "kpi", kpis([kpi("0", "Forced replacements", "استبدال إجباري", "shield"), kpi("1", "Fallback plan", "خطة رجوع", "flow"), kpi("100%", "Exceptions logged", "توثيق الاستثناءات", "file")])),
  page("30", "MEASUREMENT • WEEKS 10–11", "إثبات القيمة", "Evidence the value", "تُقارن النتائج بخط الأساس باستخدام مصادر وطريقة احتساب متفق عليها دون افتراض تحسين مسبق.", "Results are compared with baseline using agreed sources and calculations without pre-assumed improvement.", ["زمن الإغلاق", "اكتمال الأدلة", "وقت التقارير", "التبني"], ["Closure time", "Evidence completeness", "Reporting time", "Adoption"], "steps", steps([step("Freeze data", "تثبيت البيانات", "Close measurement window"), step("Compare", "المقارنة", "Baseline versus pilot"), step("Validate", "التحقق", "Joint evidence review"), step("Conclude", "الاستنتاج", "Documented findings")])),
  page("31", "EXECUTIVE READOUT • WEEK 12", "قرار مبني على الدليل", "An evidence-based decision", "يعرض التقرير النهائي النتائج والتحديات والتعلم والتوصية بالتوسع أو التعديل أو التوقف.", "The final readout presents results, challenges, learning and a recommendation to scale, adjust or stop.", ["نتائج كمية ونوعية", "تقييم المخاطر", "خريطة توسع اختيارية"], ["Quantitative and qualitative results", "Risk assessment", "Optional scale roadmap"], "chart", bar("Executive decision evidence", [metric("Value", 90), metric("Adoption", 84), metric("Control", 93), metric("Readiness", 87)])),
  page("32", "DELIVERABLES", "ما الذي تستلمه أكوا؟", "What ACWA receives", "تستلم أكوا بيئة مهيأة ووثائق تشغيل وتدريباً ولوحة قياس وسجل دعم وتقريراً تنفيذياً.", "ACWA receives a configured environment, operating documentation, training, measurement dashboard, support log and executive report.", ["بيئة جاهزة", "حالات موثقة", "مواد تدريب", "تقرير نتائج"], ["Ready environment", "Documented use cases", "Training materials", "Results report"], "comparison", compare("Before pilot", [row("Configured environment", "بيئة مهيأة", "Delivered", "Not available"), row("Operating playbook", "دليل تشغيل", "Documented", "Scattered"), row("Measurement dashboard", "لوحة قياس", "Live", "Manual"), row("Scale recommendation", "توصية توسع", "Evidence-led", "Assumption-led")])),
  page("33", "NEXT STEP", "ابدأ صغيراً، وتوسع بالدليل", "Start focused. Scale with evidence.", "الخطوة التالية ورشة مشتركة لمدة 90 دقيقة لتحديد الموقع والحالات والمستخدمين والبيانات وخط الأساس والمسؤوليات.", "The next step is a 90-minute joint workshop to define the site, use cases, users, data, baseline and responsibilities.", ["اختيار الموقع", "تسمية المالكين", "اعتماد المقاييس"], ["Select the site", "Name owners", "Approve measures"], "kpi", kpis([kpi("90", "Workshop minutes", "دقيقة للورشة", "time"), kpi("3", "Use cases", "حالات استخدام", "layers"), kpi("1", "Approved charter", "ميثاق معتمد", "file")]), "PowerCare • powercares.pro", "PowerCare • powercares.pro")
];

export const acwaComprehensivePages = pages.map((item) => ({ ...item, total: pages.length }));