const field = (key, ar, en, type = "text") => ({ key, ar, en, type });
const section = (heading, keys, values) => ({ heading, body: keys.map((key) => `${key.label}: ${values[key.name] || "—"}`).join("\n") });

export const DOCUMENT_TEMPLATES = [
  { id: "offer", category: "hr", ar: "عرض وظيفي", en: "Employment Offer", descAr: "عرض تعيين رسمي لموظف جديد", descEn: "Formal offer for a new employee", fields: [field("employee","اسم الموظف","Employee name"),field("position","المسمى الوظيفي","Position"),field("salary","الراتب والمزايا","Salary and benefits"),field("start","تاريخ المباشرة","Start date","date"),field("terms","شروط إضافية","Additional terms","textarea")] },
  { id: "leave", category: "hr", ar: "طلب إجازة", en: "Leave Request", descAr: "طلب إجازة جاهز للاعتماد", descEn: "Leave request ready for approval", fields: [field("employee","اسم الموظف","Employee name"),field("type","نوع الإجازة","Leave type"),field("start","من تاريخ","From date","date"),field("end","إلى تاريخ","To date","date"),field("reason","السبب","Reason","textarea")] },
  { id: "warning", category: "hr", ar: "إنذار موظف", en: "Employee Warning", descAr: "توثيق مخالفة وإجراء تصحيحي", descEn: "Document a violation and corrective action", fields: [field("employee","اسم الموظف","Employee name"),field("violation","المخالفة","Violation","textarea"),field("date","تاريخ الواقعة","Incident date","date"),field("action","الإجراء المطلوب","Required action","textarea")] },
  { id: "evaluation", category: "hr", ar: "تقييم أداء", en: "Performance Evaluation", descAr: "نموذج مراجعة أداء الموظف", descEn: "Employee performance review", fields: [field("employee","اسم الموظف","Employee name"),field("period","فترة التقييم","Review period"),field("strengths","نقاط القوة","Strengths","textarea"),field("improvements","فرص التحسين","Areas for improvement","textarea"),field("rating","التقييم العام","Overall rating")] },
  { id: "minutes", category: "company", ar: "محضر اجتماع", en: "Meeting Minutes", descAr: "توثيق الحضور والقرارات والإجراءات", descEn: "Record attendees, decisions and actions", fields: [field("subject","موضوع الاجتماع","Meeting subject"),field("date","التاريخ","Date","date"),field("attendees","الحضور","Attendees","textarea"),field("decisions","القرارات","Decisions","textarea"),field("actions","الإجراءات والمسؤوليات","Actions and owners","textarea")] },
  { id: "memo", category: "company", ar: "مذكرة داخلية", en: "Internal Memo", descAr: "تعميم أو توجيه إداري رسمي", descEn: "Formal internal announcement or direction", fields: [field("to","إلى","To"),field("subject","الموضوع","Subject"),field("content","نص المذكرة","Memo content","textarea"),field("effective","تاريخ السريان","Effective date","date")] },
  { id: "purchase", category: "company", ar: "طلب شراء", en: "Purchase Request", descAr: "طلب توريد مواد أو خدمات", descEn: "Request materials or services", fields: [field("requester","مقدم الطلب","Requester"),field("items","المواد أو الخدمات","Items or services","textarea"),field("amount","التكلفة التقديرية","Estimated cost"),field("justification","المبرر","Justification","textarea")] },
  { id: "incident", category: "company", ar: "تقرير حادث", en: "Incident Report", descAr: "توثيق الحادث والإجراءات المتخذة", descEn: "Document an incident and actions taken", fields: [field("location","الموقع","Location"),field("date","التاريخ","Date","date"),field("details","تفاصيل الحادث","Incident details","textarea"),field("actions","الإجراءات الفورية","Immediate actions","textarea"),field("followup","المتابعة المطلوبة","Required follow-up","textarea")] },
];

export function templateDocument(template, values, ar) {
  const keys = template.fields.map((item) => ({ name: item.key, label: ar ? item.ar : item.en }));
  return { title: ar ? template.ar : template.en, subtitle: ar ? template.descAr : template.descEn, sections: [section(ar ? "بيانات النموذج" : "Template details", keys, values)] };
}