export const feasibilitySlides = [
  {
    eyebrow: "01 — دراسة الجدوى | Feasibility Study",
    titleAr: "PowerCare — خطة الجدوى والنمو",
    titleEn: "PowerCare — Feasibility & Growth Plan",
    summaryAr: "دراسة أولية لإطلاق وتسويق منصة PowerCare في الشرق الأوسط خلال اثني عشر شهرًا، مبنية على نموذج اشتراكات سحابي ومبيعات مباشرة وشراكات محلية.",
    summaryEn: "A preliminary 12-month plan to launch and market PowerCare across the Middle East through SaaS subscriptions, direct sales, and local partnerships.",
    visual: "cover",
  },
  {
    eyebrow: "02 — الخلاصة الاستثمارية | Investment Summary",
    titleAr: "فرصة قابلة للنمو مع وصول تدريجي للتعادل",
    titleEn: "A scalable opportunity with a measured path to break-even",
    summaryAr: "تستهدف الخطة الشركات متعددة المواقع التي تحتاج إلى توحيد الحضور والمهام والموارد البشرية والتقارير. السيناريو الأساسي يفترض الوصول إلى 150 شركة مدفوعة بنهاية السنة.",
    summaryEn: "The base case targets multi-site businesses needing unified attendance, tasks, HR, and reporting, reaching 150 paying companies by year-end.",
    details: [
      ["المستهدف بنهاية السنة | Year-end target", "150 شركة مدفوعة | paying companies"],
      ["الإيراد الشهري بنهاية السنة | Exit MRR", "$17,850"],
      ["الإيراد السنوي المتكرر | Exit ARR", "$214,200"],
      ["نقطة التعادل المقدرة | Estimated break-even", "الشهر 10–12 | Month 10–12"],
      ["ميزانية التشغيل التقديرية | Estimated operating budget", "$140,000"],
    ],
    visual: "analytics",
  },
  {
    eyebrow: "03 — فرصة السوق | Market Opportunity",
    titleAr: "احتياج واضح لدى المنشآت متعددة المواقع",
    titleEn: "A clear need among multi-location organizations",
    summaryAr: "تعاني قطاعات التشغيل الميداني من تشتت البيانات، الحضور غير المنضبط، ضعف توثيق المهام، وبطء التقارير. تتميز PowerCare بتجميع هذه الاحتياجات في منصة عربية مرنة بدل استخدام أنظمة منفصلة.",
    summaryEn: "Field-service sectors face fragmented data, attendance leakage, weak task documentation, and slow reporting. PowerCare combines these needs in one Arabic-ready platform.",
    points: [
      ["الرقمنة المتزايدة للموارد البشرية والعمليات", "Growing digitization of HR and operations"],
      ["ارتفاع الحاجة للحضور المرتبط بالموقع", "Rising demand for location-aware attendance"],
      ["أفضلية تجربة عربية ودعم RTL", "Advantage of Arabic-first and RTL-ready UX"],
      ["قابلية التوسع من محطة واحدة إلى شبكة كاملة", "Scalable from one site to a full network"],
    ],
    visual: "location",
  },
  {
    eyebrow: "04 — العملاء المستهدفون | Target Customers",
    titleAr: "قطاعات ذات ألم تشغيلي وقرار شراء واضح",
    titleEn: "Segments with operational pain and clear buying authority",
    summaryAr: "الأولوية للمنشآت التي لديها 20–500 موظف وعدة مواقع، ويقود قرار الشراء فيها المالك أو مدير العمليات أو الموارد البشرية.",
    summaryEn: "Priority goes to organizations with 20–500 employees across several locations, where owners, operations leaders, or HR managers control purchasing.",
    points: [
      ["إدارة المرافق والصيانة والتشغيل", "Facilities management, maintenance, and operations"],
      ["المقاولات والخدمات الميدانية", "Construction and field services"],
      ["التجزئة والمطاعم والفروع", "Retail, restaurants, and branch networks"],
      ["الخدمات الأمنية واللوجستية", "Security and logistics services"],
      ["العيادات ومراكز الخدمة", "Clinics and service centers"],
    ],
    visual: "hierarchy",
  },
  {
    eyebrow: "05 — القيمة المقدمة | Value Proposition",
    titleAr: "خفض الهدر ورفع وضوح التشغيل",
    titleEn: "Reduce operational leakage and improve visibility",
    summaryAr: "لا تُباع PowerCare بوصفها برنامج حضور فقط؛ بل كغرفة عمليات تربط الأشخاص والمواقع والمهام والوثائق والقرارات في واجهة واحدة.",
    summaryEn: "PowerCare is not positioned as attendance software alone, but as an operations hub connecting people, locations, tasks, documents, and decisions.",
    points: [
      ["تقليل الوقت الإداري في جمع السجلات", "Less administrative time spent collecting records"],
      ["إثبات الحضور وربطه بالموقع والوردية", "Attendance evidence linked to location and shift"],
      ["متابعة المسؤوليات والتأخير والتصعيد", "Accountability for delays and escalations"],
      ["تقارير مركزية جاهزة للإدارة", "Management-ready centralized reporting"],
    ],
    visual: "dashboard",
  },
  {
    eyebrow: "06 — نموذج الإيرادات | Revenue Model",
    titleAr: "اشتراكات شهرية وسنوية بثلاث باقات",
    titleEn: "Monthly and annual subscriptions across three tiers",
    summaryAr: "يعتمد النموذج على اشتراك ثابت لكل شركة مع ترقية الباقة حسب حجم العمليات والاحتياج، إضافة إلى خدمات اختيارية للتهيئة والتدريب والتخصيص.",
    summaryEn: "Revenue comes from company subscriptions, tier upgrades, and optional onboarding, training, and configuration services.",
    details: [
      ["Starter", "$49 شهريًا | $490 سنويًا"],
      ["Professional", "$149 شهريًا | $1,490 سنويًا"],
      ["Enterprise", "$249 شهريًا | $2,490 سنويًا"],
      ["تهيئة وتدريب | Onboarding", "$250–$1,500 حسب النطاق | by scope"],
      ["العملة المرجعية | Reference currency", "USD — تعرض محليًا حسب السوق"],
    ],
    visual: "brand",
  },
  {
    eyebrow: "07 — افتراضات السنة الأولى | Year-One Assumptions",
    titleAr: "سيناريو أساسي محافظ وقابل للقياس",
    titleEn: "A measurable and controlled base-case scenario",
    summaryAr: "الأرقام التالية افتراضات تخطيطية وليست ضمانًا ماليًا. يجب تحديثها بعد أول 20 مقابلة عميل وأول 10 عقود فعلية.",
    summaryEn: "These figures are planning assumptions, not financial guarantees. They should be recalibrated after 20 customer interviews and the first 10 signed contracts.",
    details: [
      ["مزيج العملاء | Customer mix", "70 Starter / 55 Professional / 25 Enterprise"],
      ["متوسط الإيراد الشهري | Blended ARPU", "$119"],
      ["الهامش الإجمالي المستهدف | Target gross margin", "80%+"],
      ["معدل فقد العملاء السنوي | Annual churn ceiling", "أقل من 12% | Below 12%"],
      ["مدة استرداد CAC | CAC payback", "أقل من 6 أشهر | Below 6 months"],
    ],
    visual: "document",
  },
  {
    eyebrow: "08 — مستهدفات المبيعات | Sales Targets",
    titleAr: "نمو ربع سنوي حتى 150 شركة",
    titleEn: "Quarterly growth toward 150 companies",
    summaryAr: "يبدأ الإطلاق بإثبات الملاءمة في سوقين أو ثلاثة، ثم يتوسع عبر المبيعات المباشرة والشركاء بدل الانتشار العشوائي في المنطقة كاملة.",
    summaryEn: "The launch proves fit in two or three markets before expanding through direct sales and partners rather than spreading resources too early.",
    steps: [
      ["Q1", "15 شركة", "15 clients"],
      ["Q2", "+30 شركة", "+30 clients"],
      ["Q3", "+45 شركة", "+45 clients"],
      ["Q4", "+60 شركة", "+60 clients"],
    ],
    points: [
      ["الإجمالي بنهاية السنة: 150 شركة", "Year-end total: 150 companies"],
      ["أولوية التحويل للعقود السنوية", "Prioritize annual contract conversion"],
      ["توسّع مشروط بثبات الدعم والاحتفاظ", "Expansion gated by support quality and retention"],
    ],
    visual: "steps",
  },
  {
    eyebrow: "09 — التوقع المالي | Financial Projection",
    titleAr: "إيرادات متدرجة مع ضبط المصروفات",
    titleEn: "Ramped revenue with disciplined spending",
    summaryAr: "يفترض السيناريو نمو العملاء تدريجيًا خلال السنة؛ لذلك يقل الإيراد المحقق داخل السنة عن ARR في نهايتها. تشمل الإيرادات اشتراكات وخدمات تهيئة مدفوعة.",
    summaryEn: "Because customers are acquired gradually, recognized first-year revenue is lower than exit ARR. Revenue includes subscriptions and paid onboarding services.",
    details: [
      ["إيراد الاشتراكات المقدر | Subscription revenue", "$132,000"],
      ["التهيئة والتدريب | Onboarding & training", "$35,000"],
      ["إجمالي الإيرادات | Total revenue", "$167,000"],
      ["إجمالي المصروفات | Total operating expenses", "$140,000"],
      ["الفائض التشغيلي الأولي | Indicative operating surplus", "$27,000"],
      ["ARR بنهاية السنة | Exit ARR", "$214,200"],
    ],
    visual: "analytics",
  },
  {
    eyebrow: "10 — توزيع الميزانية | Budget Allocation",
    titleAr: "الإنفاق يركز على المنتج والبيع والاحتفاظ",
    titleEn: "Spending focused on product, sales, and retention",
    summaryAr: "ينبغي اعتماد الصرف على مراحل وربطه بمؤشرات واضحة؛ فلا تُفتح سوق جديدة قبل إثبات تكلفة اكتساب مناسبة واستقرار المنتج والدعم.",
    summaryEn: "Spending should be milestone-based. New markets should open only after healthy acquisition cost, product stability, and support capacity are proven.",
    details: [
      ["المنتج والسحابة والأمان | Product, cloud & security", "$32,000"],
      ["التسويق والمبيعات | Marketing & sales", "$52,000"],
      ["الدعم والتهيئة | Support & onboarding", "$25,000"],
      ["القانوني والإداري والتوطين | Legal, admin & localization", "$16,000"],
      ["احتياطي مخاطر | Contingency", "$15,000"],
      ["الإجمالي | Total", "$140,000"],
    ],
    visual: "dashboard",
  },
  {
    eyebrow: "11 — استراتيجية التسويق | Go-to-Market",
    titleAr: "مبيعات استشارية مدعومة بمحتوى وشركاء",
    titleEn: "Consultative sales supported by content and partners",
    summaryAr: "المنتج B2B ويحتاج إلى شرح العائد وتطبيق تجريبي؛ لذلك تكون القناة الرئيسية مبيعات مباشرة موجهة، وتدعمها شراكات ومحتوى عربي وحالات استخدام موثقة.",
    summaryEn: "As a B2B product requiring ROI explanation and a guided pilot, the primary channel is targeted direct sales, supported by partnerships, Arabic content, and case studies.",
    points: [
      ["حملات LinkedIn ورسائل مباشرة لصناع القرار", "LinkedIn and targeted outreach to decision-makers"],
      ["شركاء موارد بشرية وتقنية ومحاسبة", "HR, technology, and accounting partners"],
      ["ندوات قصيرة وتجارب مباشرة للقطاعات", "Short webinars and sector-specific live demos"],
      ["محتوى عربي عن الحضور والتشغيل والامتثال", "Arabic content on attendance, operations, and compliance"],
      ["برنامج إحالة للعملاء والمستشارين", "Referral program for clients and consultants"],
    ],
    visual: "messages",
  },
  {
    eyebrow: "12 — قمع التسويق | Marketing Funnel",
    titleAr: "مستهدفات قابلة للقياس من الوصول إلى الاشتراك",
    titleEn: "Measurable targets from reach to paid conversion",
    summaryAr: "تُراجع النسب شهريًا، ويُوقف أي مصدر عملاء لا يحقق جودة أو تكلفة اكتساب مناسبة بعد فترة اختبار كافية.",
    summaryEn: "Conversion rates are reviewed monthly, and channels failing quality or acquisition-cost thresholds are paused after a valid test period.",
    steps: [
      ["4,500", "عميل محتمل", "Prospects"],
      ["900", "فرصة مؤهلة", "MQLs"],
      ["360", "عرض مباشر", "Demos"],
      ["225", "تجربة موجهة", "Pilots"],
      ["150", "اشتراك مدفوع", "Paid"],
    ],
    details: [
      ["تكلفة الاكتساب القصوى | Maximum CAC", "$470"],
      ["تحويل العرض إلى تجربة | Demo-to-pilot", "62%"],
      ["تحويل التجربة إلى مدفوع | Pilot-to-paid", "67%"],
      ["زمن إغلاق الصفقة | Sales cycle", "14–45 يومًا | days"],
    ],
    visual: "steps",
  },
  {
    eyebrow: "13 — خطة الإطلاق | Launch Roadmap",
    titleAr: "أربعة أرباع بنتائج محددة",
    titleEn: "Four quarters with defined outcomes",
    summaryAr: "تجمع الخطة بين اكتشاف السوق والبيع والتحسين، مع منع التوسع قبل التحقق من الاستخدام الفعلي والاحتفاظ بالعملاء.",
    summaryEn: "The roadmap combines discovery, selling, and iteration, while preventing expansion before usage and retention are validated.",
    points: [
      ["Q1: مقابلات، مواد بيع، 15 عميلًا وتجارب قطاعية", "Q1: interviews, sales kit, 15 clients, sector pilots"],
      ["Q2: تحسين الإعداد، إطلاق الإحالات، 45 عميلًا تراكميًا", "Q2: improve onboarding, launch referrals, 45 cumulative clients"],
      ["Q3: شريكان محليان، حالات نجاح، 90 عميلًا", "Q3: two local partners, case studies, 90 clients"],
      ["Q4: التوسع المدروس، 150 عميلًا وتجديد العقود", "Q4: measured expansion, 150 clients, renewals"],
    ],
    visual: "flow",
  },
  {
    eyebrow: "14 — مؤشرات الأداء | Key Performance Indicators",
    titleAr: "لوحة قيادة أسبوعية وشهرية",
    titleEn: "Weekly and monthly management dashboard",
    summaryAr: "لا يُقاس النجاح بعدد التسجيلات فقط؛ بل بجودة الاستخدام والاحتفاظ وسرعة تحقيق القيمة للعميل.",
    summaryEn: "Success is not measured by sign-ups alone, but by usage quality, retention, and time-to-value.",
    details: [
      ["الشركات المدفوعة | Paying companies", "150"],
      ["MRR بنهاية السنة | Exit MRR", "$17,850"],
      ["تفعيل العميل خلال | Customer activation", "7 أيام | days"],
      ["الاحتفاظ بعد 90 يومًا | 90-day retention", "90%+"],
      ["رضا الدعم | Support satisfaction", "90%+"],
      ["استخدام أسبوعي للحسابات | Weekly account activity", "75%+"],
      ["توقف الخدمة المستهدف | Target downtime", "أقل من 0.5% | Below 0.5%"],
    ],
    visual: "dashboard",
  },
  {
    eyebrow: "15 — المخاطر والمعالجة | Risks & Mitigation",
    titleAr: "إدارة المخاطر قبل التوسع",
    titleEn: "Manage risk before scaling",
    summaryAr: "نجاح المشروع يعتمد على الثقة وسهولة التطبيق والالتزام المحلي؛ لذا يجب اعتبار الأمن والتوطين والدعم عناصر بيع أساسية وليست أعمالًا جانبية.",
    summaryEn: "Success depends on trust, implementation simplicity, and local compliance. Security, localization, and support are core sales requirements, not side activities.",
    points: [
      ["بطء التبني: تجربة موجهة وإعداد سريع", "Slow adoption: guided pilots and fast onboarding"],
      ["حساسية بيانات الموظفين: مراجعة قانونية وأمنية بكل سوق", "Employee-data sensitivity: legal and security review per market"],
      ["ارتفاع تكلفة الاكتساب: شراكات وإحالات وقطاعات محددة", "High CAC: partnerships, referrals, and vertical focus"],
      ["ضغط الدعم: قاعدة معرفة وتدريب ومسارات خدمة", "Support load: knowledge base, training, and service tiers"],
      ["منافسة الأنظمة العالمية: تفوق عربي ومرونة تشغيلية", "Global competitors: Arabic-first UX and operational flexibility"],
    ],
    visual: "security",
  },
  {
    eyebrow: "16 — القرار المقترح | Recommendation",
    titleAr: "إطلاق مرحلي مشروط بمؤشرات نجاح",
    titleEn: "A milestone-gated regional launch",
    summaryAr: "التوصية هي بدء مرحلة تجارية لمدة 90 يومًا في سوقين أو ثلاثة، ثم اعتماد التوسع عند تحقق ملاءمة المنتج، تكلفة اكتساب مقبولة، واحتفاظ أولي قوي.",
    summaryEn: "Proceed with a 90-day commercial launch in two or three markets, then scale only after product fit, healthy CAC, and strong early retention are demonstrated.",
    points: [
      ["اعتماد ميزانية على دفعات مرتبطة بالنتائج", "Release budget in milestone-linked tranches"],
      ["تثبيت 10 عملاء مرجعيين قبل حملات واسعة", "Secure 10 reference clients before broad campaigns"],
      ["مراجعة الأرقام شهريًا وتحديث السيناريو", "Review figures monthly and update the model"],
      ["الحصول على استشارة قانونية ومالية محلية قبل الاستثمار", "Obtain local legal and financial advice before investment"],
    ],
    visual: "brand",
  },
  {
    eyebrow: "17 — تنبيه مهني | Professional Notice",
    titleAr: "دراسة أولية لاتخاذ قرار مبدئي",
    titleEn: "Preliminary planning study",
    summaryAr: "هذه الوثيقة تقديرية أُعدت لأغراض التخطيط، وليست تقييمًا ماليًا معتمدًا أو وعدًا بالعائد. الأسعار والتكاليف والتحويلات مستهدفات يجب التحقق منها ميدانيًا وتحديثها حسب كل دولة.",
    summaryEn: "This document is for planning purposes and is not an audited valuation or a guarantee of return. Pricing, costs, and conversion rates are targets requiring market validation in each country.",
    details: [
      ["النطاق | Scope", "الشرق الأوسط | Middle East"],
      ["الفترة | Period", "12 شهرًا | months"],
      ["العملة | Currency", "USD"],
      ["تاريخ الدراسة | Study date", "13 July 2026"],
      ["إعداد | Prepared for", "PowerCare"],
    ],
    visual: "document",
  },
];