import {
  LayoutDashboard, Gauge, FileText, ListTodo, ClipboardCheck, MessageSquare,
  FolderOpen, PenLine, Sparkles, Megaphone, Users, Radio, UserCog, Banknote,
  Trophy, ShieldQuestion, HelpCircle, Warehouse, ReceiptText, LogIn, CreditCard, ShieldCheck,
} from "lucide-react";

const HELP_SECTIONS = [
  { icon: LayoutDashboard, ar: ["لوحة التحكم", "ابدأ من الملخص الذكي والتنبيهات لمعرفة أولويات اليوم.", "راجع مؤشرات الحضور والمهام وحالة الفريق، ثم افتح البطاقة المرتبطة للتفاصيل."], en: ["Dashboard", "Start with the smart summary and alerts to identify today's priorities.", "Review attendance, tasks and team status, then open a related card for details."] },
  { icon: Gauge, ar: ["اللوحة التنفيذية", "تعرض صورة موحدة عن الفروع والأداء والمخاطر للإدارة العليا.", "قارن المؤشرات وافتح الفرع التي تحتاج قرارًا أو متابعة."], en: ["Executive dashboard", "See a unified view of stations, performance and risk.", "Compare indicators and open any station requiring a decision."] },
  { icon: FileText, ar: ["التقرير اليومي", "يسجل الموظف إنجازاته وملاحظاته ومشكلات يوم العمل.", "يراجع المدير التقارير المعلقة ثم يعتمدها أو يرفضها بسبب واضح."], en: ["Daily reports", "Employees record achievements, notes and daily issues.", "Managers review pending reports and approve or reject them with a reason."] },
  { icon: ListTodo, ar: ["المهام والأقسام", "التنظيم ثابت: فرع، ثم قسم، ثم المهام التابعة لذلك القسم.", "أنشئ القسم واحفظه أولًا، ثم افتحه لإضافة المهام ومتابعة الإنجاز والإثبات والمراجعة."], en: ["Tasks and sections", "Work is organized as Station, then Section, then Tasks.", "Save a section first, open it, then add tasks and track progress, proof and review."] },
  { icon: ClipboardCheck, ar: ["الحضور والجدولة", "سجل الحضور والانصراف وفق سياسة الموقع والجدول المعتمدة.", "يستخدم المدير التبويبات لمراجعة اليوم والشهر والخريطة والورديات والإعدادات."], en: ["Attendance and scheduling", "Check in and out according to location and schedule policy.", "Managers use the tabs for daily, monthly, map, shifts and settings."] },
  { icon: MessageSquare, ar: ["الدردشة", "تواصل عبر غرفة الفرع أو المجموعة أو الرسائل المباشرة.", "يمكن إرسال النصوص والملفات والصوت والبحث في الرسائل والوسائط السابقة."], en: ["Chat", "Communicate in station rooms, groups or direct messages.", "Send text, files and voice notes, and search previous messages and media."] },
  { icon: FolderOpen, ar: ["الملفات", "أنشئ مجلدات واضحة وارفع الملفات داخل المجلد والفرع الصحيحين.", "استخدم إعادة التسمية والتنزيل والحذف فقط وفق صلاحيتك."], en: ["Files", "Create clear folders and upload files in the correct station context.", "Rename, download or delete only when your role permits it."] },
  { icon: Warehouse, ar: ["المخزون وإدارة المواد", "تدير كل فرع مخزونها ومشترياتها بصورة مستقلة، مع تسجيل الصنف والكمية والمورد والتكلفة والفاتورة والصور.", "تُنفذ التحويلات عبر طلب بين الفروع واعتماد الفرع الموردة، ويتيح سجل الحركات للإدارة العليا التراجع الموثق وتصدير تقرير شامل لكل فرع بصيغتي PDF وExcel."], en: ["Inventory and materials", "Each station independently manages its stock and purchases, including item, quantity, supplier, cost, invoice and images.", "Transfers use station requests and supplying-station approval; senior management can audit or reverse movements and export complete station PDF and Excel reports."] },
  { icon: ReceiptText, ar: ["إدارة المصروفات", "ارفع الإيصال وحدد نوع المصروف وتاريخه والفرع أو الفروع المستفيدة؛ يحسب النظام الإجمالي تلقائيًا عند التوزيع على عدة فروع.", "يمر الطلب باعتماد المدير ثم المراجعة المالية، ويمكن متابعة الحالة وفتح مصروفات فرع محددة وتصدير السجل إلى Excel أو PDF."], en: ["Expense management", "Upload the receipt and define the expense type, date, and benefiting station or stations; multi-station totals are calculated automatically.", "Claims pass through manager approval and finance review, with station views and Excel or PDF export."] },
  { icon: PenLine, ar: ["التوقيع الرقمي", "احفظ توقيعك ثم حدد موضعه على المستند قبل الإرسال.", "للطلبات المتعددة يتبع الموقّعون ترتيبًا محددًا، ويمكن التحقق من النسخة النهائية."], en: ["Digital signing", "Save your signature and place it on the document before sending.", "Multi-sign requests follow signer order and the final document can be verified."] },
  { icon: Sparkles, ar: ["المساعد نيرو", "اطلب تلخيصًا أو مقارنة أو فتح صفحة أو إنشاء إجراء مسموح.", "اذكر الفرع والفترة والهدف بوضوح، وراجع النتيجة قبل اعتمادها."], en: ["Niro assistant", "Ask for summaries, comparisons, navigation or permitted actions.", "State the station, period and goal clearly, then review the result."] },
  { icon: Megaphone, ar: ["صوت الموظف", "ثلاث قنوات: اقتراح للتحسين، شكوى باسمك، أو بلاغ مجهول للحماية.", "تابع الردود؛ الشكاوى والبلاغات تُصعَّد تلقائيًا إذا تجاوزت زمن الاستجابة."], en: ["Employee Voice", "Three channels: a suggestion to improve, a named complaint, or an anonymous report for protection.", "Track replies; complaints and reports auto-escalate when the response time is exceeded."] },
  { icon: Users, ar: ["الموظفون", "أضف الموظف وحدد دوره وفرعه وبيانات دخوله.", "من الملف الشخصي تُدار البيانات المهنية والشهادات والإجازات والرصيد."], en: ["Employees", "Add employees and define role, station and login access.", "Profiles contain professional details, certificates, leave and balances."] },
  { icon: Radio, ar: ["الفروع", "عرّف كل موقع عمل ومديره وحالته ونقطة GPS ونطاق الحضور.", "قبل الحذف انقل الموظفين وعالج المهام والسجلات المرتبطة بالفرع."], en: ["Stations", "Define each workplace, manager, status, GPS point and attendance radius.", "Before deletion, transfer employees and resolve linked records."] },
  { icon: UserCog, ar: ["الموارد البشرية", "ابنِ مستويات الموارد البشرية وحدد صلاحية ونطاق كل مستوى.", "ترتيب المستويات يصنع مسار التصعيد للطلبات والشكاوى والاعتراضات."], en: ["Human resources", "Build HR levels and define each level's permissions and scope.", "Their order forms the escalation path for requests and disputes."] },
  { icon: Banknote, ar: ["الرواتب", "اتبع الدورة النظامية: جهّز المسير من الملفات، راجع البنود وفق المادتين 90 و107، ثم اعتمد.", "بعد الاعتماد أنشئ ملف حماية الأجور (مدى): هوية، آيبان، تطابق قوى، وصافٍ موجب قبل اليوم الثالث."], en: ["Payroll", "Follow the statutory cycle: prepare the run from profiles, review lines under Articles 90 and 107, then approve.", "After approval, build the Mudad wage-protection file: ID, IBAN, Qiwa match and a positive net before day 3."] },
  { icon: Trophy, ar: ["الأداء", "راجع إنجاز الأفراد والفروع والنقاط والاتجاهات خلال فترة موحدة.", "استخدم المقارنات مع حجم العمل ولا تعتمد على النسبة وحدها."], en: ["Performance", "Review individual and station achievement, points and trends.", "Compare equal periods and consider workload, not percentages alone."] },
  { icon: ShieldQuestion, ar: ["السلامة HSE", "اختر الفرع ثم انتقل طبقة بعد طبقة: العمل، الامتثال، الاعتماد.", "افتح الخطر إن كان قائمًا، وسجّل الحادث إن وقع، ولا تعتمد آمنة قبل إغلاق المخاطر."], en: ["Safety HSE", "Pick a station, then move layer by layer: work, compliance, approval.", "Open a hazard if it is still present, log an incident if it happened, and do not approve Safe before closing hazards."] },
  { icon: HelpCircle, ar: ["دليل الاستخدام", "افتح شرح الصفحة المختصر من الشريط أعلى كل قسم.", "استخدم الدليل التشغيلي الشامل للتفاصيل والطباعة أو الحفظ PDF."], en: ["User guide", "Open the short contextual guide at the top of each section.", "Use the complete operations manual for detail and PDF printing."] },
  { icon: LogIn, ar: ["البدء وتسجيل الدخول", "اختر بوابة الشركة أو الفرد، ثم أدخل بيانات الحساب ورمز التحقق OTP المرسل إلى البريد.", "بعد الدخول تأكد من الشركة والفرع والدور الظاهر قبل بدء العمل."], en: ["Getting started and sign-in", "Choose company or individual access, then enter the account details and emailed OTP.", "After sign-in, confirm the company, station and role before starting work."] },
  { icon: CreditCard, ar: ["الاشتراكات والخطط", "تُدار الخطط الشهرية والسنوية والتجربة من صفحات الأسعار والاشتراك.", "الدفع يتم من الموقع المنشور، بينما يتابع مالك المنصة حالة الشركات والاشتراكات."], en: ["Plans and subscriptions", "Monthly and annual plans and trials are managed through pricing and subscription flows.", "Checkout runs on the published site, while the platform owner monitors companies and subscriptions."] },
  { icon: ShieldCheck, ar: ["الأمن والخصوصية", "تُقيد البيانات حسب الشركة والدور ونطاق الفروع، وتُراجع العمليات الحساسة في سجل التدقيق.", "لا تشارك كلمات المرور أو رموز التحقق أو روابط التوقيع والملفات الخاصة."], en: ["Security and privacy", "Data is restricted by company, role and station scope, with sensitive activity recorded for audit.", "Never share passwords, verification codes, signing links or private files."] },
];

const SECTION_ORDER = [LogIn, LayoutDashboard, Gauge, Radio, Users, UserCog, ListTodo, ClipboardCheck, FileText, MessageSquare, Megaphone, FolderOpen, PenLine, Warehouse, ReceiptText, Banknote, Trophy, ShieldQuestion, Sparkles, HelpCircle, CreditCard, ShieldCheck];
export const PLATFORM_HELP_SECTIONS = [...HELP_SECTIONS].sort((a, b) => SECTION_ORDER.indexOf(a.icon) - SECTION_ORDER.indexOf(b.icon));