import {
  LayoutDashboard, Gauge, FileText, ListTodo, ClipboardCheck, MessageSquare,
  FolderOpen, PenLine, Sparkles, Megaphone, Users, Radio, UserCog, Banknote,
  Trophy, ShieldQuestion, HelpCircle,
} from "lucide-react";

export const PLATFORM_HELP_SECTIONS = [
  { icon: LayoutDashboard, ar: ["لوحة التحكم", "ابدأ من الملخص الذكي والتنبيهات لمعرفة أولويات اليوم.", "راجع مؤشرات الحضور والمهام وحالة الفريق، ثم افتح البطاقة المرتبطة للتفاصيل."], en: ["Dashboard", "Start with the smart summary and alerts to identify today's priorities.", "Review attendance, tasks and team status, then open a related card for details."] },
  { icon: Gauge, ar: ["اللوحة التنفيذية", "تعرض صورة موحدة عن المحطات والأداء والمخاطر للإدارة العليا.", "قارن المؤشرات وافتح المحطة التي تحتاج قرارًا أو متابعة."], en: ["Executive dashboard", "See a unified view of stations, performance and risk.", "Compare indicators and open any station requiring a decision."] },
  { icon: FileText, ar: ["التقرير اليومي", "يسجل الموظف إنجازاته وملاحظاته ومشكلات يوم العمل.", "يراجع المدير التقارير المعلقة ثم يعتمدها أو يرفضها بسبب واضح."], en: ["Daily reports", "Employees record achievements, notes and daily issues.", "Managers review pending reports and approve or reject them with a reason."] },
  { icon: ListTodo, ar: ["المهام والأقسام", "التنظيم ثابت: محطة، ثم قسم، ثم المهام التابعة لذلك القسم.", "أنشئ القسم واحفظه أولًا، ثم افتحه لإضافة المهام ومتابعة الإنجاز والإثبات والمراجعة."], en: ["Tasks and sections", "Work is organized as Station, then Section, then Tasks.", "Save a section first, open it, then add tasks and track progress, proof and review."] },
  { icon: ClipboardCheck, ar: ["الحضور والجدولة", "سجل الحضور والانصراف وفق سياسة الموقع والجدول المعتمدة.", "يستخدم المدير التبويبات لمراجعة اليوم والشهر والخريطة والورديات والإعدادات."], en: ["Attendance and scheduling", "Check in and out according to location and schedule policy.", "Managers use the tabs for daily, monthly, map, shifts and settings."] },
  { icon: MessageSquare, ar: ["الدردشة", "تواصل عبر غرفة المحطة أو المجموعة أو الرسائل المباشرة.", "يمكن إرسال النصوص والملفات والصوت والبحث في الرسائل والوسائط السابقة."], en: ["Chat", "Communicate in station rooms, groups or direct messages.", "Send text, files and voice notes, and search previous messages and media."] },
  { icon: FolderOpen, ar: ["الملفات", "أنشئ مجلدات واضحة وارفع الملفات داخل المجلد والمحطة الصحيحين.", "استخدم إعادة التسمية والتنزيل والحذف فقط وفق صلاحيتك."], en: ["Files", "Create clear folders and upload files in the correct station context.", "Rename, download or delete only when your role permits it."] },
  { icon: PenLine, ar: ["التوقيع الرقمي", "احفظ توقيعك ثم حدد موضعه على المستند قبل الإرسال.", "للطلبات المتعددة يتبع الموقّعون ترتيبًا محددًا، ويمكن التحقق من النسخة النهائية."], en: ["Digital signing", "Save your signature and place it on the document before sending.", "Multi-sign requests follow signer order and the final document can be verified."] },
  { icon: Sparkles, ar: ["المساعد نيرو", "اطلب تلخيصًا أو مقارنة أو فتح صفحة أو إنشاء إجراء مسموح.", "اذكر المحطة والفترة والهدف بوضوح، وراجع النتيجة قبل اعتمادها."], en: ["Niro assistant", "Ask for summaries, comparisons, navigation or permitted actions.", "State the station, period and goal clearly, then review the result."] },
  { icon: Megaphone, ar: ["الشكاوى والبلاغات", "اختر نوع البلاغ والمحطة وما إذا كانت الهوية معلنة أو مجهولة.", "تابع الردود، ويمكن التصعيد للمستوى الإداري التالي إذا لم تُحل الحالة."], en: ["Complaints and reports", "Choose the report type, station and identified or anonymous mode.", "Track replies and escalate to the next management level when unresolved."] },
  { icon: Users, ar: ["الموظفون", "أضف الموظف وحدد دوره ومحطته وبيانات دخوله.", "من الملف الشخصي تُدار البيانات المهنية والشهادات والإجازات والرصيد."], en: ["Employees", "Add employees and define role, station and login access.", "Profiles contain professional details, certificates, leave and balances."] },
  { icon: Radio, ar: ["المحطات", "عرّف كل موقع عمل ومديره وحالته ونقطة GPS ونطاق الحضور.", "قبل الحذف انقل الموظفين وعالج المهام والسجلات المرتبطة بالمحطة."], en: ["Stations", "Define each workplace, manager, status, GPS point and attendance radius.", "Before deletion, transfer employees and resolve linked records."] },
  { icon: UserCog, ar: ["الموارد البشرية", "ابنِ مستويات الموارد البشرية وحدد صلاحية ونطاق كل مستوى.", "ترتيب المستويات يصنع مسار التصعيد للطلبات والشكاوى والاعتراضات."], en: ["Human resources", "Build HR levels and define each level's permissions and scope.", "Their order forms the escalation path for requests and disputes."] },
  { icon: Banknote, ar: ["الرواتب", "أنشئ مسير الشهر من البيانات الحالية ثم راجع البدلات والخصومات والصافي.", "عالج التحذيرات قبل اعتماد الدفع أو تصدير المسير والقسائم."], en: ["Payroll", "Create the monthly run, then review allowances, deductions and net pay.", "Resolve warnings before payment approval or export."] },
  { icon: Trophy, ar: ["الأداء", "راجع إنجاز الأفراد والمحطات والنقاط والاتجاهات خلال فترة موحدة.", "استخدم المقارنات مع حجم العمل ولا تعتمد على النسبة وحدها."], en: ["Performance", "Review individual and station achievement, points and trends.", "Compare equal periods and consider workload, not percentages alone."] },
  { icon: ShieldQuestion, ar: ["السلامة HSE", "تنقل بين النظرة العامة والمؤشرات والمخاطر والفحوصات وتصاريح العمل.", "سجل الحوادث والإجراءات التصحيحية، ولا تعتمد الحالة الآمنة قبل إغلاق المخاطر."], en: ["Safety HSE", "Use overview, KPIs, risks, checklists and work permits.", "Record incidents and corrective actions; close risks before safe approval."] },
  { icon: HelpCircle, ar: ["دليل الاستخدام", "افتح شرح الصفحة المختصر من الشريط أعلى كل قسم.", "استخدم الدليل التشغيلي الشامل للتفاصيل والطباعة أو الحفظ PDF."], en: ["User guide", "Open the short contextual guide at the top of each section.", "Use the complete operations manual for detail and PDF printing."] },
];