export const IP_CERTIFICATE_URL = "https://media.base44.com/files/public/6a4f617bd7360a0ae9581d2a/00f2eb2e9_.pdf";

export const ipCertificateTranslations = {
  ar: { badge: "مصنف مسجل لدى الهيئة السعودية للملكية الفكرية", title: "شهادة تسجيل مصنف", intro: "NiroVera مصنف برمجي مسجل لدى الهيئة السعودية للملكية الفكرية.", registration: "رقم التسجيل", work: "عنوان المصنف", category: "نوع المصنف", categoryValue: "مصنفات برمجيات وتطبيقات الحاسب الآلي", author: "المؤلف وصاحب الحق", date: "تاريخ التسجيل", view: "عرض الشهادة الأصلية", note: "تعرض هذه المعلومات لأغراض التوثيق والثقة، ولا تمثل تصريحًا باستغلال المصنف أو تداوله." },
  en: { badge: "Work registered with the Saudi Authority for Intellectual Property", title: "Work Registration Certificate", intro: "NiroVera is a software work registered with the Saudi Authority for Intellectual Property.", registration: "Registration number", work: "Work title", category: "Work category", categoryValue: "Software and computer application works", author: "Author and rights holder", date: "Registration date", view: "View original certificate", note: "This information is shown for documentation and trust and does not authorize exploitation or circulation of the work." },
  de: { badge: "Bei der saudischen Behörde für geistiges Eigentum registriertes Werk", title: "Registrierungsbescheinigung", intro: "NiroVera ist ein bei der saudischen Behörde für geistiges Eigentum registriertes Softwarewerk.", registration: "Registrierungsnummer", work: "Titel des Werks", category: "Werkart", categoryValue: "Software- und Computeranwendungswerke", author: "Urheber und Rechteinhaber", date: "Registrierungsdatum", view: "Originalzertifikat anzeigen", note: "Diese Angaben dienen der Dokumentation und Vertrauensbildung und erlauben keine Verwertung oder Verbreitung des Werks." },
  fr: { badge: "Œuvre enregistrée auprès de l’Autorité saoudienne de la propriété intellectuelle", title: "Certificat d’enregistrement d’œuvre", intro: "NiroVera est une œuvre logicielle enregistrée auprès de l’Autorité saoudienne de la propriété intellectuelle.", registration: "Numéro d’enregistrement", work: "Titre de l’œuvre", category: "Catégorie", categoryValue: "Logiciels et applications informatiques", author: "Auteur et titulaire des droits", date: "Date d’enregistrement", view: "Voir le certificat original", note: "Ces informations sont présentées à des fins de documentation et de confiance et n’autorisent pas l’exploitation ou la diffusion de l’œuvre." },
  es: { badge: "Obra registrada ante la Autoridad Saudí de Propiedad Intelectual", title: "Certificado de registro de obra", intro: "NiroVera es una obra de software registrada ante la Autoridad Saudí de Propiedad Intelectual.", registration: "Número de registro", work: "Título de la obra", category: "Categoría", categoryValue: "Obras de software y aplicaciones informáticas", author: "Autor y titular de derechos", date: "Fecha de registro", view: "Ver certificado original", note: "Esta información se muestra con fines de documentación y confianza y no autoriza la explotación ni la circulación de la obra." },
  pt: { badge: "Obra registrada na Autoridade Saudita de Propriedade Intelectual", title: "Certificado de registro de obra", intro: "NiroVera é uma obra de software registrada na Autoridade Saudita de Propriedade Intelectual.", registration: "Número de registro", work: "Título da obra", category: "Categoria", categoryValue: "Obras de software e aplicações informáticas", author: "Autor e titular dos direitos", date: "Data de registro", view: "Ver certificado original", note: "Estas informações são exibidas para documentação e confiança e não autorizam a exploração ou circulação da obra." },
  ru: { badge: "Произведение зарегистрировано в Саудовском ведомстве интеллектуальной собственности", title: "Свидетельство о регистрации произведения", intro: "NiroVera — программное произведение, зарегистрированное в Саудовском ведомстве интеллектуальной собственности.", registration: "Регистрационный номер", work: "Название произведения", category: "Категория", categoryValue: "Программное обеспечение и компьютерные приложения", author: "Автор и правообладатель", date: "Дата регистрации", view: "Открыть оригинал свидетельства", note: "Сведения представлены для документального подтверждения и доверия и не разрешают использование или распространение произведения." },
  ja: { badge: "サウジ知的財産庁に登録された著作物", title: "著作物登録証明書", intro: "NiroVeraはサウジ知的財産庁に登録されたソフトウェア著作物です。", registration: "登録番号", work: "著作物名", category: "区分", categoryValue: "ソフトウェアおよびコンピューターアプリケーション", author: "著作者・権利者", date: "登録日", view: "原本証明書を見る", note: "この情報は記録と信頼性のために表示され、著作物の利用または流通を許可するものではありません。" },
  ko: { badge: "사우디 지식재산청 등록 저작물", title: "저작물 등록 증명서", intro: "NiroVera는 사우디 지식재산청에 등록된 소프트웨어 저작물입니다.", registration: "등록 번호", work: "저작물명", category: "분류", categoryValue: "소프트웨어 및 컴퓨터 응용 프로그램 저작물", author: "저작자 및 권리자", date: "등록일", view: "원본 증명서 보기", note: "이 정보는 문서화와 신뢰를 위해 표시되며 저작물의 이용이나 유통을 허가하지 않습니다." },
};