const rows = (items) => items.map(([label, labelAr, owner, ownerAr, status, statusAr]) => ({ label, labelAr, owner, ownerAr, status, statusAr }));

export const MANUAL_DEMO_DATA = {
  dashboard: { title: "Operations Command Center", titleAr: "مركز قيادة العمليات", metrics: [["Attendance", "الحضور", "94%"], ["Open tasks", "المهام المفتوحة", "18"], ["Safety", "السلامة", "Good"]], rows: rows([["Transformer inspection", "فحص المحول", "Ahmed Al-Salem", "أحمد السالم", "In progress", "قيد التنفيذ"], ["Attendance exception", "استثناء حضور", "Sara Hassan", "سارة حسن", "Needs review", "تحتاج مراجعة"], ["Station risk alert", "تنبيه مخاطر محطة", "North Station", "المحطة الشمالية", "High", "مرتفع"]]) },
  employees: { title: "Employee Directory", titleAr: "دليل الموظفين", metrics: [["Employees", "الموظفون", "126"], ["Stations", "المحطات", "8"], ["On duty", "على رأس العمل", "91"]], rows: rows([["Ahmed Al-Salem", "أحمد السالم", "Station Manager", "مدير محطة", "Active", "نشط"], ["Sara Hassan", "سارة حسن", "HSE Officer", "مسؤولة سلامة", "Active", "نشط"], ["Omar Nasser", "عمر ناصر", "Technician", "فني", "On leave", "في إجازة"]]) },
  stations: { title: "Stations and Workplaces", titleAr: "المحطات ومواقع العمل", metrics: [["Stations", "المحطات", "8"], ["Online", "متصلة", "7"], ["GPS ready", "GPS جاهز", "8"]], rows: rows([["North Station", "المحطة الشمالية", "Ahmed Al-Salem", "أحمد السالم", "Operational", "تعمل"], ["Central Warehouse", "المستودع المركزي", "Khalid Omar", "خالد عمر", "Operational", "تعمل"], ["East Station", "المحطة الشرقية", "Maha Ali", "مها علي", "Attention", "تحتاج متابعة"]]) },
  attendance: { title: "Attendance Today", titleAr: "حضور اليوم", metrics: [["Present", "حاضر", "91"], ["Late", "متأخر", "4"], ["Absent", "غائب", "2"]], rows: rows([["Ahmed Al-Salem", "أحمد السالم", "07:54 AM", "07:54 ص", "Present", "حاضر"], ["Sara Hassan", "سارة حسن", "08:07 AM", "08:07 ص", "Late", "متأخرة"], ["Omar Nasser", "عمر ناصر", "—", "—", "Day off", "راحة"]]) },
  tasks: { title: "Station Tasks", titleAr: "مهام المحطة", metrics: [["Active", "نشطة", "18"], ["Completed", "مكتملة", "42"], ["Overdue", "متأخرة", "3"]], rows: rows([["Inspect cooling system", "فحص نظام التبريد", "Omar Nasser", "عمر ناصر", "70% complete", "منجزة 70%"], ["Update safety signs", "تحديث لوحات السلامة", "Sara Hassan", "سارة حسن", "Needs review", "تحتاج مراجعة"], ["Monthly meter reading", "قراءة العداد الشهرية", "Field Team", "الفريق الميداني", "Overdue", "متأخرة"]]) },
  payroll: { title: "July Payroll", titleAr: "مسير رواتب يوليو", metrics: [["Employees", "الموظفون", "126"], ["Net payroll", "صافي الرواتب", "SAR 842K"], ["Paid", "مدفوع", "104"]], rows: rows([["Ahmed Al-Salem", "أحمد السالم", "SAR 12,800", "12,800 ر.س", "Ready", "جاهز"], ["Sara Hassan", "سارة حسن", "SAR 10,450", "10,450 ر.س", "Paid", "مدفوع"], ["Omar Nasser", "عمر ناصر", "SAR 7,900", "7,900 ر.س", "Review", "مراجعة"]]) },
  expenses: { title: "Expense Requests", titleAr: "طلبات المصروفات", metrics: [["Submitted", "مقدمة", "12"], ["Manager review", "مراجعة المدير", "5"], ["Approved", "معتمدة", "31"]], rows: rows([["Fuel invoice #1042", "فاتورة وقود #1042", "North Station", "المحطة الشمالية", "Manager review", "مراجعة المدير"], ["Safety equipment", "معدات سلامة", "East Station", "المحطة الشرقية", "Finance review", "مراجعة مالية"], ["Team accommodation", "سكن الفريق", "Central Office", "المقر الرئيسي", "Approved", "معتمد"]]) },
  inventory: { title: "Station Inventory", titleAr: "مخزون المحطة", metrics: [["Items", "الأصناف", "348"], ["Low stock", "مخزون منخفض", "9"], ["Movements", "الحركات", "64"]], rows: rows([["Insulated gloves", "قفازات عازلة", "North Station", "المحطة الشمالية", "24 available", "24 متاح"], ["Circuit breaker 32A", "قاطع 32 أمبير", "Central Warehouse", "المستودع المركزي", "Low stock", "مخزون منخفض"], ["Copper cable 16mm", "كيبل نحاس 16مم", "East Station", "المحطة الشرقية", "Transfer pending", "تحويل معلق"]]) },
  signing: { title: "Signature Requests", titleAr: "طلبات التوقيع", metrics: [["Pending", "معلقة", "6"], ["Signed", "موقعة", "18"], ["Verified", "موثقة", "17"]], rows: rows([["Safety inspection report.pdf", "تقرير فحص السلامة.pdf", "Sara Hassan", "سارة حسن", "Waiting signature", "بانتظار التوقيع"], ["Purchase approval.pdf", "اعتماد مشتريات.pdf", "Ahmed Al-Salem", "أحمد السالم", "Completed", "مكتمل"], ["Employment letter.pdf", "خطاب موظف.pdf", "HR Department", "الموارد البشرية", "Verified", "موثق"]]) },
  files: { title: "Company Files", titleAr: "ملفات الشركة", metrics: [["Folders", "المجلدات", "24"], ["Files", "الملفات", "386"], ["Updated today", "محدثة اليوم", "11"]], rows: rows([["HSE / July Reports", "السلامة / تقارير يوليو", "Sara Hassan", "سارة حسن", "12 files", "12 ملفًا"], ["HR / Certificates", "الموارد / الشهادات", "HR Department", "الموارد البشرية", "38 files", "38 ملفًا"], ["Stations / North", "المحطات / الشمالية", "Ahmed Al-Salem", "أحمد السالم", "Updated", "محدث"]]) },
  safety: { title: "HSE Safety Dashboard", titleAr: "لوحة السلامة HSE", metrics: [["Safety score", "درجة السلامة", "92%"], ["Open risks", "مخاطر مفتوحة", "4"], ["Permits", "التصاريح", "7"]], rows: rows([["Working at height", "العمل على ارتفاع", "Sara Hassan", "سارة حسن", "Medium risk", "خطر متوسط"], ["Electrical isolation", "العزل الكهربائي", "North Station", "المحطة الشمالية", "Approved", "معتمد"], ["Emergency exit check", "فحص مخرج الطوارئ", "Omar Nasser", "عمر ناصر", "Action due", "إجراء مستحق"]]) },
  performance: { title: "Performance Analytics", titleAr: "تحليلات الأداء", metrics: [["Completion", "الإنجاز", "88%"], ["Points", "النقاط", "2,460"], ["Issues", "المشكلات", "5"]], rows: rows([["Ahmed Al-Salem", "أحمد السالم", "North Station", "المحطة الشمالية", "Excellent", "ممتاز"], ["Sara Hassan", "سارة حسن", "HSE Team", "فريق السلامة", "On target", "ضمن الهدف"], ["Omar Nasser", "عمر ناصر", "Field Team", "الفريق الميداني", "Needs support", "يحتاج دعمًا"]]) },
  hr: { title: "HR Structure", titleAr: "الهيكل الإداري", metrics: [["HR levels", "مستويات HR", "4"], ["Station groups", "مجموعات المحطات", "3"], ["Open positions", "مناصب شاغرة", "1"]], rows: rows([["Corporate HR Manager", "مدير الموارد للشركة", "Noura Ali", "نورة علي", "Company scope", "نطاق الشركة"], ["Northern Cluster HR", "موارد المجموعة الشمالية", "Fahad Salem", "فهد سالم", "3 stations", "3 محطات"], ["Station HR Assistant", "مساعد موارد المحطة", "Unassigned", "غير معين", "Action needed", "يلزم إجراء"]]) },
  reports: { title: "Daily Operations Report", titleAr: "التقرير التشغيلي اليومي", metrics: [["Tasks", "المهام", "18"], ["Issues", "المشكلات", "3"], ["Actions", "الإجراءات", "11"]], rows: rows([["Cooling inspection completed", "اكتمل فحص التبريد", "North Station", "المحطة الشمالية", "Completed", "مكتمل"], ["Generator vibration reported", "تم الإبلاغ عن اهتزاز المولد", "East Station", "المحطة الشرقية", "Investigating", "قيد التحقيق"], ["Emergency drill recorded", "تم تسجيل تمرين الطوارئ", "HSE Team", "فريق السلامة", "Logged", "مسجل"]]) },
  complaints: { title: "Complaints and Reports", titleAr: "الشكاوى والبلاغات", metrics: [["Open", "مفتوحة", "7"], ["In review", "قيد المراجعة", "4"], ["Resolved", "محلولة", "23"]], rows: rows([["Shift schedule concern", "ملاحظة على جدول الوردية", "Anonymous", "مجهول", "In review", "قيد المراجعة"], ["Equipment request", "طلب معدات", "Omar Nasser", "عمر ناصر", "Responded", "تم الرد"], ["Safety suggestion", "اقتراح سلامة", "North Station", "المحطة الشمالية", "Escalated", "مصعد"]]) },
  chat: { title: "Company Chat", titleAr: "دردشة الشركة", metrics: [["Rooms", "الغرف", "8"], ["Unread", "غير مقروءة", "14"], ["Online", "متصلون", "27"]], rows: rows([["North Station Room", "غرفة المحطة الشمالية", "Ahmed: Inspection done", "أحمد: اكتمل الفحص", "2 unread", "2 غير مقروءة"], ["HSE Team", "فريق السلامة", "Sara: Permit approved", "سارة: تم اعتماد التصريح", "Active", "نشطة"], ["Omar Nasser", "عمر ناصر", "Photo attached", "تم إرفاق صورة", "Delivered", "تم التسليم"]]) },
  niro: { title: "Niro Smart Assistant", titleAr: "المساعد الذكي نيرو", metrics: [["Questions", "الأسئلة", "24"], ["Actions ready", "إجراءات جاهزة", "3"], ["Documents", "المستندات", "5"]], rows: rows([["Summarize today’s risks", "لخص مخاطر اليوم", "Niro Analysis", "تحليل نيرو", "Completed", "مكتمل"], ["Create inspection task", "أنشئ مهمة فحص", "Approval required", "تتطلب اعتمادًا", "Waiting approval", "بانتظار الاعتماد"], ["Prepare weekly report", "جهز التقرير الأسبوعي", "PDF Document", "مستند PDF", "Ready", "جاهز"]]) }
};