export const MANUAL_UI_LABELS = {
  ar: { toc:"فهرس الفصول", appearance:"شكل واجهة القسم", contains:"ماذا تحتوي الشاشة؟", controls:"الأزرار وماذا تفعل", states:"الحالات والرسائل الظاهرة", roles:"من يستخدم القسم؟", steps:"طريقة الاستخدام خطوة بخطوة", rules:"قواعد وضوابط مهمة", tips:"نصائح عملية", download:"تنزيل PDF", footer:"الدليل التشغيلي الشامل", updated:"آخر تحديث" },
  en: { toc:"Table of contents", appearance:"Section interface", contains:"What is on this screen?", controls:"Controls and actions", states:"Visible states and messages", roles:"Who uses this section?", steps:"Step-by-step instructions", rules:"Rules and constraints", tips:"Practical tips", download:"Download PDF", footer:"Comprehensive operations manual", updated:"Last updated" },
  fr: { toc:"Table des matières", appearance:"Interface de la section", contains:"Contenu de l’écran", controls:"Commandes et actions", states:"États et messages visibles", roles:"Qui utilise cette section ?", steps:"Instructions étape par étape", rules:"Règles et contraintes", tips:"Conseils pratiques", download:"Télécharger le PDF", footer:"Manuel opérationnel complet", updated:"Dernière mise à jour" },
  es: { toc:"Índice", appearance:"Interfaz de la sección", contains:"Contenido de la pantalla", controls:"Controles y acciones", states:"Estados y mensajes visibles", roles:"¿Quién usa esta sección?", steps:"Instrucciones paso a paso", rules:"Reglas y restricciones", tips:"Consejos prácticos", download:"Descargar PDF", footer:"Manual operativo completo", updated:"Última actualización" },
  tr: { toc:"İçindekiler", appearance:"Bölüm arayüzü", contains:"Ekranda neler var?", controls:"Kontroller ve işlemler", states:"Görünen durumlar ve mesajlar", roles:"Bu bölümü kim kullanır?", steps:"Adım adım talimatlar", rules:"Kurallar ve kısıtlamalar", tips:"Pratik ipuçları", download:"PDF indir", footer:"Kapsamlı operasyon kılavuzu", updated:"Son güncelleme" },
  ur: { toc:"فہرستِ ابواب", appearance:"سیکشن کا انٹرفیس", contains:"اس اسکرین میں کیا ہے؟", controls:"کنٹرولز اور کارروائیاں", states:"ظاہر حالتیں اور پیغامات", roles:"یہ سیکشن کون استعمال کرتا ہے؟", steps:"مرحلہ وار ہدایات", rules:"قواعد اور پابندیاں", tips:"عملی تجاویز", download:"PDF ڈاؤن لوڈ کریں", footer:"جامع آپریشنز مینوئل", updated:"آخری تازہ کاری" },
  hi: { toc:"विषय सूची", appearance:"अनुभाग इंटरफ़ेस", contains:"इस स्क्रीन में क्या है?", controls:"नियंत्रण और कार्रवाइयाँ", states:"दिखाई देने वाली स्थितियाँ और संदेश", roles:"इस अनुभाग का उपयोग कौन करता है?", steps:"चरण-दर-चरण निर्देश", rules:"नियम और सीमाएँ", tips:"व्यावहारिक सुझाव", download:"PDF डाउनलोड करें", footer:"व्यापक संचालन पुस्तिका", updated:"अंतिम अपडेट" },
  bn: { toc:"সূচিপত্র", appearance:"বিভাগের ইন্টারফেস", contains:"এই স্ক্রিনে কী আছে?", controls:"নিয়ন্ত্রণ ও কার্যক্রম", states:"দৃশ্যমান অবস্থা ও বার্তা", roles:"এই বিভাগ কে ব্যবহার করেন?", steps:"ধাপে ধাপে নির্দেশনা", rules:"নিয়ম ও সীমাবদ্ধতা", tips:"ব্যবহারিক পরামর্শ", download:"PDF ডাউনলোড", footer:"সম্পূর্ণ পরিচালনা নির্দেশিকা", updated:"সর্বশেষ হালনাগাদ" },
  ru: { toc:"Содержание", appearance:"Интерфейс раздела", contains:"Что находится на экране?", controls:"Элементы управления", states:"Состояния и сообщения", roles:"Кто использует раздел?", steps:"Пошаговые инструкции", rules:"Правила и ограничения", tips:"Практические советы", download:"Скачать PDF", footer:"Полное руководство по эксплуатации", updated:"Последнее обновление" },
};