export const MANUAL_UI_LABELS = {
  ar: { toc:"فهرس الفصول", appearance:"وصف القسم وهدفه", contains:"ماذا تحتوي الشاشة؟", controls:"الأزرار وماذا تفعل", states:"الحالات والرسائل الظاهرة", roles:"من يستخدم القسم؟", steps:"طريقة الاستخدام خطوة بخطوة", rules:"تحذيرات وضوابط مهمة", tips:"نصائح للنجاح", screenshot:"لقطة حقيقية من القسم", download:"تصدير PDF", footer:"الدليل التشغيلي الشامل", updated:"آخر تحديث" },
  en: { toc:"Table of contents", appearance:"Section interface", contains:"What is on this screen?", controls:"Controls and actions", states:"Visible states and messages", roles:"Who uses this section?", steps:"Step-by-step instructions", rules:"Rules and constraints", tips:"Practical tips", screenshot:"Live section screenshot", download:"Export PDF", footer:"Comprehensive operations manual", updated:"Last updated" },
  fr: { toc:"Table des matières", appearance:"Interface de la section", contains:"Contenu de l’écran", controls:"Commandes et actions", states:"États et messages visibles", roles:"Qui utilise cette section ?", steps:"Instructions étape par étape", rules:"Règles et contraintes", tips:"Conseils pratiques", screenshot:"Capture réelle de la section", download:"Exporter en PDF", footer:"Manuel opérationnel complet", updated:"Dernière mise à jour" },
  es: { toc:"Índice", appearance:"Interfaz de la sección", contains:"Contenido de la pantalla", controls:"Controles y acciones", states:"Estados y mensajes visibles", roles:"¿Quién usa esta sección?", steps:"Instrucciones paso a paso", rules:"Reglas y restricciones", tips:"Consejos prácticos", screenshot:"Captura real de la sección", download:"Exportar PDF", footer:"Manual operativo completo", updated:"Última actualización" },
  de: { toc:"Inhaltsverzeichnis", appearance:"Bereichsoberfläche", contains:"Was befindet sich auf diesem Bildschirm?", controls:"Steuerelemente und Aktionen", states:"Sichtbare Zustände und Meldungen", roles:"Wer nutzt diesen Bereich?", steps:"Schritt-für-Schritt-Anleitung", rules:"Regeln und Einschränkungen", tips:"Praktische Tipps", screenshot:"Echter Bereichs-Screenshot", download:"PDF exportieren", footer:"Umfassendes Betriebshandbuch", updated:"Zuletzt aktualisiert" },
  pt: { toc:"Índice", appearance:"Interface da secção", contains:"O que existe neste ecrã?", controls:"Controlos e ações", states:"Estados e mensagens visíveis", roles:"Quem utiliza esta secção?", steps:"Instruções passo a passo", rules:"Regras e restrições", tips:"Dicas práticas", screenshot:"Captura real da secção", download:"Exportar PDF", footer:"Manual operacional completo", updated:"Última atualização" },
  ja: { toc:"目次", appearance:"セクション画面", contains:"この画面の内容", controls:"操作とアクション", states:"表示される状態とメッセージ", roles:"このセクションの利用者", steps:"手順", rules:"重要な規則と制約", tips:"実用的なヒント", screenshot:"セクションの実画面", download:"PDFを書き出す", footer:"総合運用マニュアル", updated:"最終更新" },
  ko: { toc:"목차", appearance:"섹션 화면", contains:"이 화면의 내용", controls:"제어 및 작업", states:"표시 상태 및 메시지", roles:"이 섹션의 사용자", steps:"단계별 안내", rules:"규칙 및 제한", tips:"실용적인 팁", screenshot:"실제 섹션 화면", download:"PDF 내보내기", footer:"종합 운영 매뉴얼", updated:"최종 업데이트" },
  ru: { toc:"Содержание", appearance:"Интерфейс раздела", contains:"Что находится на экране?", controls:"Элементы управления", states:"Состояния и сообщения", roles:"Кто использует раздел?", steps:"Пошаговые инструкции", rules:"Правила и ограничения", tips:"Практические советы", screenshot:"Снимок раздела", download:"Экспорт PDF", footer:"Полное руководство по эксплуатации", updated:"Последнее обновление" },
};