export const presentationSlides = [
  {
    eyebrow: "01 — الغلاف | Cover",
    titleAr: "NiroVera",
    titleEn: "Integrated Workforce Operations Platform",
    summaryAr: "منصة رقمية متكاملة لإدارة القوى العاملة والعمليات اليومية والموارد البشرية ضمن بيئة موحّدة وآمنة.",
    summaryEn: "A unified and secure digital platform for workforce, daily operations, and human-resources management.",
    visual: "cover",
  },
  {
    eyebrow: "02 — الملخص التنفيذي | Executive Summary",
    titleAr: "منصة واحدة لإدارة دورة العمل كاملة",
    titleEn: "One platform for the complete work cycle",
    summaryAr: "تربط NiroVera الإدارة والموظفين والفروع في منظومة واحدة تبدأ من الحضور والمهام، وتمتد إلى الموارد البشرية والتقارير والتواصل والتوقيع الإلكتروني.",
    summaryEn: "NiroVera connects management, employees, and workstations in one system spanning attendance, tasks, HR, reporting, communication, and e-signatures.",
    points: [
      ["بنية متعددة المستأجرين بعزل تام — تدعم مئات الفروع وآلاف الموظفين", "Multi-tenant architecture with strict isolation — scales to hundreds of stations and thousands of employees"],
      ["تجربة متجاوبة للويب والجوال مع دعم العربية والاتجاه من اليمين", "Responsive web and mobile experience with Arabic RTL support"],
      ["قرارات أسرع بفضل مؤشرات الأداء والتقارير المركزية", "Faster decisions through centralized KPIs and reports"],
    ],
    visual: "dashboard",
  },
  {
    eyebrow: "03 — المشكلة والحل | Challenge & Solution",
    titleAr: "تحويل العمليات المتفرقة إلى مسار رقمي واضح",
    titleEn: "Turning fragmented operations into a clear digital flow",
    summaryAr: "تعالج المنصة تشتت سجلات الحضور والمهام والملفات والموافقات بين الورق والرسائل والجداول المنفصلة، وتحوّلها إلى بيانات مترابطة قابلة للمتابعة والتدقيق.",
    summaryEn: "The platform replaces scattered paper records, messages, and spreadsheets with connected, traceable, and auditable workflows.",
    points: [
      ["قبل: بيانات موزعة وتأخر في المتابعة", "Before: fragmented data and delayed follow-up"],
      ["بعد: مصدر موحد للحقيقة وصلاحيات واضحة", "After: one source of truth with clear permissions"],
      ["النتيجة: سرعة تنفيذ وشفافية ومساءلة", "Outcome: speed, visibility, and accountability"],
    ],
    visual: "flow",
  },
  {
    eyebrow: "04 — طريقة العمل | Operating Model",
    titleAr: "من التسجيل حتى القرار الإداري",
    titleEn: "From data capture to management decision",
    summaryAr: "يسجّل المستخدم الحدث من الهاتف أو الويب، تتحقق المنصة من الصلاحية والسياق، تحفظ البيانات ضمن نطاق الشركة، ثم تعرضها في اللوحات والتقارير مع تنبيهات وإجراءات متابعة.",
    summaryEn: "Users capture events on mobile or web; NiroVera validates context and permissions, stores company-scoped data, then turns it into dashboards, reports, alerts, and actions.",
    steps: [
      ["01", "إدخال الحدث", "Capture"],
      ["02", "التحقق والصلاحيات", "Validate"],
      ["03", "الحفظ والمزامنة", "Sync"],
      ["04", "التحليل والتقرير", "Analyze"],
      ["05", "القرار والمتابعة", "Act"],
    ],
    visual: "steps",
  },
  {
    eyebrow: "05 — الحضور | Attendance",
    titleAr: "حضور موثوق مرتبط بالموقع والجدول",
    titleEn: "Trusted attendance linked to location and schedule",
    summaryAr: "تتحقق المنصة من موقع الموظف مقارنة بنطاق العمل المحدد، وتربط تسجيل الدخول والخروج بالوردية، ثم تعرض التأخير والغياب وساعات العمل في تقارير يومية وشهرية.",
    summaryEn: "NiroVera validates employee location against the approved work radius, links check-in/out to shifts, and reports lateness, absence, and worked hours.",
    points: [
      ["نطاق جغرافي قابل للضبط لكل فرع", "Configurable geofence for every workstation"],
      ["جداول وورديات وصيغ وقت 12/24 ساعة", "Schedules, shifts, and 12/24-hour formats"],
      ["لوحات يومية وشهرية وتحليلات مقارنة", "Daily, monthly, and comparative analytics"],
    ],
    visual: "location",
  },
  {
    eyebrow: "06 — المهام | Tasks",
    titleAr: "تنظيم المهام حسب الفروع والمجلدات",
    titleEn: "Tasks organized by stations and folders",
    summaryAr: "تدعم المنصة إنشاء المهام وإسنادها للأفراد أو الفرق، تنظيمها داخل أقسام قابلة للبحث، توثيق التقدم والتعليقات والمرفقات، وتصعيد المتأخر أو المعرّض للخطر.",
    summaryEn: "Tasks can be assigned to people or teams, arranged in searchable folders, updated with comments and attachments, and escalated when delayed or at risk.",
    points: [
      ["حالات وأولويات ومواعيد نهائية واضحة", "Clear statuses, priorities, and deadlines"],
      ["سجل تقدم ومرفقات وتعليقات موثقة", "Documented progress, files, and comments"],
      ["تصعيد آلي ومراجعة إدارية", "Automated escalation and management review"],
    ],
    visual: "tasks",
  },
  {
    eyebrow: "07 — الموارد البشرية | Human Resources",
    titleAr: "هيكل إداري مرن وصلاحيات دقيقة",
    titleEn: "Flexible hierarchy and precise permissions",
    summaryAr: "يمكن بناء مستويات الموارد البشرية بما يناسب المنشأة، وتعيين المسؤولين حسب الفرع أو المجموعة أو المستوى، مع توجيه الطلبات والشكاوى إلى المسار الإداري الصحيح.",
    summaryEn: "Organizations can define HR tiers, assign responsibility by station or group, and route requests and complaints through the correct escalation path.",
    points: [
      ["ملفات موظفين وبيانات مهنية وشهادات", "Employee profiles, professional data, and certificates"],
      ["إجازات وأرصدة وموافقات واتصالات HR", "Leave balances, approvals, and HR communication"],
      ["أدوار مخصصة ونطاقات إدارة قابلة للضبط", "Custom roles and configurable management scopes"],
    ],
    visual: "hierarchy",
  },
  {
    eyebrow: "08 — الأداء والتقارير | Performance & Reports",
    titleAr: "بيانات تشغيلية تتحول إلى قرارات",
    titleEn: "Operational data turned into decisions",
    summaryAr: "تجمع لوحات الأداء بيانات المهام والحضور والنقاط والملاحظات لتقديم رؤية على مستوى الموظف والفرع والمنشأة، مع تقارير قابلة للتصدير وهوية مؤسسية مخصصة.",
    summaryEn: "Performance dashboards combine tasks, attendance, points, and observations at employee, station, and company level, with branded exportable reports.",
    points: [
      ["مقارنة موظف بموظف وفرع بفرع", "Employee-to-employee and station comparisons"],
      ["تقارير يومية ودورية وملخصات تنفيذية", "Daily, periodic, and executive summaries"],
      ["تصدير احترافي مع هوية الشركة", "Professional exports with company branding"],
    ],
    visual: "analytics",
  },
  {
    eyebrow: "09 — التواصل | Communication",
    titleAr: "تواصل داخلي منظم وقابل للرجوع",
    titleEn: "Structured, searchable internal communication",
    summaryAr: "توفر NiroVera محادثات للفروع والفرق، رسائل مباشرة، مشاركة وسائط، بحثًا داخل المحادثات، وإرسال بريد إلكتروني عند الحاجة، مع تقارير مجهولة تحمي هوية المرسل.",
    summaryEn: "NiroVera provides station and team chats, direct messages, media sharing, conversation search, email delivery, and identity-protected anonymous reporting.",
    points: [
      ["محادثات فرق وفروع ومجموعات مخصصة", "Team, station, and custom group chats"],
      ["مشاركة ملفات وصوت وصور", "File, voice, and image sharing"],
      ["بلاغات مجهولة ومسار متابعة آمن", "Anonymous reports with a secure follow-up path"],
    ],
    visual: "messages",
  },
  {
    eyebrow: "10 — الملفات والتوقيع | Files & E-Signature",
    titleAr: "إدارة ملفات وتوقيع رقمي قابل للتحقق",
    titleEn: "File management and verifiable digital signing",
    summaryAr: "ينشئ المستخدم توقيعه، يرفع المستند، يحدد موضع التوقيع، ثم تصدر نسخة تحمل معرّف تحقق وبصمة رقمية تربط سجل التوقيع بالملف النهائي.",
    summaryEn: "Users create a signature, upload a document, place the signature, and generate a final copy carrying a verification ID and cryptographic fingerprint.",
    steps: [
      ["01", "حفظ التوقيع", "Save signature"],
      ["02", "رفع المستند", "Upload document"],
      ["03", "اختيار الموضع", "Place signature"],
      ["04", "إصدار نسخة موثقة", "Issue verified copy"],
    ],
    visual: "signature",
  },
  {
    eyebrow: "11 — الذكاء والمساعدة | Intelligence & Assistance",
    titleAr: "مساعد Niro لفهم بيانات المنصة",
    titleEn: "Niro assistant for platform-wide insight",
    summaryAr: "يساعد Niro المستخدم في قراءة البيانات التشغيلية وصياغة الملخصات والإجابة عن الأسئلة المتعلقة بالأداء والمهام والحضور ضمن صلاحيات المستخدم.",
    summaryEn: "Niro helps users understand operational data, produce summaries, and answer questions about performance, tasks, and attendance within their access scope.",
    points: [
      ["أسئلة بلغة طبيعية وإجابات مرتبطة بالسياق", "Natural-language questions with contextual answers"],
      ["تلخيص المؤشرات والمشكلات والإجراءات", "Summaries of KPIs, issues, and actions"],
      ["احترام أدوار المستخدم ونطاق بياناته", "Role-aware, scope-limited data access"],
    ],
    visual: "assistant",
  },
  {
    eyebrow: "12 — الأمان | Security Architecture",
    titleAr: "عزل البيانات والحماية حسب الدور",
    titleEn: "Tenant isolation and role-based protection",
    summaryAr: "تعتمد المنصة على نطاق مستقل لكل شركة، جلسات دخول محمية، تحقق بخطوتين عبر رمز مؤقت، كلمات مرور مجزأة، وصلاحيات تتحكم في عرض وتنفيذ كل عملية.",
    summaryEn: "The platform uses company-scoped data, protected sessions, one-time-code verification, hashed passwords, and role-based controls for every sensitive action.",
    points: [
      ["عزل صارم بين بيانات الشركات", "Strict isolation between company datasets"],
      ["رموز تحقق مؤقتة وأحدث رمز فقط صالح", "Expiring OTPs where only the newest code is valid"],
      ["سجل تدقيق للإجراءات الحساسة", "Audit trail for sensitive actions"],
    ],
    visual: "security",
  },
  {
    eyebrow: "13 — الملكية الفكرية | Intellectual Property",
    titleAr: "منظومة مترابطة بهوية وتجربة أصلية",
    titleEn: "A connected system with an original identity and experience",
    summaryAr: "تتمثل القيمة الإبداعية في جمع الوظائف التشغيلية ضمن تجربة موحدة، وتصميم مسارات مترابطة للحضور والمهام والموارد البشرية والتقارير والتوقيع، مع هوية NiroVera البصرية ودعم متعدد اللغات.",
    summaryEn: "The original value lies in unifying operational functions and designing connected flows across attendance, tasks, HR, reporting, and signing under the NiroVera identity.",
    points: [
      ["اسم وهوية وواجهات NiroVera", "NiroVera name, identity, and interfaces"],
      ["تسلسل شاشات ومسارات استخدام مترابطة", "Connected screen sequences and user journeys"],
      ["هيكلة مخصصة للبيانات والصلاحيات والتقارير", "Custom data, permissions, and reporting structure"],
    ],
    visual: "brand",
  },
  {
    eyebrow: "14 — بيانات الإيداع | Submission Details",
    titleAr: "وثيقة تعريف بالمصنف البرمجي",
    titleEn: "Software Work Identification Document",
    summaryAr: "أُعد هذا العرض لتوثيق فكرة NiroVera، مكوناته، طريقة تشغيله، وتجربته البصرية بوصفه مصنفًا برمجيًا متكاملًا.",
    summaryEn: "This presentation documents the NiroVera concept, components, operating method, and visual experience as an integrated software work.",
    details: [
      ["اسم المصنف | Work title", "NiroVera"],
      ["نوع المصنف | Work type", "منصة ويب وتطبيق أعمال | Web-based business platform"],
      ["صاحب الحقوق | Rights holder", "____________________________"],
      ["الإصدار | Version", "1.0"],
      ["تاريخ الوثيقة | Document date", "13 July 2026"],
    ],
    visual: "document",
  },
];