/**
 * Sales deck slide content — intent from design handoff Sales Deck.
 * Illustrative pitch figures only; not live derived platform metrics.
 */

export const SALES_DECK_META = {
  dateAr: "أغسطس 2026",
  dateEn: "August 2026",
  kindAr: "عرض تعريفي",
  kindEn: "Sales briefing",
};

/** @typedef {'cover'|'divider'|'problem'|'cost'|'command'|'modules'|'assistant'|'safety'|'compare'|'roi'|'rollout'|'plans'|'close'} SlideKind */

/**
 * @type {Array<{
 *   id: string,
 *   kind: SlideKind,
 *   labelAr: string,
 *   labelEn: string,
 *   notesAr?: string,
 *   notesEn?: string,
 *   [key: string]: unknown,
 * }>}
 */
export const SALES_DECK_SLIDES = [
  {
    id: "cover",
    kind: "cover",
    labelAr: "الغلاف",
    labelEn: "Cover",
    titleAr: "منصة تشغيل الفروع والقوى العاملة الميدانية",
    titleEn: "Station operations and field workforce platform",
    subAr: "إدارة العمليات والحضور والسلامة والرواتب في نظام واحد، مبني للميدان السعودي.",
    subEn: "Operations, attendance, safety, and payroll in one system — built for the Saudi field.",
    notesAr: "عرّف بنفسك وبالمنصة في جملة واحدة. المدة المستهدفة خمس عشرة دقيقة.",
    notesEn: "Introduce yourself and the platform in one sentence. Target length: fifteen minutes.",
  },
  {
    id: "problem-divider",
    kind: "divider",
    labelAr: "فاصل — المشكلة",
    labelEn: "Divider — Problem",
    chapter: "01",
    titleAr: "المشكلة",
    titleEn: "The problem",
    notesAr: "انتقال قصير. لا تقرأ الشريحة، قل فقط: لنبدأ بالوضع الحالي.",
    notesEn: "Short transition. Do not read the slide — just say: let’s start with today.",
  },
  {
    id: "reality",
    kind: "problem",
    labelAr: "واقع التشغيل اليوم",
    labelEn: "Operations today",
    titleAr: "واقع التشغيل اليوم",
    titleEn: "How operations look today",
    subAr: "المعلومة موجودة، لكنها موزّعة على أدوات لا تتحدث مع بعضها.",
    subEn: "The data exists — but it is scattered across tools that never talk.",
    stats: [
      {
        value: "7",
        unitAr: "",
        unitEn: "",
        bodyAr: "أدوات منفصلة في المتوسط: إكسل، واتساب، ورق، بريد، ونظام حضور مستقل.",
        bodyEn: "Separate tools on average: Excel, WhatsApp, paper, email, and a standalone attendance system.",
        tone: "ink",
      },
      {
        value: "3",
        unitAr: "ساعات",
        unitEn: "hrs",
        bodyAr: "يوميًا من وقت المشرفين في جمع البيانات وتجميع التقارير يدويًا.",
        bodyEn: "Of supervisor time each day spent gathering data and assembling reports by hand.",
        tone: "ink",
      },
      {
        value: "48",
        unitAr: "ساعة",
        unitEn: "hrs",
        bodyAr: "متوسط التأخير حتى تصل مشكلة ميدانية إلى من يملك قرار حلّها.",
        bodyEn: "Average delay before a field issue reaches the person who can decide.",
        tone: "danger",
      },
    ],
    notesAr: "أرقام من مقابلات تشغيل — لا تدّعِ أنها دراسة رسمية.",
    notesEn: "Figures from operator interviews — do not present them as a formal study.",
  },
  {
    id: "cost",
    kind: "cost",
    labelAr: "تكلفة التشتت",
    labelEn: "Cost of fragmentation",
    titleAr: "تكلفة التشتت",
    titleEn: "The cost of fragmentation",
    items: [
      {
        titleAr: "ساعات إضافية غير مبررة",
        titleEn: "Unjustified overtime",
        bodyAr: "بلا ربط بين الجدولة والحضور الفعلي، تُعتمد ساعات لا يمكن التحقق منها.",
        bodyEn: "Without linking roster to verified attendance, hours get approved that cannot be proven.",
      },
      {
        titleAr: "توقفات تتكرر",
        titleEn: "Recurring downtime",
        bodyAr: "لا يوجد سجل يربط العطل بسببه، فتتكرر المشكلة نفسها كل ربع سنة.",
        bodyEn: "No record ties a failure to its cause — so the same issue returns every quarter.",
      },
      {
        titleAr: "مخاطر امتثال",
        titleEn: "Compliance risk",
        bodyAr: "عند التدقيق، إثبات من فعل ماذا ومتى يستغرق أيامًا من البحث في الأرشيف.",
        bodyEn: "At audit time, proving who did what and when takes days of archive digging.",
      },
    ],
    outcomeAr: "القرارات تُتخذ على بيانات عمرها يومان، بينما الفرع تعمل بالساعة.",
    outcomeEn: "Decisions ride on two-day-old data while the station runs by the hour.",
    notesAr: "اربطها بأرقام العميل إن توفرت قبل الاجتماع.",
    notesEn: "Tie this to the buyer’s own numbers if available before the meeting.",
  },
  {
    id: "solution-divider",
    kind: "divider",
    labelAr: "فاصل — الحل",
    labelEn: "Divider — Solution",
    chapter: "02",
    titleAr: "الحل",
    titleEn: "The solution",
    notesAr: "انتقال. هنا يبدأ العرض الفعلي للمنصة.",
    notesEn: "Transition. The live product story starts here.",
  },
  {
    id: "command",
    kind: "command",
    labelAr: "مركز القيادة",
    labelEn: "Command center",
    titleAr: "مركز القيادة",
    titleEn: "Command center",
    subAr: "تفتح المنصة على ما يحتاج قرارك اليوم، مرتبًا بأثره على التشغيل — لا بتاريخ وصوله.",
    subEn: "The platform opens on what needs your decision today — ranked by operational impact, not inbox order.",
    score: "82",
    scoreHintAr: "مؤشر الجاهزية التشغيلية",
    scoreHintEn: "Operational readiness index",
    scoreBodyAr: "رقم واحد يجمع الحضور وإنجاز المهام وإغلاق بنود السلامة وجاهزية الأصول.",
    scoreBodyEn: "One figure combining attendance, task completion, safety closures, and asset readiness.",
    queue: [
      {
        severity: "danger",
        titleAr: "توقف مضخة التبريد — الجبيل 2",
        titleEn: "Cooling pump down — Jubail 2",
        metaAr: "يعطّل 3 مهام",
        metaEn: "Blocks 3 tasks",
      },
      {
        severity: "warn",
        titleAr: "7 طلبات إجازة تتجاوز حد الوردية",
        titleEn: "7 leave requests breach shift coverage",
        metaAr: "الأسبوع القادم",
        metaEn: "Next week",
      },
      {
        severity: "warn",
        titleAr: "عقد صيانة بانتظار توقيعك",
        titleEn: "Maintenance contract awaiting your signature",
        metaAr: "ينتهي خلال 48 ساعة",
        metaEn: "Expires in 48 hours",
      },
    ],
    notesAr: "لوحات تقليدية تعرض أرقامًا؛ هذه تعرض قرارات مرتبة بأثرها.",
    notesEn: "Classic dashboards show numbers; this shows decisions ranked by impact.",
  },
  {
    id: "modules",
    kind: "modules",
    labelAr: "وحدات المنصة",
    labelEn: "Platform modules",
    titleAr: "وحدات المنصة",
    titleEn: "Platform modules",
    subAr: "وحدات متصلة فوق قاعدة واحدة — تسجيل حضور واحد يغذّي الجدولة والرواتب والتقارير معًا.",
    subEn: "Connected modules on one data base — a single check-in feeds roster, payroll, and reports together.",
    modules: [
      { ar: "مركز القيادة", en: "Command", featured: true },
      { ar: "الحضور والانصراف", en: "Attendance" },
      { ar: "المهام والعمليات", en: "Operations" },
      { ar: "إثبات العمل", en: "Work proof" },
      { ar: "التوقيع الرقمي", en: "Signing" },
      { ar: "التقرير اليومي", en: "Daily report" },
      { ar: "التقارير والتحليلات", en: "Reports" },
      { ar: "المحادثات التشغيلية", en: "Ops chat" },
      { ar: "الورديات", en: "Shifts" },
      { ar: "طلبات الإجازة", en: "Leave" },
      { ar: "الموارد البشرية", en: "HR" },
      { ar: "التوظيف", en: "Recruitment" },
      { ar: "الأداء", en: "Performance" },
      { ar: "الهيكل التنظيمي", en: "Org" },
      { ar: "السلامة HSE", en: "HSE" },
      { ar: "صوت الموظف", en: "Employee voice" },
      { ar: "الرواتب", en: "Payroll" },
      { ar: "المصروفات", en: "Expenses" },
      { ar: "المخزون والأصول", en: "Inventory" },
      { ar: "الملفات", en: "Files" },
      { ar: "المساعد الذكي", en: "Assistant" },
    ],
    notesAr: "النقطة: كلها فوق قاعدة واحدة — الحضور ينعكس فورًا في الرواتب.",
    notesEn: "Point: one database — attendance lands in payroll immediately.",
  },
  {
    id: "assistant",
    kind: "assistant",
    labelAr: "المساعد الذكي",
    labelEn: "Smart assistant",
    titleAr: "المساعد الذكي",
    titleEn: "Smart assistant",
    questionAr: "لماذا انخفض إنجاز المهام في فرع الجبيل 2 هذا الأسبوع؟",
    questionEn: "Why did task completion drop at Jubail 2 this week?",
    answerAr:
      "الانخفاض مصدره سبب واحد: توقف مضخة التبريد يوم الأحد أوقف 3 مهام معتمدة عليها، ولم تُعَد جدولتها. الحضور والطاقم لم يتغيرا.",
    answerEn:
      "One root cause: Sunday’s cooling-pump outage blocked three dependent tasks that were never rescheduled. Attendance and crew were unchanged.",
    metrics: [
      { labelAr: "العمليات", labelEn: "Ops", value: "-23%" },
      { labelAr: "الحضور", labelEn: "Attendance", value: "0%" },
      { labelAr: "الأصول", labelEn: "Assets", value: "31h" },
    ],
    actionAr: "أعد جدولة المهام الثلاث",
    actionEn: "Reschedule the three tasks",
    notesAr: "يقرأ بيانات الشركة، يعرض مصدر الرقم، وينتهي بزر تنفيذ.",
    notesEn: "Reads company data, cites the source, ends in an action button.",
  },
  {
    id: "safety",
    kind: "safety",
    labelAr: "السلامة والامتثال",
    labelEn: "Safety & compliance",
    titleAr: "السلامة والامتثال",
    titleEn: "Safety and compliance",
    pillars: [
      {
        titleAr: "سجل تدقيق تلقائي",
        titleEn: "Automatic audit trail",
        bodyAr: "كل تغيير يُسجَّل من مصدره: من، ومتى، وماذا تغيّر — دون الاعتماد على تذكّر المستخدم.",
        bodyEn: "Every change is logged at source: who, when, what changed — without relying on user discipline.",
      },
      {
        titleAr: "بلاغ مجهول محمي",
        titleEn: "Protected anonymous report",
        bodyAr: "الموظف يبلّغ برمز متغيّر، فلا يمكن ربط البلاغ بصاحبه حتى من داخل النظام.",
        bodyEn: "Staff report with a rotating code — the report cannot be tied to the raiser even inside the system.",
      },
      {
        titleAr: "تصعيد تلقائي",
        titleEn: "Automatic escalation",
        bodyAr: "إن تجاوز البلاغ زمن الاستجابة، ينتقل تلقائيًا إلى المستوى الأعلى في سلسلة المسؤولية.",
        bodyEn: "If a report burns its response quota, it escalates automatically up the accountability chain.",
      },
    ],
    streak: "214",
    streakAr: "يومًا متتاليًا دون حادث يفقد وقت عمل — مقاسة تلقائيًا من سجل الحوادث، لا مدخلة يدويًا.",
    streakEn: "Consecutive days without a lost-time incident — measured from the incident log, never typed in by hand.",
    notesAr: "مهم للجهات الحكومية: التدقيق لا يعتمد على انضباط المستخدم.",
    notesEn: "Critical for public sector: audit does not depend on user discipline.",
  },
  {
    id: "impact-divider",
    kind: "divider",
    labelAr: "فاصل — الأثر",
    labelEn: "Divider — Impact",
    chapter: "03",
    titleAr: "الأثر",
    titleEn: "Impact",
    notesAr: "انتقال إلى ما يهم من يوقّع الشيك.",
    notesEn: "Transition to what matters to the person who signs the check.",
  },
  {
    id: "compare",
    kind: "compare",
    labelAr: "مقارنة",
    labelEn: "Comparison",
    titleAr: "NiroVera مقابل الأنظمة التقليدية",
    titleEn: "NiroVera vs traditional systems",
    rows: [
      {
        criterionAr: "مدة التطبيق",
        criterionEn: "Time to live",
        otherAr: "6 إلى 18 شهرًا",
        otherEn: "6–18 months",
        oursAr: "أسبوعان",
        oursEn: "Two weeks",
      },
      {
        criterionAr: "التدريب المطلوب",
        criterionEn: "Training needed",
        otherAr: "دورات لكل وحدة",
        otherEn: "Courses per module",
        oursAr: "الفني يسجّل حضوره من هاتفه بلا تدريب",
        oursEn: "Technician clocks in from the phone with no training",
      },
      {
        criterionAr: "اللغة والاتجاه",
        criterionEn: "Language & direction",
        otherAr: "عربية مضافة على واجهة إنجليزية",
        otherEn: "Arabic bolted onto an English UI",
        oursAr: "عربية أصلية من اليمين لليسار",
        oursEn: "Native Arabic RTL from the start",
      },
      {
        criterionAr: "التكلفة السنوية",
        criterionEn: "Annual cost",
        otherAr: "مئات الآلاف قبل التخصيص",
        otherEn: "Hundreds of thousands before customization",
        oursAr: "اشتراك واضح بلا رسوم تطبيق مخفية",
        oursEn: "Clear subscription — no hidden implementation fees",
      },
    ],
    notesAr: "لا تهاجم الأنظمة الكبيرة — الرسالة: تعقيد لا تحتاجه شركة ميدانية.",
    notesEn: "Do not attack large ERPs — message: complexity a field company does not need.",
  },
  {
    id: "roi",
    kind: "roi",
    labelAr: "العائد المتوقع",
    labelEn: "Expected return",
    titleAr: "العائد المتوقع",
    titleEn: "Expected return",
    subAr: "تقديرات لشركة بـ 150 موظفًا وست فروع، خلال أول اثني عشر شهرًا — ليست وعودًا تعاقدية.",
    subEn: "Estimates for a company with 150 employees and six stations in the first twelve months — not contractual promises.",
    figures: [
      {
        value: "-31%",
        bodyAr: "في الساعات الإضافية، بربط الجدولة بالحضور المتحقق جغرافيًا.",
        bodyEn: "In overtime, by linking roster to geofenced attendance.",
      },
      {
        value: "-64%",
        bodyAr: "في زمن وصول المشكلة الميدانية إلى صاحب القرار.",
        bodyEn: "In time for a field issue to reach the decision owner.",
      },
      {
        value: "15h",
        bodyAr: "تُوفَّر أسبوعيًا من وقت المشرفين كانت تذهب لتجميع التقارير.",
        bodyEn: "Saved weekly from supervisor time once spent assembling reports.",
      },
    ],
    notesAr: "قدّمها كتقديرات، لا كوعود تعاقدية.",
    notesEn: "Present as estimates, never as contractual promises.",
  },
  {
    id: "rollout",
    kind: "rollout",
    labelAr: "خطة التطبيق",
    labelEn: "Rollout plan",
    titleAr: "خطة التطبيق",
    titleEn: "Rollout plan",
    weeks: [
      {
        weekAr: "الأسبوع 1",
        weekEn: "Week 1",
        titleAr: "التهيئة",
        titleEn: "Setup",
        bodyAr: "رفع الموظفين والفروع، رسم الهيكل، وتحديد النطاق الجغرافي لكل فرع.",
        bodyEn: "Load people and stations, draw the org, and set each station’s geofence.",
      },
      {
        weekAr: "الأسبوع 2",
        weekEn: "Week 2",
        titleAr: "التشغيل التجريبي",
        titleEn: "Pilot live",
        bodyAr: "فرع واحد تعمل بالكامل على المنصة، مع فريق التشغيل الفعلي لا فريق تجريبي.",
        bodyEn: "One station runs fully on the platform with the real ops crew — not a sandbox team.",
      },
      {
        weekAr: "الأسبوع 3",
        weekEn: "Week 3",
        titleAr: "التوسعة",
        titleEn: "Scale-out",
        bodyAr: "بقية الفروع تنضم دفعة واحدة، والتقارير المجدولة تصل تلقائيًا.",
        bodyEn: "Remaining stations join in one wave; scheduled reports start arriving automatically.",
      },
    ],
    footnoteAr: "لا يوجد فريق تطبيق يُقيم في مقر العميل، ولا رسوم تهيئة منفصلة.",
    footnoteEn: "No on-site implementation team camping at HQ — and no separate setup fee.",
    notesAr: "الشركة تعمل على المنصة من الأسبوع الثالث.",
    notesEn: "The company is live on the platform from week three.",
  },
  {
    id: "plans",
    kind: "plans",
    labelAr: "الباقات",
    labelEn: "Plans",
    titleAr: "الباقات",
    titleEn: "Plans",
    plans: [
      {
        nameAr: "البداية",
        nameEn: "Starter",
        priceNum: "29",
        priceUnitAr: "ريال / موظف / شهر",
        priceUnitEn: "SAR / employee / month",
        bodyAr: "المهام والحضور والمحادثات والملفات. حتى 30 موظفًا وفرعين.",
        bodyEn: "Tasks, attendance, chat, and files. Up to 30 employees and two stations.",
        featured: false,
      },
      {
        nameAr: "الاحترافية",
        nameEn: "Professional",
        priceNum: "49",
        priceUnitAr: "ريال / موظف / شهر",
        priceUnitEn: "SAR / employee / month",
        bodyAr: "كل الوحدات الإحدى والعشرين، بما فيها الرواتب والمخزون والتوقيع الرقمي والمساعد الذكي.",
        bodyEn: "All 21 modules, including payroll, inventory, digital sign, and the smart assistant.",
        featured: true,
        badgeAr: "الأكثر اختيارًا",
        badgeEn: "Most chosen",
      },
      {
        nameAr: "المؤسسات",
        nameEn: "Enterprise",
        priceLabelAr: "حسب الاتفاق",
        priceLabelEn: "By agreement",
        bodyAr: "استضافة مخصصة، تكامل مع الأنظمة القائمة، ودعم تشغيلي مخصص.",
        bodyEn: "Dedicated hosting, integration with existing systems, and dedicated ops support.",
        featured: false,
      },
    ],
    notesAr: "ثبّت الأسعار قبل العرض. الرسالة: السعر لكل موظف شهريًا، بلا رسوم مخفية.",
    notesEn: "Lock prices before the meeting. Message: per-employee monthly, no hidden fees.",
  },
  {
    id: "close",
    kind: "close",
    labelAr: "الخطوة التالية",
    labelEn: "Next step",
    titleAr: "فرع واحد، أسبوعان، بلا التزام",
    titleEn: "One station, two weeks, no commitment",
    subAr: "نشغّل فرع واحد من فروعكم على المنصة، وتقارنون النتيجة بأنفسكم قبل أي قرار.",
    subEn: "We run one of your stations on the platform — you compare the result yourselves before any decision.",
    contactNameAr: "نيار عبدالله الرنياوي",
    contactNameEn: "Niyar Abdullah Al-Raniawi",
    email: "niyar@powercares.pro",
    phone: "+966 59 541 4472",
    notesAr: "اختم بطلب واضح واترك الشريحة أثناء الأسئلة.",
    notesEn: "Close with a clear ask and leave this slide up during Q&A.",
  },
];
