import React from "react";
import { GitBranch, KeyRound, MapPin, Move, Route, UserCog, UserPlus, Users } from "lucide-react";

const sections = [
  [UserPlus, "إنشاء موظف أو محطة", "Create employee or station", "اضغط «إضافة»، ثم اختر موظفًا أو محطة. عند إنشاء موظف أدخل الاسم والبريد والمسمى الوظيفي، وحدد مكانه في الشجرة.", "Select Add, then choose an employee or station. For employees, enter the name, email, job title and tree position."],
  [UserCog, "إنشاء منصب موارد بشرية", "Create an HR position", "أنشئ الموظف من الشجرة واكتب المسمى المطلوب، مثل مدير الموارد البشرية أو مسؤول شؤون الموظفين. ويمكن تعديل المسمى لاحقًا من بطاقة الموظف.", "Create the employee from the tree and enter a title such as HR Manager or Employee Affairs Officer. The title can be edited later."],
  [KeyRound, "تحديد الصلاحيات", "Set permissions", "لكل قسم اختر: مخفي، عرض فقط، أو إدارة كاملة. وتشمل الصلاحيات الشكاوى والسلامة والكاميرات والرواتب والموظفين والأداء والحضور والموارد البشرية والمخزون.", "For every department choose Hidden, View, or Full management, including complaints, safety, cameras, payroll, employees, performance, attendance, HR and inventory."],
  [MapPin, "تحديد نطاق المحطة", "Set station scope", "ضع الموظف تحت محطة ليصبح مرتبطًا بها، أو عيّنه مديرًا لمحطة واحدة أو عدة محطات. موضعه في الشجرة يوضح نطاقه الإداري.", "Place an employee under a station to link them to it, or assign them to manage one or more stations. Tree placement shows their scope."],
  [GitBranch, "تحديد التبعية", "Define reporting lines", "العقدة الموجودة أعلى موظف تمثل المسؤول المباشر، وما تحت الموظف يمثل الأشخاص أو المحطات التابعة له.", "The node above an employee represents their manager; people and stations below report to that employee."],
  [Move, "النقل وإعادة التنظيم", "Move and reorganize", "اسحب العقدة أعلى أو أسفل عقدة أخرى لتغيير التبعية، أو إلى اليمين واليسار لتغيير ترتيبها، أو داخل محطة لربطها بها.", "Drag a node above or below another to change reporting, left or right to reorder, or inside a station to link it."],
  [Users, "الموظفون غير المعيّنين", "Unassigned employees", "يظهر الموظف غير المرتبط بموقع إداري في قائمة مستقلة، ويمكن سحبه إلى المحطة أو المسؤول المناسب دون إنشاء حساب جديد.", "Employees without a reporting position appear separately and can be dragged to the correct station or manager without creating another account."],
  [Route, "مسار تصعيد الشكاوى", "Complaint escalation", "أضف الأشخاص المطلوبين إلى مسار الشكاوى؛ ويحدد ترتيبهم الرأسي في الشجرة مستوى وصول الشكوى وتصعيدها تلقائيًا.", "Add the required people to the complaint path; their vertical tree order automatically determines escalation levels."],
];

export default function OrgTreeDetailedSections({ ar }) {
  return <div className="grid gap-2 md:grid-cols-2">{sections.map(([Icon, arTitle, enTitle, arText, enText], index) => <div key={enTitle} className="flex gap-3 rounded-md border bg-card p-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-accent/10 text-xs font-bold text-accent">{index + 1}</span><div><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-accent" /><p className="text-xs font-semibold">{ar ? arTitle : enTitle}</p></div><p className="mt-1 text-[11px] leading-5 text-muted-foreground">{ar ? arText : enText}</p></div></div>)}</div>;
}