import React from "react";
import SmartDepartmentGrid from "@/components/hr/SmartDepartmentGrid";

export default function OrgTreeNodeFields({ type, setType, refId, setRefId, title, setTitle, rank, setRank, stationName, setStationName, permissions, setPermissions, employees, stations, usedEmployees, editing, ar }) {
  const choices = type === "employee" ? employees.filter((employee) => editing || !usedEmployees.includes(employee.id)) : stations;
  return <>
    {!editing && <div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => { setType("station"); setRefId(""); }} className={`rounded-md border p-3 text-sm ${type === "station" ? "border-accent bg-accent/10" : "border-border"}`}>{ar ? "محطة / فرع / مقر" : "Station / branch / HQ"}</button><button type="button" onClick={() => { setType("employee"); setRefId(""); }} className={`rounded-md border p-3 text-sm ${type === "employee" ? "border-accent bg-accent/10" : "border-border"}`}>{ar ? "موظف" : "Employee"}</button></div>}
    <select value={refId} disabled={editing} onChange={(event) => setRefId(event.target.value)} required className="w-full rounded-md border px-3 py-2 text-sm"><option value="">{type === "employee" ? (ar ? "اختر الموظف" : "Select employee") : (ar ? "اختر المحطة أو الفرع" : "Select station or branch")}</option>{choices.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
    {type === "station" && editing && <input value={stationName} onChange={(event) => setStationName(event.target.value)} required placeholder={ar ? "اسم المحطة" : "Station name"} className="w-full rounded-md border px-3 py-2 text-sm" />}
    {type === "employee" && <SmartDepartmentGrid permissions={permissions} onChange={setPermissions} ar={ar} />}
    {type === "employee" && editing && <label className="block space-y-1"><span className="text-xs font-semibold text-muted-foreground">{ar ? "رتبة المنصب" : "Position rank"}</span><select value={rank || ""} onChange={(event) => setRank(event.target.value || null)} className="w-full rounded-md border px-3 py-2 text-sm"><option value="">{ar ? "بدون تمييز (تلقائي)" : "No distinction (automatic)"}</option><option value="lead">{ar ? "قائد فريق" : "Team lead"}</option><option value="supervisor">{ar ? "سوبرفايزر" : "Supervisor"}</option><option value="manager">{ar ? "مدير" : "Manager"}</option></select></label>}
    <input value={title} onChange={(event) => setTitle(event.target.value)} required placeholder={type === "employee" ? (ar ? "المسمى الوظيفي" : "Job title") : (ar ? "وصف العقدة" : "Node label")} className="w-full rounded-md border px-3 py-2 text-sm" />
  </>;
}