import React from "react";

const BilingualText = ({ item }) => <div className="grid grid-cols-2 gap-10"><div className="space-y-4">{item.bodyAr.map((text) => <p key={text} className="text-justify text-[13px] leading-7">{text}</p>)}</div><div dir="ltr" className="space-y-4 border-l border-border pl-8">{item.bodyEn.map((text) => <p key={text} className="text-justify text-[12px] leading-6 text-muted-foreground">{text}</p>)}</div></div>;

export default function ProjectGuideClosing({ interconnection, pitch, author }) {
  return <>
    <article className="guide-page bg-background p-12 text-foreground"><div className="mb-10 border-b border-accent/50 pb-6"><p className="font-mono text-[9px] tracking-[.25em] text-accent">ONE CONNECTED OPERATING SYSTEM</p><h2 className="mt-3 font-heading text-4xl font-bold">{interconnection.titleAr}</h2><p dir="ltr" className="mt-2 text-sm text-muted-foreground">{interconnection.titleEn}</p></div><BilingualText item={interconnection} /><div className="mt-12 border-y border-accent/40 bg-primary px-10 py-8 text-center text-primary-foreground"><p className="font-heading text-3xl">جسد واحد، بعصب واحد</p><p dir="ltr" className="mt-2 text-xs tracking-[.2em] text-accent">ONE BODY • ONE NERVOUS SYSTEM</p></div></article>
    <article className="guide-page flex flex-col bg-primary p-12 text-primary-foreground"><p className="font-mono text-[9px] tracking-[.25em] text-accent">THE BUSINESS CASE</p><h2 className="mt-3 font-heading text-4xl font-bold">{pitch.titleAr}</h2><p dir="ltr" className="mt-2 text-sm text-primary-foreground/65">{pitch.titleEn}</p><div className="mt-10 grid grid-cols-2 gap-8">{pitch.pointsAr.map((text, index) => <div key={text} className="border-t border-accent/50 pt-4"><span className="font-heading text-3xl text-accent">{String(index + 1).padStart(2, "0")}</span><p className="mt-2 text-[13px] leading-7">{text}</p><p dir="ltr" className="mt-3 text-[11px] leading-6 text-primary-foreground/65">{pitch.pointsEn[index]}</p></div>)}</div><div className="mt-auto border border-accent/50 bg-background p-7 text-center text-foreground"><p className="font-heading text-2xl font-bold">{pitch.contactAr}</p><p dir="ltr" className="text-xs text-muted-foreground">{pitch.contactEn}</p><p className="mt-4 font-semibold">{author.nameAr}</p><p dir="ltr" className="text-xs">{author.nameEn}</p><p dir="ltr" className="mt-3 text-xs">{pitch.phone} · {pitch.emails.join(" · ")}</p></div></article>
  </>;
}