import React from "react";
import { BarChart, Bar, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer, RadarChart, Radar, PolarGrid, PolarAngleAxis, PieChart, Pie, Cell } from "recharts";

const COLORS = ["hsl(var(--accent))", "hsl(var(--primary))", "hsl(var(--chart-3))", "hsl(var(--chart-4))", "hsl(var(--chart-5))"];
const tooltipStyle = { border: "1px solid hsl(var(--border))", borderRadius: 8, fontSize: 10 };

export default function AcwaChartVisual({ type, data }) {
  if (type === "radar") return <div className="h-full"><p className="mb-1 text-center font-heading text-xs font-semibold">{data.title}</p><ResponsiveContainer width="100%" height={185}><RadarChart data={data.items}><PolarGrid stroke="hsl(var(--border))" /><PolarAngleAxis dataKey="label" tick={{ fontSize: 9 }} /><Radar dataKey="value" stroke="hsl(var(--accent))" fill="hsl(var(--accent))" fillOpacity={0.35} /></RadarChart></ResponsiveContainer></div>;
  if (type === "pie") return <div className="h-full"><p className="mb-1 text-center font-heading text-xs font-semibold">{data.title}</p><ResponsiveContainer width="100%" height={185}><PieChart><Pie data={data.items} dataKey="value" nameKey="label" cx="50%" cy="48%" innerRadius={38} outerRadius={72} label={({ label, value }) => `${label} ${value}%`} labelLine={false}>{data.items.map((_, index) => <Cell key={index} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip contentStyle={tooltipStyle} /></PieChart></ResponsiveContainer></div>;
  return <div className="h-full"><p className="mb-2 text-center font-heading text-xs font-semibold">{data.title}</p><ResponsiveContainer width="100%" height={180}><BarChart data={data.items} margin={{ top: 5, right: 8, left: -22, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="label" tick={{ fontSize: 9 }} /><YAxis tick={{ fontSize: 9 }} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="value" fill="hsl(var(--accent))" radius={[5, 5, 0, 0]} /><Bar dataKey="baseline" fill="hsl(var(--primary))" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div>;
}