import React from "react";
import { useI18n } from "@/lib/i18n";

export default function PurchaseFilters({ canViewAll, stations, stationId, onStation, period, onPeriod, startDate, endDate, onStartDate, onEndDate }) {
  const { t } = useI18n();
  return <div className="grid gap-3 rounded-xl border border-border bg-card p-3 sm:grid-cols-2 lg:grid-cols-3">
    {canViewAll && <label className="space-y-1 text-xs text-muted-foreground"><span>{t("purchaseStationFilter")}</span><select value={stationId} onChange={(e) => onStation(e.target.value)} className="w-full rounded-lg border px-3 py-2 text-sm text-foreground"><option value="all">{t("purchaseAllStations")}</option>{stations.map((station) => <option key={station.stationId} value={station.stationId}>{station.name}</option>)}</select></label>}
    <label className="space-y-1 text-xs text-muted-foreground"><span>{t("purchaseDateRange")}</span><select value={period} onChange={(e) => onPeriod(e.target.value)} className="w-full rounded-lg border px-3 py-2 text-sm text-foreground"><option value="month">{t("purchaseLastMonth")}</option><option value="3months">{t("purchaseLast3Months")}</option><option value="6months">{t("purchaseLast6Months")}</option><option value="year">{t("purchaseLastYear")}</option><option value="custom">{t("purchaseCustomRange")}</option></select></label>
    {period === "custom" && <div className="grid grid-cols-2 gap-2 sm:col-span-2 lg:col-span-1"><label className="space-y-1 text-xs text-muted-foreground"><span>{t("purchaseFromDate")}</span><input type="date" value={startDate} max={endDate || undefined} onChange={(e) => onStartDate(e.target.value)} className="w-full rounded-lg border px-3 py-2 text-sm text-foreground" /></label><label className="space-y-1 text-xs text-muted-foreground"><span>{t("purchaseToDate")}</span><input type="date" value={endDate} min={startDate || undefined} onChange={(e) => onEndDate(e.target.value)} className="w-full rounded-lg border px-3 py-2 text-sm text-foreground" /></label></div>}
  </div>;
}