import React from "react";
import { ArrowLeft, ArrowRight } from "lucide-react";

export default function RequestsList({ requests, items, employees, stations, canReview, canReviewAll, reviewerStationId, onReview, ar }) {
  const itemName = (id) => items.find((entry) => entry.id === id)?.name || "—";
  const employeeName = (id) => employees.find((employee) => employee.employeeId === id)?.name || "—";
  const stationName = (id) => stations.find((station) => station.stationId === id)?.name || "—";
  const status = (value) => ({ pending: ar ? "بانتظار الموافقة" : "Pending approval", issued: ar ? "تمت الموافقة والنقل" : "Approved and transferred", rejected: ar ? "مرفوض" : "Rejected" }[value] || value);
  return <div className="space-y-3">{requests.map((request) => <div key={request.id} className="rounded-xl border border-border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{itemName(request.itemId)} · {ar ? "الكمية" : "Qty"}: {request.quantity}</p>{request.totalCost != null && <p className="mt-1 text-xs font-medium text-accent">{ar ? "سعر الوحدة" : "Unit price"}: {Number(request.unitPrice || 0).toFixed(2)} {ar ? "ر.س" : "SAR"} · {ar ? "قيمة النقل" : "Transfer value"}: {Number(request.totalCost || 0).toFixed(2)} {ar ? "ر.س" : "SAR"}</p>}<p className="flex flex-wrap items-center gap-1.5 text-xs text-muted-foreground"><span>{stationName(request.sourceStationId)}</span>{ar ? <ArrowLeft className="h-3.5 w-3.5 shrink-0 text-accent" aria-label="إلى" /> : <ArrowRight className="h-3.5 w-3.5 shrink-0 text-accent" aria-label="to" />}<span>{stationName(request.stationId)}</span><span>· {employeeName(request.requesterId)}{request.notes ? ` — ${request.notes}` : ""}</span></p></div><span className="rounded-full bg-muted px-2 py-1 text-[10px]">{status(request.status)}</span></div>{canReview && (canReviewAll || request.sourceStationId === reviewerStationId) && request.status === "pending" && <div className="mt-3 flex gap-2"><button onClick={() => onReview(request.id, "approved")} className="rounded-lg bg-accent px-3 py-1.5 text-xs text-accent-foreground">{ar ? "موافقة ونقل الصنف" : "Approve and transfer"}</button><button onClick={() => onReview(request.id, "rejected")} className="rounded-lg border px-3 py-1.5 text-xs">{ar ? "رفض" : "Reject"}</button></div>}</div>)}{!requests.length && <p className="text-sm text-muted-foreground">{ar ? "لا توجد طلبات." : "No requests."}</p>}</div>;
}