import React from "react";
import { BookOpen, Radio, Radar, Upload, X } from "lucide-react";

const sections = (ar) => [
  { icon: Radio, title: ar ? "1. ربط كاميرا" : "1. Connect a camera", text: ar ? "اختر النظام، حدّد المحطة ونوع البث، أدخل رابط HLS أو MJPEG أو Web Player، ثم اختبر الاتصال واحفظ." : "Choose the system, station, and stream type; enter an HLS, MJPEG, or web-player URL, then test and save." },
  { icon: Upload, title: ar ? "2. استيراد CSV" : "2. Import CSV", text: ar ? "نزّل القالب، أضف الكاميرات، ارفع الملف، راجع الأخطاء ثم استورد الصفوف الصحيحة دفعة واحدة." : "Download the template, add cameras, upload it, review errors, then import all valid rows." },
  { icon: Radar, title: ar ? "3. اكتشاف ONVIF" : "3. ONVIF discovery", text: ar ? "أدخل نطاقًا مثل 192.168.1.0/24 وافحص الشبكة المحلية، ثم اضغط إعداد بجانب الجهاز المكتشف." : "Enter a range such as 192.168.1.0/24, scan the LAN, then select Set up beside a discovered device." },
  { icon: BookOpen, title: ar ? "4. عرض البث" : "4. Live viewing", text: ar ? "HLS وMJPEG والمشغلات المضمّنة تظهر داخل البطاقة مع حالة الاتصال وملء الشاشة. يحتاج RTSP الخام إلى بوابة RTSP-to-HLS." : "HLS, MJPEG, and embedded players appear in the card with connection status and fullscreen. Raw RTSP requires an RTSP-to-HLS gateway." },
];

export default function CameraGuideDialog({ ar, onClose }) {
  return <div className="fixed inset-0 z-[2000] grid place-items-center bg-foreground/40 p-4"><div className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-xl border border-border bg-card p-5 shadow-elevated" dir={ar ? "rtl" : "ltr"}><div className="flex items-center justify-between"><div><h2 className="font-heading text-xl font-semibold">{ar ? "دليل قسم الكاميرات" : "Camera Center guide"}</h2><p className="text-xs text-muted-foreground">{ar ? "شرح سريع لربط الكاميرات وعرضها" : "A quick guide to connecting and viewing cameras"}</p></div><button onClick={onClose} aria-label={ar ? "إغلاق" : "Close"}><X className="h-5 w-5" /></button></div><div className="mt-5 space-y-3">{sections(ar).map(({ icon: Icon, title, text }) => <section key={title} className="rounded-lg border border-border bg-muted/30 p-4"><div className="flex items-start gap-3"><span className="rounded-md bg-accent/10 p-2 text-accent"><Icon className="h-4 w-4" /></span><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></div></section>)}</div><div className="mt-4 rounded-lg border border-accent/25 bg-accent/5 p-3 text-xs leading-5 text-muted-foreground">{ar ? "مهم: لا تضع اسم المستخدم أو كلمة المرور داخل رابط البث. استخدم بوابة آمنة داخل شبكة الشركة لإدارة بيانات الدخول وتحويل RTSP إلى HLS." : "Important: Never place usernames or passwords in stream URLs. Use a secure on-site gateway to manage credentials and convert RTSP to HLS."}</div><div className="mt-5 flex justify-end"><button onClick={onClose} className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground">{ar ? "فهمت" : "Got it"}</button></div></div></div>;
}