import React from "react";

export default function CameraWizardFields({ form, set, stations, ar }) {
  const local = form.connectionType === "local";
  return <div className="grid gap-3 sm:grid-cols-2">
    <label className="space-y-1"><span className="text-xs font-semibold">{ar ? "اسم الكاميرا" : "Camera name"}</span><input required value={form.name} onChange={(e) => set("name", e.target.value)} placeholder={ar ? "مثال: مدخل الفرع" : "e.g. Branch entrance"} className="w-full rounded-md border p-3" /></label>
    <label className="space-y-1"><span className="text-xs font-semibold">{ar ? "المحطة" : "Station"}</span><select required value={form.stationId} onChange={(e) => set("stationId", e.target.value)} className="w-full rounded-md border p-3"><option value="">{ar ? "اختر المحطة" : "Select station"}</option>{stations.map((station) => <option key={station.id} value={station.id}>{station.name}</option>)}</select></label>
    <label className="space-y-1"><span className="text-xs font-semibold">{ar ? "نوع الاتصال" : "Connection type"}</span><select value={form.connectionType} onChange={(e) => set("connectionType", e.target.value)} className="w-full rounded-md border p-3"><option value="cloud">{ar ? "سحابة الشركة (Cloud P2P)" : "Provider cloud (Cloud P2P)"}</option><option value="local">{ar ? "شبكة محلية (Local)" : "Local network"}</option><option value="custom">{ar ? "رابط مخصص" : "Custom URL"}</option></select></label>
    <label className="space-y-1"><span className="text-xs font-semibold">{ar ? "صيغة العرض" : "Display format"}</span><select value={form.streamType} onChange={(e) => set("streamType", e.target.value)} className="w-full rounded-md border p-3"><option value="player">Web Player</option><option value="hls">HLS</option><option value="mjpeg">MJPEG</option><option value="rtsp">RTSP</option></select></label>
    {local && <label className="space-y-1 sm:col-span-2"><span className="text-xs font-semibold">{ar ? "عنوان الجهاز المحلي" : "Local device address"}</span><input value={form.deviceAddress} onChange={(e) => set("deviceAddress", e.target.value)} placeholder="192.168.1.20" className="w-full rounded-md border p-3" dir="ltr" /></label>}
    <label className="space-y-1 sm:col-span-2"><span className="text-xs font-semibold">{local ? (ar ? "مسار البث المحلي" : "Local stream path") : (ar ? "رابط المشاهدة أو المشاركة" : "Viewing or sharing link")}</span><input required value={form.streamUrl} onChange={(e) => set("streamUrl", e.target.value)} placeholder={local ? "http://192.168.1.20/stream.mjpg" : "https://..."} className="w-full rounded-md border p-3" dir="ltr" /></label>
    <p className="sm:col-span-2 text-xs text-muted-foreground">{local ? (ar ? "🏠 يعمل الرابط المحلي عند وجود جهاز العرض على شبكة الكاميرا نفسها." : "🏠 Local links work when the viewing device is on the same camera network.") : (ar ? "🔒 استخدم رابط المشاهدة السحابي الآمن، ولا تضع كلمة المرور داخل الرابط." : "🔒 Use a secure cloud viewing link and never include a password in it.")}</p>
  </div>;
}