import React from "react";
import { BookOpen, Camera, Info, Link2, Radar, Server, X } from "lucide-react";

const sections = (ar) => [
  { icon: Info, title: ar ? "قبل البدء: كيف يعمل الربط؟" : "Before you start: how it works", text: ar ? "يربط PowerCare كل كاميرا بمحطة محددة ويعرض بثها من خلال رابط آمن متوافق مع المتصفح. إذا كانت الكاميرا في الشبكة المحلية يمكنك اكتشافها عبر ONVIF. وإذا كانت في مدينة بعيدة، فيجب أن يوفّر جهاز NVR أو بوابة داخل الموقع رابط HLS أو Web Player عبر HTTPS. لا يتصل المتصفح مباشرة بعنوان الكاميرا المحلي أو ببث RTSP الخام." : "PowerCare links each camera to a station and displays its feed through a secure browser-compatible URL. On the same LAN, the camera can be discovered through ONVIF. For a camera in another city, an on-site NVR or gateway must provide an HTTPS HLS or Web Player URL. Browsers cannot connect directly to a private camera address or raw RTSP feed." },
  { icon: Link2, title: ar ? "خطوات ربط الكاميرا" : "Camera connection steps", text: ar ? "1) وصّل الكاميرا أو جهاز NVR بالشبكة. 2) اضغط «ربط كاميرا» وحدد الشركة المصنّعة. 3) ارفع صورة الباركود أو أدخل عنوان الجهاز يدويًا. 4) اختر المحطة واكتب اسم الكاميرا. 5) أدخل رابط HLS أو Web Player أو MJPEG المتوافق مع المتصفح. 6) اضغط «التالي» ثم «اختبار الاتصال». 7) عند نجاح الاختبار اضغط «حفظ وربط». إذا كان المصدر RTSP فقط، حوّله أولًا إلى HLS عبر NVR أو بوابة محلية." : "1) Connect the camera or NVR to the network. 2) Select Connect camera and choose the manufacturer. 3) Upload the barcode image or enter the device address manually. 4) Choose the station and name the camera. 5) Enter a browser-compatible HLS, Web Player, or MJPEG URL. 6) Select Next, then Test connection. 7) When the test succeeds, select Save & connect. If the source is RTSP-only, first convert it to HLS through an NVR or local gateway." },
  { icon: Camera, title: ar ? "ربط Hikvision" : "Connect Hikvision", text: ar ? "1) افتح إعدادات الكاميرا أو جهاز NVR وفعّل RTSP. 2) أنشئ مستخدمًا مخصصًا للعرض فقط. 3) حوّل RTSP إلى HLS عبر جهاز NVR أو بوابة آمنة. 4) اضغط «ربط كاميرا»، اختر Hikvision والمحطة ونوع HLS، ثم أدخل رابط HTTPS الناتج. 5) اختبر الاتصال واحفظ." : "1) Open the camera or NVR settings and enable RTSP. 2) Create a view-only user. 3) Convert RTSP to HLS through the NVR or a secure gateway. 4) Select Connect camera, Hikvision, the station, and HLS, then enter the resulting HTTPS URL. 5) Test and save." },
  { icon: Server, title: ar ? "ربط Dahua" : "Connect Dahua", text: ar ? "1) افتح إعدادات Dahua أو XVR/NVR وفعّل RTSP أو ONVIF. 2) أنشئ حساب مشاهدة محدود الصلاحيات. 3) استخدم بوابة لتحويل البث إلى HLS أو رابط Web Player آمن. 4) اختر Dahua والمحطة ونوع البث وأدخل الرابط. 5) اختبر الاتصال ثم احفظ." : "1) Open the Dahua or XVR/NVR settings and enable RTSP or ONVIF. 2) Create a restricted viewing account. 3) Use a gateway to provide HLS or a secure Web Player URL. 4) Select Dahua, station, and stream type, then enter the URL. 5) Test and save." },
  { icon: Radar, title: ar ? "ربط جهاز ONVIF" : "Connect an ONVIF device", text: ar ? "1) فعّل ONVIF من إعدادات الجهاز وأنشئ مستخدم ONVIF. 2) اجعل جهازك على الشبكة المحلية نفسها. 3) أدخل نطاقًا مثل 192.168.1.0/24 في أداة الاكتشاف واضغط فحص. 4) اختر الجهاز المكتشف واضغط إعداد. 5) أكمل بيانات المحطة والبث، ثم اختبر واحفظ. لا يعمل الاكتشاف المباشر عبر الإنترنت أو بين المدن." : "1) Enable ONVIF and create an ONVIF user. 2) Join the same LAN as the device. 3) Enter a range such as 192.168.1.0/24 in Discovery and scan. 4) Select the device and choose Set up. 5) Complete the station and stream details, then test and save. Direct discovery does not work over the internet or between cities." },
  { icon: BookOpen, title: ar ? "متطلبات العرض الآمن" : "Secure viewing requirements", text: ar ? "يجب أن يكون الرابط النهائي HTTPS ومتوافقًا مع المتصفح مثل HLS أو MJPEG أو Web Player. لا يعمل RTSP الخام داخل المتصفح؛ استخدم NVR أو بوابة RTSP-to-HLS، ولا تفتح الكاميرا مباشرة للإنترنت." : "The final URL must use HTTPS and a browser-compatible format such as HLS, MJPEG, or Web Player. Raw RTSP does not play in browsers; use an NVR or RTSP-to-HLS gateway and never expose the camera directly to the internet." },
];

export default function CameraGuideDialog({ ar, onClose }) {
  return <div className="fixed inset-0 z-[2000] grid place-items-center bg-foreground/40 p-4"><div className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-xl border border-border bg-card p-5 shadow-elevated" dir={ar ? "rtl" : "ltr"}><div className="flex items-center justify-between"><div><h2 className="font-heading text-xl font-semibold">{ar ? "دليل قسم الكاميرات" : "Camera Center guide"}</h2><p className="text-xs text-muted-foreground">{ar ? "ابدأ بفهم طريقة الربط، ثم اتبع خطوات جهازك" : "Understand the connection first, then follow your device steps"}</p></div><button onClick={onClose} aria-label={ar ? "إغلاق" : "Close"}><X className="h-5 w-5" /></button></div><div className="mt-5 space-y-3">{sections(ar).map(({ icon: Icon, title, text }) => <section key={title} className="rounded-lg border border-border bg-muted/30 p-4"><div className="flex items-start gap-3"><span className="rounded-md bg-accent/10 p-2 text-accent"><Icon className="h-4 w-4" /></span><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></div></section>)}</div><div className="mt-4 rounded-lg border border-accent/25 bg-accent/5 p-3 text-xs leading-5 text-muted-foreground">{ar ? "مهم: لا تضع اسم المستخدم أو كلمة المرور داخل رابط البث. استخدم بوابة آمنة داخل شبكة الشركة لإدارة بيانات الدخول وتحويل RTSP إلى HLS." : "Important: Never place usernames or passwords in stream URLs. Use a secure on-site gateway to manage credentials and convert RTSP to HLS."}</div><div className="mt-5 flex justify-end"><button onClick={onClose} className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground">{ar ? "فهمت" : "Got it"}</button></div></div></div>;
}