import React, { useState } from "react";
import { Download, Upload, X } from "lucide-react";
import { cameraTypes } from "@/lib/cameraProviders";

const parseLine = (line) => { const out = []; let value = "", quoted = false; for (let i = 0; i < line.length; i++) { const char = line[i]; if (char === '"' && line[i + 1] === '"') { value += '"'; i++; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { out.push(value.trim()); value = ""; } else value += char; } out.push(value.trim()); return out; };
export default function CameraCsvImport({ stations, ar, onImport, onClose }) {
  const [rows, setRows] = useState([]); const stationIds = new Set(stations.map((item) => item.id));
  const load = async (file) => { const lines = (await file.text()).replace(/^\uFEFF/, "").split(/\r?\n/).filter(Boolean); const headers = parseLine(lines.shift() || ""); setRows(lines.map((line, index) => { const values = parseLine(line); const row = Object.fromEntries(headers.map((key, i) => [key, values[i] || ""])); const errors = []; if (!row.name) errors.push("name"); if (!row.streamUrl) errors.push("streamUrl"); if (!stationIds.has(row.stationId)) errors.push("stationId"); if (!cameraTypes.includes(row.streamType)) errors.push("streamType"); return { ...row, status: row.status || "active", provider: row.provider || "generic", _line: index + 2, _errors: errors }; })); };
  const download = () => { const blob = new Blob(["name,streamUrl,streamType,stationId,status,provider\nCamera 1,https://example.com/live.m3u8,hls,STATION_ID,active,hikvision\n"], { type: "text/csv" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "powercare-camera-template.csv"; link.click(); URL.revokeObjectURL(link.href); };
  const valid = rows.filter((row) => !row._errors.length);
  return <div className="fixed inset-0 z-[2000] grid place-items-center bg-foreground/40 p-4"><div className="w-full max-w-3xl space-y-4 rounded-xl border bg-card p-5 shadow-elevated"><div className="flex justify-between"><h2 className="font-heading text-xl font-semibold">{ar ? "استيراد الكاميرات" : "Import cameras"}</h2><button onClick={onClose}><X className="h-5 w-5" /></button></div><div className="flex flex-wrap gap-2"><button onClick={download} className="inline-flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><Download className="h-4 w-4" />{ar ? "تنزيل القالب" : "Download template"}</button><label className="inline-flex cursor-pointer items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm text-primary-foreground"><Upload className="h-4 w-4" />{ar ? "اختيار CSV" : "Choose CSV"}<input type="file" accept=".csv,text/csv" className="hidden" onChange={(e) => e.target.files?.[0] && load(e.target.files[0])} /></label></div>{rows.length > 0 && <div className="max-h-80 overflow-auto rounded-md border"><table className="w-full text-xs"><thead><tr><th className="p-2">#</th><th className="p-2">name</th><th className="p-2">stationId</th><th className="p-2">type</th><th className="p-2">status</th></tr></thead><tbody>{rows.map((row) => <tr key={row._line} className={row._errors.length ? "bg-destructive/10" : ""}><td className="p-2">{row._line}</td><td className="p-2">{row.name || "—"}</td><td className="p-2">{row.stationId || "—"}</td><td className="p-2">{row.streamType || "—"}</td><td className="p-2">{row._errors.length ? `${ar ? "خطأ" : "Error"}: ${row._errors.join(", ")}` : (ar ? "جاهز" : "Ready")}</td></tr>)}</tbody></table></div>}<div className="flex justify-end gap-2"><button onClick={onClose} className="rounded-md border px-4 py-2 text-sm">{ar ? "إلغاء" : "Cancel"}</button><button disabled={!valid.length} onClick={() => onImport(valid.map(({ _line, _errors, ...row }) => row))} className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-40">{ar ? `استيراد ${valid.length}` : `Import ${valid.length}`}</button></div></div></div>;
}