import React, { useEffect, useRef, useState } from "react";
import { ChevronLeft, ChevronRight, Loader2, X } from "lucide-react";
import * as pdfjsLib from "pdfjs-dist";
import { Image } from "@/components/ui/image";
import { STAMP_CANVAS_HEIGHT, STAMP_CANVAS_WIDTH, STAMP_WIDTH_PERCENT } from "@/lib/signatureStampGeometry";

pdfjsLib.GlobalWorkerOptions.workerSrc = `https://unpkg.com/pdfjs-dist@${pdfjsLib.version}/build/pdf.worker.min.mjs`;

export default function InlinePdfPlacement({ url, fields, onFieldsChange, textValues, signaturePreview, ar, onPageChange }) {
  const canvasRef = useRef(null); const wrapRef = useRef(null); const stageRef = useRef(null); const renderTaskRef = useRef(null);
  const [pdf, setPdf] = useState(null); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [size, setSize] = useState({ width: 800, height: 600 }); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; pdfjsLib.getDocument({ url, cMapUrl: `https://unpkg.com/pdfjs-dist@${pdfjsLib.version}/cmaps/`, cMapPacked: true, standardFontDataUrl: `https://unpkg.com/pdfjs-dist@${pdfjsLib.version}/standard_fonts/`, useSystemFonts: false, disableFontFace: true }).promise.then((doc) => { if (active) { setPdf(doc); setPages(doc.numPages); } }); return () => { active = false; renderTaskRef.current?.cancel(); }; }, [url]);
  useEffect(() => { const stage = stageRef.current; if (!stage) return; const update = () => setSize({ width: Math.max(280, stage.clientWidth - 32), height: Math.max(280, stage.clientHeight - 80) }); update(); const observer = new ResizeObserver(update); observer.observe(stage); return () => observer.disconnect(); }, []);
  useEffect(() => { if (!pdf || !canvasRef.current) return; let cancelled = false; (async () => { const previous = renderTaskRef.current; if (previous) { previous.cancel(); try { await previous.promise; } catch {} } if (cancelled) return; setLoading(true); const pdfPage = await pdf.getPage(page); if (cancelled) return; const base = pdfPage.getViewport({ scale: 1 }); const cssScale = Math.min(size.width / base.width, size.height / base.height); const displayWidth = base.width * cssScale; const displayHeight = base.height * cssScale; const viewport = pdfPage.getViewport({ scale: cssScale * (window.devicePixelRatio || 1) }); const canvas = canvasRef.current; canvas.width = viewport.width; canvas.height = viewport.height; canvas.style.width = `${displayWidth}px`; canvas.style.height = `${displayHeight}px`; const task = pdfPage.render({ canvasContext: canvas.getContext("2d"), viewport }); renderTaskRef.current = task; try { await task.promise; if (!cancelled) setLoading(false); } catch (error) { if (error?.name !== "RenderingCancelledException") throw error; } finally { if (renderTaskRef.current === task) renderTaskRef.current = null; } })(); return () => { cancelled = true; renderTaskRef.current?.cancel(); }; }, [pdf, page, size]);
  useEffect(() => { onPageChange?.(page); }, [page, onPageChange]);
  const drag = (event, field) => { event.preventDefault(); const rect = wrapRef.current.getBoundingClientRect(); const startX = event.clientX; const startY = event.clientY; const originX = field.x; const originY = field.y; const move = (e) => onFieldsChange(fields.map((item) => item.id === field.id ? { ...item, x: Math.min(96, Math.max(4, originX + ((e.clientX - startX) / rect.width) * 100)), y: Math.min(96, Math.max(4, originY + ((e.clientY - startY) / rect.height) * 100)) } : item)); const stop = () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", stop); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", stop); };
  const visible = fields.filter((field) => field.page === page);
  return <div ref={stageRef} className="document-first-page-preview relative flex h-[70vh] min-h-[420px] w-full min-w-0 items-center justify-center overflow-hidden bg-secondary/45 p-4 pb-16"><div ref={wrapRef} className="relative h-fit max-w-full bg-white shadow-lg"><canvas ref={canvasRef} className="document-first-page-canvas block max-w-full" />{visible.map((field) => { const fieldWidth = (field.type === "signature" ? STAMP_WIDTH_PERCENT : 26) * ((field.scale || 100) / 100); return <div key={field.id} onPointerDown={(event) => drag(event, field)} className={`absolute flex cursor-move touch-none items-center justify-center overflow-visible rounded-md border-2 border-dashed ${field.type === "signature" ? "border-accent bg-accent/10" : "border-blue-600 bg-blue-50/90 px-2 text-xs font-bold text-blue-700"}`} style={{ left: `${field.x}%`, top: `${field.y}%`, width: `${fieldWidth}%`, minHeight: field.type === "text" ? 32 : undefined, aspectRatio: field.type === "signature" ? `${STAMP_CANVAS_WIDTH} / ${STAMP_CANVAS_HEIGHT}` : undefined, transform: "translate(-50%, -50%)" }}>{field.type === "signature" && signaturePreview ? <Image src={signaturePreview} alt={ar ? "التوقيع" : "Signature"} fittingType="fit" className="h-full w-full overflow-hidden rounded" /> : field.type === "text" ? (textValues[field.id] || field.label) : (ar ? "التوقيع" : "Signature")}<button type="button" aria-label={ar ? "حذف الحقل" : "Delete field"} onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); onFieldsChange(fields.filter((item) => item.id !== field.id)); }} className="absolute -end-2 -top-2 flex h-6 w-6 items-center justify-center rounded-full border-2 border-white bg-destructive text-destructive-foreground shadow-md"><X className="h-3.5 w-3.5" /></button></div>; })}</div>{loading && <div className="absolute inset-0 flex items-center justify-center bg-card/65"><Loader2 className="h-6 w-6 animate-spin text-accent" /></div>}<div className="absolute bottom-3 left-1/2 flex -translate-x-1/2 items-center gap-2 rounded-full border border-border bg-card px-3 py-2 shadow-lg"><button type="button" disabled={page === 1} onClick={() => setPage((value) => Math.max(1, value - 1))} className="rounded-full border p-1.5 disabled:opacity-35">{ar ? <ChevronRight className="h-4 w-4" /> : <ChevronLeft className="h-4 w-4" />}</button><span className="min-w-14 text-center text-xs font-bold">{page} / {pages}</span><button type="button" disabled={page === pages} onClick={() => setPage((value) => Math.min(pages, value + 1))} className="rounded-full border p-1.5 disabled:opacity-35">{ar ? <ChevronLeft className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}</button></div></div>;
}