import React, { useMemo, useRef, useState } from "react";
import { FileText, Loader2, Send, Undo2, Upload, Users } from "lucide-react";
import MultiSignPlacementModal from "@/components/files/MultiSignPlacementModal";
import GroupSignUploadZone from "@/components/files/GroupSignUploadZone";
import GroupSignerList from "@/components/files/GroupSignerList";
import GroupSignSuccess from "@/components/files/GroupSignSuccess";
import SignatureThemePicker from "@/components/files/SignatureThemePicker";
import { base44 } from "@/api/base44Client";
import { generateVerificationId } from "@/lib/verificationBadge";
import { appParams } from "@/lib/app-params";
import { getCompanyToken } from "@/lib/store";

const EMPTY_SIGNER = { name: "", email: "", employeeId: null, role: "", stationId: null, signatureUrl: "", external: false };
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function uploadWithRetry(file) { for (let attempt = 0; attempt < 6; attempt += 1) { try { return await base44.integrations.Core.UploadFile({ file }); } catch (error) { const limited = error?.response?.status === 429 || error?.status === 429 || String(error?.message || "").includes("429"); if (!limited || attempt === 5) throw error; await wait(Math.min(30000, 1000 * (2 ** attempt))); } } }
function signingBaseUrl() { try { if (appParams.appBaseUrl) return String(appParams.appBaseUrl).replace(/\/+$/, ""); } catch {} return window.location.origin; }

export default function MultiSignCard({ currentUser, companyId, employees, ar, onCreated }) {
  const [doc, setDoc] = useState(null); const [uploading, setUploading] = useState(false); const [sending, setSending] = useState(false);
  const [signers, setSigners] = useState([{ ...EMPTY_SIGNER }]); const [activeSigner, setActiveSigner] = useState(0); const [spots, setSpots] = useState({});
  const [stampTheme, setStampTheme] = useState("heritage"); const [result, setResult] = useState(null); const [error, setError] = useState(""); const fileRef = useRef(null);
  const validSigners = useMemo(() => signers.filter((signer) => signer.name.trim() && /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(signer.email.trim())), [signers]);
  const unique = validSigners.length === signers.length && new Set(signers.map((signer) => signer.email.trim().toLowerCase())).size === signers.length;
  const allPlaced = unique && signers.every((_, index) => (spots[index] || []).some((field) => field.type === "signature"));

  const upload = async (event) => { const file = event.target.files?.[0]; if (!file || uploading) return; if (file.type !== "application/pdf" && !file.name.toLowerCase().endsWith(".pdf")) { setError(ar ? "اختر ملف PDF صالحًا." : "Choose a valid PDF file."); return; } setUploading(true); setError(""); try { const { file_url } = await uploadWithRetry(file); setDoc({ name: file.name, url: file_url }); setSpots({}); } catch { setError(ar ? "تعذّر رفع المستند. حاول مرة أخرى." : "The document couldn't be uploaded. Please try again."); } finally { setUploading(false); event.target.value = ""; } };
  const send = async () => { if (!unique) { setError(ar ? "أدخل اسمًا وبريدًا صالحًا وفريدًا لكل موقّع." : "Enter a valid, unique name and email for every signer."); return; } if (!allPlaced) { setError(ar ? "ضع حقل توقيع واحدًا على الأقل لكل موقّع." : "Place at least one signature field for every signer."); return; } setSending(true); setError(""); try { const response = await base44.functions.invoke("multiSign", { action: "create", companyId, sessionToken: getCompanyToken(companyId), creatorId: currentUser.id, creatorName: currentUser.name, creatorEmail: currentUser.email || "", fileName: doc.name, docUrl: doc.url, verificationId: generateVerificationId(), signatureTheme: stampTheme, signers: validSigners.map((signer, index) => ({ ...signer, spots: spots[index] })), appUrl: signingBaseUrl(), lang: ar ? "ar" : "en" }); setResult(response.data); onCreated?.(); } catch (err) { setError((ar ? "تعذّر إنشاء الطلب — " : "Couldn't create the request — ") + (err?.response?.data?.error || err.message)); } finally { setSending(false); } };
  const cancelDocument = () => { setDoc(null); setActiveSigner(0); setSpots({}); setError(""); if (fileRef.current) fileRef.current.value = ""; };
  const reset = () => { setDoc(null); setSigners([{ ...EMPTY_SIGNER }]); setActiveSigner(0); setSpots({}); setStampTheme("heritage"); setResult(null); setError(""); };
  if (result) return <GroupSignSuccess ar={ar} result={result} onReset={reset} />;

  return <div className="signature-workspace w-full min-w-0 max-w-full" dir={ar ? "rtl" : "ltr"}><div className="signature-workspace-grid grid w-full min-w-0 grid-cols-1 items-start gap-5 lg:grid-cols-[minmax(0,1fr)_320px] xl:grid-cols-[minmax(0,1fr)_340px]">
    <section className="order-2 min-w-0 overflow-hidden rounded-2xl border border-accent/25 bg-card shadow-soft lg:order-1"><div className="self-sign-document-header flex items-start justify-between gap-4 border-b border-border p-5"><div className="flex gap-3"><span className="rounded-xl bg-accent/10 p-2.5"><Users className="h-5 w-5 text-accent" /></span><div><h2 className="font-heading text-xl font-semibold">{ar ? "المستند الجماعي" : "Group document"}</h2><p className="mt-1 text-xs text-muted-foreground">{ar ? "اسحب حقول كل موقّع إلى مكانها" : "Drag each signer's fields into place"}</p></div></div>{doc && <div className="flex items-center gap-2"><button type="button" onClick={() => fileRef.current?.click()} className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-2 text-xs font-bold"><Upload className="h-3.5 w-3.5" />{ar ? "استبدال" : "Replace"}</button><button type="button" onClick={cancelDocument} className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-2 text-xs font-bold text-muted-foreground hover:border-destructive/40 hover:text-destructive"><Undo2 className="h-3.5 w-3.5" />{ar ? "تراجع" : "Cancel"}</button></div>}</div>
      {!doc ? <GroupSignUploadZone ar={ar} uploading={uploading} inputRef={fileRef} onUpload={upload} /> : validSigners.length ? <MultiSignPlacementModal embedded docUrl={doc.url} signers={validSigners} initialSpots={spots} activeSigner={activeSigner} onActiveSignerChange={setActiveSigner} ar={ar} onChange={setSpots} /> : <div className="flex min-h-[460px] flex-col items-center justify-center p-8 text-center"><FileText className="mb-3 h-8 w-8 text-accent" /><p className="text-sm font-bold">{ar ? "أضف بيانات أول موقّع لعرض المستند" : "Add the first signer to open the document"}</p></div>} {doc && <input ref={fileRef} type="file" accept="application/pdf,.pdf" className="hidden" onChange={upload} />}
    </section>
    <aside className="signature-fit-panel order-1 w-full rounded-2xl border border-accent/25 bg-card shadow-soft lg:order-2 lg:sticky lg:top-5"><div className="border-b border-border bg-gradient-to-l from-secondary/80 to-card p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-accent">PowerCare Identity</p><h2 className="mt-0.5 font-heading text-xl font-semibold">{ar ? "إرسال التواقيع" : "Send signatures"}</h2><p className="mt-0.5 text-[11px] leading-4 text-muted-foreground">{ar ? "أضف الموقّعين واختر بصمة الختم ثم وزّع الحقول مباشرة." : "Add signers, choose the stamp fingerprint, then place fields directly."}</p></div><div className="space-y-4 p-4"><GroupSignerList ar={ar} currentUser={currentUser} employees={employees} signers={signers} setSigners={setSigners} activeSigner={activeSigner} setActiveSigner={setActiveSigner} /><SignatureThemePicker value={stampTheme} onChange={setStampTheme} ar={ar} /><button type="button" onClick={send} disabled={sending || !doc || !allPlaced} className="flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-5 py-3.5 text-sm font-bold text-primary-foreground shadow-md disabled:opacity-40">{sending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}{sending ? (ar ? "جارٍ الإرسال…" : "Sending…") : (ar ? "إرسال طلبات التوقيع" : "Send signature requests")}</button>{error && <p className="text-xs text-destructive">{error}</p>}</div></aside>
  </div></div>;
}