import React, { useEffect, useState } from "react";
import { Check, Keyboard, PenLine, Trash2, Upload } from "lucide-react";
import { Image } from "@/components/ui/image";
import { base44 } from "@/api/base44Client";
import { updateEmployeeProfile } from "@/lib/store";
import { makeSignatureStamp } from "@/lib/multiSignStamp";
import SignaturePad from "./SignaturePad";
import TypedSignature from "./TypedSignature";
import UploadedSignature from "./UploadedSignature";
import SelfSignDocumentCard from "./SelfSignDocumentCard";
import SignatureSecurityBar from "./SignatureSecurityBar";


async function generateSignatureId(userId) { const data = new TextEncoder().encode(`${userId}::${Date.now()}::${Math.random()}`); const hash = await crypto.subtle.digest("SHA-256", data); const hex = [...new Uint8Array(hash)].map((b) => b.toString(16).padStart(2, "0")).join("").toUpperCase(); return `PWC-${hex.slice(0, 4)}-${hex.slice(4, 8)}-${hex.slice(8, 12)}`; }
function dataUrlToBlob(dataUrl) { const [header, encoded] = dataUrl.split(","); const mime = header.match(/data:(.*?);base64/)?.[1] || "image/png"; const binary = atob(encoded); const bytes = new Uint8Array(binary.length); for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i); return new Blob([bytes], { type: mime }); }

export default function MySignatureCard({ companyId, currentUser, ar, onSaved }) {
  const [localSignature, setLocalSignature] = useState(null); const signatureUrl = localSignature?.signatureUrl ?? currentUser?.profile?.signatureUrl ?? ""; const signatureRawUrl = localSignature?.signatureRawUrl ?? currentUser?.profile?.signatureRawUrl ?? ""; const signatureVariant = localSignature?.signatureVariant ?? currentUser?.profile?.signatureVariant ?? "unique"; const signatureTheme = "neo"; const signatureId = localSignature?.signatureId ?? currentUser?.profile?.signatureId ?? "";
  const [editing, setEditing] = useState(!signatureUrl); const [mode, setMode] = useState("type"); const stampTheme = "neo"; const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [refreshedPreview, setRefreshedPreview] = useState(""); const [security, setSecurity] = useState({ signatureId, timestamp: currentUser?.profile?.signatureUpdatedAt || "", verified: false });

  useEffect(() => { let active = true; setRefreshedPreview(""); if (!signatureRawUrl || !signatureId || signatureVariant === "composed") return () => { active = false; }; const signerName = currentUser?.profile?.signatureName || currentUser?.name || ""; makeSignatureStamp(signatureRawUrl, signerName, signatureId, signatureVariant, signatureTheme).then((preview) => { if (active) setRefreshedPreview(preview); }).catch(() => { if (active) setRefreshedPreview(""); }); return () => { active = false; }; }, [signatureRawUrl, signatureId, signatureVariant, signatureTheme, currentUser?.profile?.signatureName, currentUser?.name]);

  const saveSignature = async (dataUrl, typedName, signatureStyle = "composed", selectedTheme = stampTheme) => { setSaving(true); setError(""); try { const sigId = await generateSignatureId(currentUser.id); const signerName = typeof typedName === "string" ? typedName : currentUser.name; const finalDataUrl = signatureStyle !== "composed" ? await makeSignatureStamp(dataUrl, signerName, sigId, signatureStyle, selectedTheme) : dataUrl; const finalFile = new File([dataUrlToBlob(finalDataUrl)], "signature.png", { type: "image/png" }); const rawFile = signatureStyle !== "composed" ? new File([dataUrlToBlob(dataUrl)], "signature-original.png", { type: "image/png" }) : null; const [finalUpload, rawUpload] = await Promise.all([base44.integrations.Core.UploadFile({ file: finalFile }), rawFile ? base44.integrations.Core.UploadFile({ file: rawFile }) : Promise.resolve(null)]); const timestamp = new Date().toISOString(); const savedProfile = { signatureUrl: finalUpload.file_url, signatureRawUrl: rawUpload?.file_url || "", signatureVariant: signatureStyle, signatureTheme: selectedTheme, signatureId: sigId, signatureName: signerName, signatureUpdatedAt: timestamp }; updateEmployeeProfile(companyId, currentUser.id, savedProfile); setLocalSignature(savedProfile); setSecurity({ signatureId: sigId, timestamp, verified: false }); onSaved?.(savedProfile); setEditing(false); } catch { setError(ar ? "تعذّر حفظ التوقيع؛ حاول مرة أخرى." : "Couldn't save the signature; try again."); } finally { setSaving(false); } };
  const remove = () => { const cleared = { signatureUrl: "", signatureRawUrl: "", signatureVariant: "", signatureTheme: "", signatureId: "" }; updateEmployeeProfile(companyId, currentUser.id, cleared); setLocalSignature(cleared); setSecurity({ signatureId: "", timestamp: "", verified: false }); onSaved?.(cleared); setEditing(true); };
  const tabs = [{ id: "type", icon: Keyboard, label: ar ? "كتابة الاسم" : "Type" }, { id: "draw", icon: PenLine, label: ar ? "رسم التوقيع" : "Draw" }, { id: "upload", icon: Upload, label: ar ? "رفع توقيع" : "Upload" }];

  return <div className="signature-workspace w-full min-w-0 max-w-full space-y-5" dir={ar ? "rtl" : "ltr"}>
    <div className="signature-workspace-grid grid w-full min-w-0 max-w-full grid-cols-1 items-start gap-5 lg:grid-cols-[minmax(0,1fr)_320px] xl:grid-cols-[minmax(0,1fr)_340px]">
      <div className="order-2 min-w-0 max-w-full lg:order-1"><SelfSignDocumentCard signatureUrl={signatureUrl} signatureRawUrl={signatureRawUrl} signatureVariant={signatureVariant} signatureTheme={signatureTheme} currentUser={currentUser} companyId={companyId} ar={ar} onVerified={setSecurity} /></div>
      <aside className="signature-fit-panel order-1 w-full min-w-0 max-w-full rounded-2xl border border-accent/25 bg-card shadow-soft lg:order-2 lg:sticky lg:top-5 lg:self-start"><div className="border-b border-border bg-gradient-to-l from-secondary/80 to-card p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-accent">NiroVera Identity</p><h2 className="mt-0.5 font-heading text-xl font-semibold">{ar ? "إنشاء التوقيع" : "Create signature"}</h2><p className="mt-0.5 text-[11px] leading-4 text-muted-foreground">{ar ? "أنشئ توقيعك الشخصي المحمي لاستخدامه على المستند." : "Create your protected personal signature for this document."}</p></div>
        <div className="p-4">{!editing && signatureUrl ? <div className="space-y-3"><div className="flex justify-center rounded-xl border border-accent/25 bg-white p-3"><Image src={refreshedPreview || signatureUrl} alt={ar ? "توقيعك" : "Your signature"} fittingType="fit" className="h-20 w-full max-w-[240px]" /></div><div className="flex gap-2"><button type="button" onClick={() => setEditing(true)} className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-primary px-4 py-3 text-sm font-bold text-primary-foreground"><PenLine className="h-4 w-4" />{ar ? "توقيع جديد" : "New signature"}</button><button type="button" onClick={remove} className="rounded-lg border border-destructive/40 px-4 text-destructive"><Trash2 className="h-4 w-4" /></button></div><p className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-medium text-emerald-700"><Check className="h-4 w-4" />{ar ? "التوقيع محفوظ وجاهز للاستخدام" : "Signature saved and ready"}</p></div> : <div className="space-y-2.5"><div className="grid grid-cols-3 gap-1 rounded-lg bg-secondary p-1">{tabs.map(({ id, icon: Icon, label }) => <button key={id} type="button" onClick={() => setMode(id)} className={`flex min-h-9 items-center justify-center gap-1.5 rounded-md px-2 text-[11px] font-bold ${mode === id ? "bg-card text-foreground shadow-sm ring-1 ring-accent/30" : "text-muted-foreground"}`}><Icon className="h-3.5 w-3.5" />{label}</button>)}</div>{mode === "draw" && <SignaturePad ar={ar} signerName={currentUser?.name || ""} stampTheme={stampTheme} onSave={saveSignature} saving={saving} />}{mode === "type" && <TypedSignature ar={ar} defaultName={currentUser?.name || ""} stampTheme={stampTheme} onSave={saveSignature} saving={saving} />}{mode === "upload" && <UploadedSignature ar={ar} signerName={currentUser?.name || ""} stampTheme={stampTheme} onSave={saveSignature} saving={saving} />}{error && <p className="text-xs text-destructive">{error}</p>}</div>}</div>
      </aside>
    </div>
    <SignatureSecurityBar signatureId={security.signatureId || signatureId} timestamp={security.timestamp || currentUser?.profile?.signatureUpdatedAt} verified={security.verified} ar={ar} />
  </div>;
}