import React from "react";
import { AlertTriangle, CheckCircle2, Download, FileCheck2, ShieldCheck } from "lucide-react";

export default function NiroReviewResult({ result, ar }) {
  const report = result?.report;
  if (!report) return null;
  return <div className="space-y-5 rounded-3xl border border-accent/20 bg-card p-6 shadow-soft">
    <div className="flex items-start gap-3"><span className={`flex h-11 w-11 items-center justify-center rounded-2xl ${result.sealed ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{result.sealed ? <ShieldCheck className="h-6 w-6" /> : <AlertTriangle className="h-6 w-6" />}</span><div><p className="text-[10px] font-bold uppercase tracking-widest text-accent">Niro AI Review</p><h3 className="mt-1 font-heading text-2xl font-semibold">{report.documentType}</h3><p className="mt-1 text-sm text-muted-foreground">{report.summary}</p></div></div>
    <div className="space-y-2">{(report.requiredChecks || []).map((check, index) => <div key={`${check.label}-${index}`} className="flex items-start gap-3 rounded-xl border border-border p-3">{check.status === "complete" ? <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" /> : <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />}<div><p className="text-sm font-semibold">{check.label}</p><p className="mt-0.5 text-xs text-muted-foreground">{check.evidence}</p></div></div>)}</div>
    {(report.missingItems || []).length > 0 && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-start"><p className="text-sm font-bold text-amber-800">{ar ? "بيانات يجب استكمالها" : "Items requiring completion"}</p><ul className="mt-2 list-disc space-y-1 ps-5 text-xs text-amber-800">{report.missingItems.map((item) => <li key={item}>{item}</li>)}</ul></div>}
    {result.sealed && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><p className="flex items-center gap-2 text-sm font-bold text-emerald-800"><FileCheck2 className="h-4 w-4" />{ar ? "تم التحقق ووضع ختم الشركة الرقمي" : "Verified and digitally company-sealed"}</p><p dir="ltr" className="mt-2 font-mono text-xs text-emerald-800">{result.verificationId}</p><a href={result.sealedUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-emerald-700 px-5 text-sm font-bold text-white"><Download className="h-4 w-4" />{ar ? "تنزيل الوثيقة المختومة" : "Download sealed document"}</a></div>}
    <details className="rounded-xl border border-border bg-muted/40 p-4"><summary className="cursor-pointer text-xs font-bold">{ar ? "سجل التدقيق" : "Audit trail"}</summary><div className="mt-3 space-y-2">{(result.auditTrail || []).map((event, index) => <p key={`${event.at}-${index}`} className="text-xs text-muted-foreground">{event.type} · {new Date(event.at).toLocaleString(ar ? "ar-SA" : "en-GB")}</p>)}</div></details>
  </div>;
}