import React from "react";
import { CheckCircle2, Clock3, PenLine, Trash2, Type } from "lucide-react";

export default function PlacementStudioSidebar({ ar, fieldType, setFieldType, signers, spots, active, setActive, colors, selected, setSelectedId, updateField, removeField, scaleBounds }) {
  const activeFields = spots[active] || [];
  return <aside className="space-y-5 p-4 sm:p-5">
    <section><p className="mb-2 text-[10px] font-bold uppercase tracking-widest text-accent">{ar ? "نوع الحقل" : "Field type"}</p><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => setFieldType("signature")} className={`flex min-h-11 items-center justify-center gap-2 rounded-lg border text-xs font-bold ${fieldType === "signature" ? "border-accent bg-accent text-accent-foreground" : "border-border bg-card"}`}><PenLine className="h-4 w-4" />{ar ? "توقيع" : "Signature"}</button><button type="button" onClick={() => setFieldType("text")} className={`flex min-h-11 items-center justify-center gap-2 rounded-lg border text-xs font-bold ${fieldType === "text" ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card"}`}><Type className="h-4 w-4" />{ar ? "نص" : "Text"}</button></div></section>
    <section><p className="mb-2 text-[10px] font-bold uppercase tracking-widest text-muted-foreground">{ar ? "الموقّعون" : "Signers"}</p><div className="space-y-2">{signers.map((signer, index) => { const count = (spots[index] || []).filter((field) => field.type === "signature").length; return <button key={signer.email || index} type="button" onClick={() => { setActive(index); setSelectedId(null); }} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-start ${active === index ? "border-accent bg-accent/10" : "border-border bg-card"}`}><span className="flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold text-white" style={{ backgroundColor: colors[index % colors.length] }}>{index + 1}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-bold">{signer.name}</span><span className="flex items-center gap-1 text-[10px] text-muted-foreground">{count ? <CheckCircle2 className="h-3 w-3 text-emerald-600" /> : <Clock3 className="h-3 w-3" />}{count} {ar ? "حقل توقيع" : "signature fields"}</span></span></button>; })}</div></section>
    <section><p className="mb-2 text-[10px] font-bold uppercase tracking-widest text-muted-foreground">{ar ? "حقول الموقّع" : "Signer fields"}</p><div className="space-y-2">{activeFields.length ? activeFields.map((field, index) => <button key={field.id} type="button" onClick={() => setSelectedId(field.id)} className={`flex w-full items-center gap-2 rounded-lg border p-2.5 text-start ${selected?.id === field.id ? "border-accent bg-accent/10" : "border-border bg-card"}`}><span className="flex h-6 w-6 items-center justify-center rounded bg-muted text-[10px] font-bold">{index + 1}</span><span className="min-w-0 flex-1 truncate text-[11px]">{field.type === "text" ? (field.label || (ar ? "حقل نص" : "Text field")) : (ar ? "حقل توقيع" : "Signature field")} · {ar ? "صفحة" : "Page"} {field.page}</span><span onClick={(event) => { event.stopPropagation(); removeField(active, field.id); }} className="rounded p-1 text-muted-foreground hover:text-destructive"><Trash2 className="h-3.5 w-3.5" /></span></button>) : <p className="rounded-lg border border-dashed border-border p-4 text-center text-xs text-muted-foreground">{ar ? "انقر على صفحة المستند لإضافة حقل." : "Click the document page to add a field."}</p>}</div></section>
    {selected && <section className="space-y-3 rounded-xl border border-accent/25 bg-accent/5 p-3"><p className="text-xs font-bold">{ar ? "خصائص الحقل" : "Field properties"}</p>{selected.type === "text" && <input value={selected.label || ""} onChange={(event) => updateField(active, selected.id, { label: event.target.value.slice(0, 60) })} placeholder={ar ? "عنوان الحقل" : "Field label"} className="w-full rounded-md border border-input bg-card px-2.5 py-2 text-xs" />}<div className="flex justify-between text-[11px] text-muted-foreground"><span>{ar ? "الحجم" : "Size"}</span><span>{selected.scale || 100}%</span></div><input type="range" min={scaleBounds(selected)[0]} max={scaleBounds(selected)[1]} step="5" value={selected.scale || 100} onChange={(event) => updateField(active, selected.id, { scale: Number(event.target.value) })} className="w-full accent-current" /></section>}
  </aside>;
}