import React from "react";
import { CheckCircle2, Clock3, PenLine, Trash2 } from "lucide-react";

export default function SigningWorkspaceSidebar({ signers, spots, active, setActive, colors, ar, removeField }) {
  const fields = signers.flatMap((signer, signerIndex) => (spots[signerIndex] || []).map((field) => ({ signer, signerIndex, field })));
  return (
    <aside className="space-y-5 bg-[var(--signing-panel)] p-4 lg:p-5">
      <section><h3 className="mb-3 flex items-center gap-2 text-sm font-bold"><PenLine className="h-4 w-4 text-[var(--signing-accent)]" />{ar ? "الموقّعون" : "Signers"}</h3><div className="space-y-2">{signers.map((signer, index) => { const signed = signer.status === "signed"; return <button key={signer.email || index} type="button" onClick={() => setActive(index)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-start ${active === index ? "border-[var(--signing-accent)] bg-[var(--signing-accent-soft)]" : "border-border bg-card"}`}><span className="h-3 w-3 shrink-0 rounded-full" style={{ backgroundColor: colors[index % colors.length] }} /><span className="min-w-0 flex-1"><span className="block truncate text-xs font-bold">{signer.name || `${ar ? "الموقّع" : "Signer"} ${index + 1}`}</span><span className="mt-0.5 flex items-center gap-1 text-[10px] text-muted-foreground">{signed ? <CheckCircle2 className="h-3 w-3" /> : <Clock3 className="h-3 w-3" />}{signed ? (ar ? "وقّع" : "Signed") : (ar ? "في انتظار" : "Waiting")} · {(spots[index] || []).length}</span></span></button>; })}</div></section>
      <section><h3 className="mb-3 text-sm font-bold">{ar ? "الحقول المضافة" : "Added fields"}</h3><div className="max-h-64 space-y-2 overflow-auto">{fields.length ? fields.map(({ signer, signerIndex, field }, index) => <div key={field.id} className="group flex items-center gap-2 rounded-lg border border-border bg-card p-2.5"><span className="flex h-6 w-6 items-center justify-center rounded-md text-[10px] font-bold text-white" style={{ backgroundColor: colors[signerIndex % colors.length] }}>{index + 1}</span><span className="min-w-0 flex-1 truncate text-[11px]">{signer.name || (ar ? "موقّع" : "Signer")} · {ar ? "صفحة" : "Page"} {field.page}</span><button type="button" onClick={() => removeField(signerIndex, field.id)} className="rounded-md p-1 text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 className="h-3.5 w-3.5" /></button></div>) : <p className="rounded-lg border border-dashed border-border p-4 text-center text-xs text-muted-foreground">{ar ? "انقر على المستند لإضافة حقل." : "Click the document to add a field."}</p>}</div></section>
    </aside>
  );
}