import React, { useState } from "react";
import { DragDropContext, Droppable, Draggable } from "@hello-pangea/dnd";
import { GripVertical, Plus, Trash2 } from "lucide-react";
import { updateCompany } from "@/lib/store";
import { orderedJobGrades } from "@/lib/jobGrades";

export default function JobGradeManager({ companyId, data, ar }) {
  const grades = orderedJobGrades(data); const [draft, setDraft] = useState({ gradeNumber: "", title: "" });
  const mutate = (fn) => updateCompany(companyId, (company) => { company.jobGrades = company.jobGrades || []; fn(company.jobGrades); });
  const add = () => { if (!draft.gradeNumber.trim() || !draft.title.trim()) return; mutate((list) => list.push({ id: `grade_${Date.now().toString(36)}`, gradeNumber: draft.gradeNumber.trim(), title: draft.title.trim(), order: list.length })); setDraft({ gradeNumber: "", title: "" }); };
  const edit = (id, field, value) => mutate((list) => { const item = list.find((grade) => grade.id === id); if (item) item[field] = value; });
  const remove = (id) => updateCompany(companyId, (company) => { company.jobGrades = (company.jobGrades || []).filter((grade) => grade.id !== id); company.jobGrades.forEach((grade, order) => { grade.order = order; }); (company.employees || []).forEach((employee) => { if (employee.profile?.gradeId === id) employee.profile.gradeId = null; }); });
  const reorder = ({ source, destination }) => { if (!destination) return; mutate((list) => { list.sort((a, b) => a.order - b.order); const [item] = list.splice(source.index, 1); list.splice(destination.index, 0, item); list.forEach((grade, order) => { grade.order = order; }); }); };
  return <section className="space-y-4 rounded-xl border border-border bg-card p-4"><div><h3 className="font-heading text-lg font-semibold">{ar ? "إدارة المستويات الوظيفية" : "Manage Job Grades"}</h3><p className="text-xs text-muted-foreground">{ar ? "طبقة تعريفية مستقلة عن الأدوار والصلاحيات." : "A display layer independent from roles and permissions."}</p></div><div className="grid gap-2 sm:grid-cols-[1fr_2fr_auto]"><input value={draft.gradeNumber} onChange={(e) => setDraft({ ...draft, gradeNumber: e.target.value })} placeholder={ar ? "رقم المستوى مثل G1" : "Grade number, e.g. G1"} className="rounded-md border border-input px-3 py-2 text-sm"/><input value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} placeholder={ar ? "المسمى الوظيفي" : "Grade title"} className="rounded-md border border-input px-3 py-2 text-sm"/><button onClick={add} className="flex items-center justify-center gap-1 rounded-md bg-foreground px-3 py-2 text-sm text-background"><Plus className="h-4 w-4"/>{ar ? "إضافة" : "Add"}</button></div><DragDropContext onDragEnd={reorder}><Droppable droppableId="job-grades">{(provided) => <div ref={provided.innerRef} {...provided.droppableProps} className="space-y-2">{grades.map((grade, index) => <Draggable key={grade.id} draggableId={grade.id} index={index}>{(item) => <div ref={item.innerRef} {...item.draggableProps} className="grid items-center gap-2 rounded-lg border border-border bg-background p-2 sm:grid-cols-[auto_1fr_2fr_auto]"><button {...item.dragHandleProps} className="p-2 text-muted-foreground"><GripVertical className="h-4 w-4"/></button><input value={grade.gradeNumber} onChange={(e) => edit(grade.id, "gradeNumber", e.target.value)} className="rounded-md border border-input px-2 py-1.5 text-sm"/><input value={grade.title} onChange={(e) => edit(grade.id, "title", e.target.value)} className="rounded-md border border-input px-2 py-1.5 text-sm"/><button onClick={() => remove(grade.id)} className="p-2 text-destructive"><Trash2 className="h-4 w-4"/></button></div>}</Draggable>)}{provided.placeholder}{!grades.length && <p className="py-4 text-center text-sm text-muted-foreground">{ar ? "لا توجد مستويات بعد." : "No job grades yet."}</p>}</div>}</Droppable></DragDropContext></section>;
}