import React, { useState } from "react";
import { Link } from "react-router-dom";
import { BarChart3, Check, MapPin, Pencil, ReceiptText, X } from "lucide-react";
import { updateCompany } from "@/lib/store";
import StationLocationEditor from "@/components/stations/StationLocationEditor";
import StationTypeEditor from "@/components/stations/StationTypeEditor";
import StationDeleteDialog from "@/components/stations/StationDeleteDialog";
import StationAnalyticsModal from "@/components/stations/StationAnalyticsModal";

export default function UnifiedStationManager({ station, team, data, company, currentUser, canManage, t, lang }) {
  const [name, setName] = useState(null); const [type, setType] = useState(false); const [location, setLocation] = useState(false); const [analytics, setAnalytics] = useState(false);
  const change = (values) => updateCompany(company.id, (draft) => { const target = draft.stations.find((item) => item.id === station.id); if (target) Object.assign(target, values); });
  const saveName = () => { if (name?.trim()) change({ name: name.trim() }); setName(null); };
  const cycleStatus = () => { const order = ["active", "maintenance", "stopped"]; change({ status: order[(order.indexOf(station.status) + 1) % order.length] }); };
  const canSetLocation = canManage || (currentUser.role === "station_manager" && (station.managerId === currentUser.id || currentUser.stationId === station.id));
  return <><section className="flex-1 rounded-xl border border-border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div>{name !== null ? <div className="flex items-center gap-1"><input autoFocus value={name} onChange={(e) => setName(e.target.value)} className="rounded-md border border-input px-2 py-1 font-heading text-xl font-semibold" /><button onClick={saveName} className="p-1 text-accent"><Check className="h-4 w-4" /></button><button onClick={() => setName(null)} className="p-1 text-muted-foreground"><X className="h-4 w-4" /></button></div> : <h1 className="flex items-center gap-2 font-heading text-3xl font-semibold">{station.name}{canManage && <button onClick={() => setName(station.name)} className="p-1 text-muted-foreground"><Pencil className="h-4 w-4" /></button>}</h1>}{type ? <StationTypeEditor t={t} onSave={(value) => { change({ type: value }); setType(false); }} onCancel={() => setType(false)} /> : <button disabled={!canManage} onClick={() => setType(true)} className="mt-1 flex items-center gap-1 text-sm text-muted-foreground">{station.location || t("location")} · {station.type || t("customType")}{canManage && <Pencil className="h-3 w-3" />}</button>}</div><div className="flex flex-wrap items-center gap-2"><button disabled={!canManage} onClick={cycleStatus} className="rounded-full bg-accent/10 px-3 py-1 text-xs text-accent">{station.status}</button>{canManage && <StationDeleteDialog station={station} stations={data.stations} data={data} company={company} lang={lang} />}</div></div><div className="mt-4 flex flex-wrap gap-4 border-t border-border pt-3 text-xs"><button onClick={() => setAnalytics(true)} className="flex items-center gap-1 text-accent"><BarChart3 className="h-3.5 w-3.5" />{t("analytics")}</button><Link to={`/app/stations/${station.id}/expenses`} className="flex items-center gap-1 text-accent"><ReceiptText className="h-3.5 w-3.5" />{lang === "ar" ? "المصروفات" : "Expenses"}</Link>{canSetLocation && <button onClick={() => setLocation(true)} className="flex items-center gap-1 text-muted-foreground"><MapPin className="h-3.5 w-3.5" />{station.lat != null ? t("editLocation") : t("setLocation")}</button>}</div></section>{location && <StationLocationEditor t={t} station={station} onSave={(coords) => { change(coords); setLocation(false); }} onCancel={() => setLocation(false)} />}{analytics && <StationAnalyticsModal stationKey={station.id} stationName={station.name} members={team} onClose={() => setAnalytics(false)} />}</>;
}