import React from "react";
import InvoiceStatusBadge from "@/components/owner/InvoiceStatusBadge";

const money = (value, currency, ar) => new Intl.NumberFormat(ar ? "ar-SA" : "en-US", { style: "currency", currency: currency || "SAR" }).format((value || 0) / 100);
export default function OfficialInvoiceTemplate({ invoice, ar }) {
  const date = new Date(invoice.createdAt).toLocaleDateString(ar ? "ar-SA" : "en-GB");
  const billing = invoice.billing === "yearly" ? (ar ? "سنوي / Yearly" : "Yearly / سنوي") : (ar ? "شهري / Monthly" : "Monthly / شهري");
  const row = (label, value, ltr = false, emphasis = false) => <div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-5 py-1 text-sm"><span className={emphasis ? "text-lg font-bold text-accent" : "font-medium text-primary-foreground/90"} dir={ltr ? "ltr" : "auto"}>{value || "—"}</span><span className={emphasis ? "text-lg font-bold" : "text-end"}>{label}</span></div>;
  return <article className="mx-auto min-h-[760px] max-w-2xl overflow-hidden rounded-2xl border border-primary-foreground/10 bg-primary px-7 py-8 text-primary-foreground shadow-elevated sm:px-10 sm:py-9" dir={ar ? "rtl" : "ltr"} style={{ backgroundImage: "url('https://media.base44.com/images/public/6a4f617bd7360a0ae9581d2a/41a16d83e_generated_image.png')", backgroundPosition: "center", backgroundSize: "cover" }}>
    <header className="text-center"><p className="text-xl tracking-tight"><strong>POWERCARE</strong> <span className="text-accent">•</span> OFFICIAL TAX INVOICE</p><h2 className="mt-4 text-xl font-normal">{ar ? "فاتورة ضريبية رسمية / Official tax invoice" : "Official tax invoice / فاتورة ضريبية رسمية"}</h2></header>
    <div className="mt-5 space-y-3">
      <section className="rounded-xl border border-primary-foreground/25 bg-primary-foreground/10 p-4 backdrop-blur-md">{row(ar ? "رقم الفاتورة / Invoice number" : "Invoice number / رقم الفاتورة", invoice.number, true)}{row(ar ? "تاريخ الإصدار / Issue date" : "Issue date / تاريخ الإصدار", date)}<div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-5 py-1 text-sm"><InvoiceStatusBadge status={invoice.status} ar={ar} /><span className="text-end">{ar ? "حالة الدفع / Payment status" : "Payment status / حالة الدفع"}</span></div></section>
      <section className="rounded-xl border border-primary-foreground/25 bg-primary-foreground/10 p-4 backdrop-blur-md"><h3 className="mb-2 text-end font-semibold">{ar ? "بيانات العميل / Bill to" : "Bill to / بيانات العميل"}</h3>{row(ar ? "اسم العميل / Customer name" : "Customer name / اسم العميل", invoice.companyName)}{row(ar ? "البريد الإلكتروني / Email" : "Email / البريد الإلكتروني", invoice.email, true)}{row(ar ? "معرّف العميل / Customer ID" : "Customer ID / معرّف العميل", invoice.companyId, true)}</section>
      <section className="rounded-xl border border-primary-foreground/25 bg-primary-foreground/10 p-4 backdrop-blur-md"><h3 className="mb-2 text-end font-semibold">{ar ? "تفاصيل الاشتراك / Subscription" : "Subscription / تفاصيل الاشتراك"}</h3>{row(ar ? "الخطة / Plan" : "Plan / الخطة", invoice.plan)}{row(ar ? "دورة الفوترة / Billing cycle" : "Billing cycle / دورة الفوترة", billing)}{row(ar ? "الرقم المرجعي / Reference" : "Reference / الرقم المرجعي", invoice.paymentReference || invoice.chargeId, true)}</section>
      <section className="rounded-xl border border-primary-foreground/25 bg-primary-foreground/10 p-4 backdrop-blur-md">{row(ar ? "المبلغ قبل الضريبة / Subtotal" : "Subtotal / المبلغ قبل الضريبة", money(invoice.subtotal, invoice.currency, ar))}{row(ar ? "ضريبة القيمة المضافة / VAT" : "VAT / ضريبة القيمة المضافة", money(invoice.tax, invoice.currency, ar))}{row(ar ? "الإجمالي / Total" : "Total / الإجمالي", money(invoice.total, invoice.currency, ar), false, true)}</section>
    </div>
    <footer className="mt-5 text-center text-xs leading-6 text-primary-foreground/80"><p>{ar ? "تم إنشاء هذه الفاتورة إلكترونيًا وهي سجل مالي رسمي صادر عن NiroVera." : "This invoice was generated electronically and is an official NiroVera financial record."}</p><p>{ar ? "This invoice was generated electronically and is an official NiroVera financial record." : "تم إنشاء هذه الفاتورة إلكترونيًا وهي سجل مالي رسمي صادر عن NiroVera."}</p><p className="mt-5 text-primary-foreground">NiroVera <span className="text-accent">•</span> Official subscription billing document</p></footer>
  </article>;
}