import React, { useEffect, useMemo, useState } from "react";
import { FileSpreadsheet, FileText, Loader2, Search } from "lucide-react";
import { base44 } from "@/api/base44Client";
import InvoiceStatusBadge from "@/components/owner/InvoiceStatusBadge";
import InvoiceDetailsDialog from "@/components/owner/InvoiceDetailsDialog";
import InvoiceMonthSelect from "@/components/owner/InvoiceMonthSelect";
import { exportInvoiceLedgerExcel, printInvoiceLedger } from "@/lib/subscriptionInvoiceLedgerExport";

const money = (value, currency, ar) => new Intl.NumberFormat(ar ? "ar-SA" : "en-US", { style: "currency", currency }).format((value || 0) / 100);
export default function SubscriptionInvoicesDashboard({ ar }) {
  const [invoices, setInvoices] = useState(null); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [month, setMonth] = useState("all"); const [selected, setSelected] = useState(null);
  useEffect(() => { base44.functions.invoke("tapPayments", { action: "listPayments" }).then((res) => setInvoices(res.data.invoices || [])).catch(() => setInvoices([])); }, []);
  const monthInvoices = useMemo(() => (invoices || []).filter((invoice) => month === "all" || String(invoice.createdAt || "").slice(0, 7) === month), [invoices, month]);
  const filtered = useMemo(() => monthInvoices.filter((invoice) => (status === "all" || invoice.status === status) && `${invoice.number} ${invoice.companyName} ${invoice.email}`.toLowerCase().includes(search.toLowerCase())), [monthInvoices, search, status]);
  const audit = (event, invoice = {}) => base44.functions.invoke("tapPayments", { action: "recordInvoiceAudit", event, invoiceId: invoice.id || "bulk", invoiceNumber: invoice.number || "bulk", companyId: invoice.companyId || "platform" }).catch(() => {});
  const exportExcel = () => { audit("exported_excel"); exportInvoiceLedgerExcel(filtered, ar); }; const exportPdf = () => { audit("exported_pdf"); printInvoiceLedger(filtered, ar); };
  if (!invoices) return <div className="flex justify-center py-16"><Loader2 className="h-6 w-6 animate-spin text-accent" /></div>;
  const paid = monthInvoices.filter((item) => item.status === "paid"); const due = monthInvoices.filter((item) => item.status === "open"); const totalPaid = paid.reduce((sum, item) => sum + item.amountPaid, 0);
  return <div className="space-y-5"><div className="rounded-xl border border-border bg-card px-5 py-4 shadow-soft"><p className="text-xs font-semibold uppercase tracking-widest text-accent">{ar ? "السجل المالي القانوني" : "Financial compliance ledger"}</p><h1 className="mt-1 font-heading text-2xl font-semibold">{ar ? "فواتير الاشتراكات" : "Subscription invoices"}</h1></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[[ar ? "إجمالي الفواتير" : "All invoices", monthInvoices.length], [ar ? "مدفوعة" : "Paid", paid.length], [ar ? "مستحقة" : "Outstanding", due.length], [ar ? "إجمالي المحصل" : "Total collected", money(totalPaid, paid[0]?.currency || "USD", ar)]].map(([label, value]) => <div key={label} className="rounded-xl border border-border bg-card p-4 shadow-soft"><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div>)}</div>
    <div className="flex flex-col gap-2 md:flex-row"><label className="relative flex-1"><Search className="absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder={ar ? "بحث برقم الفاتورة أو الشركة…" : "Search invoice or company…"} className="w-full rounded-md border border-input py-2.5 pe-3 ps-9 text-sm" /></label><InvoiceMonthSelect invoices={invoices} value={month} onChange={setMonth} ar={ar} /><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-md border border-input px-3 text-sm"><option value="all">{ar ? "كل الحالات" : "All statuses"}</option><option value="paid">{ar ? "مدفوعة" : "Paid"}</option><option value="open">{ar ? "مستحقة" : "Open"}</option><option value="draft">{ar ? "مسودة" : "Draft"}</option><option value="void">{ar ? "ملغاة" : "Void"}</option><option value="uncollectible">{ar ? "متعذرة" : "Uncollectible"}</option></select><button onClick={exportExcel} disabled={!filtered.length} className="flex items-center justify-center gap-2 rounded-md border border-emerald-300 px-4 py-2 text-xs font-semibold text-emerald-700"><FileSpreadsheet className="h-4 w-4" />Excel</button><button onClick={exportPdf} disabled={!filtered.length} className="flex items-center justify-center gap-2 rounded-md bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground"><FileText className="h-4 w-4" />PDF</button></div>
    <div className="overflow-hidden rounded-xl border border-border bg-card shadow-soft"><table className="mobile-cards w-full text-sm"><thead><tr><th className="px-4 py-3 text-start">{ar ? "رقم الفاتورة" : "Invoice"}</th><th className="px-4 py-3 text-start">{ar ? "العميل" : "Customer"}</th><th className="px-4 py-3 text-start">{ar ? "الحالة" : "Status"}</th><th className="px-4 py-3 text-start">{ar ? "التاريخ" : "Date"}</th><th className="px-4 py-3 text-start">{ar ? "الضريبة" : "Tax"}</th><th className="px-4 py-3 text-start">{ar ? "الإجمالي" : "Total"}</th><th className="px-4 py-3 text-start">{ar ? "المتبقي" : "Balance"}</th><th /></tr></thead><tbody>{filtered.map((invoice) => <tr key={invoice.id} className="border-t border-border"><td className="px-4 py-3 font-mono text-xs" data-label={ar ? "رقم الفاتورة" : "Invoice"}>{invoice.number}</td><td className="px-4 py-3" data-label={ar ? "العميل" : "Customer"}><p className="font-medium">{invoice.companyName || "—"}</p><p className="text-xs text-muted-foreground" dir="ltr">{invoice.email}</p></td><td className="px-4 py-3" data-label={ar ? "الحالة" : "Status"}><InvoiceStatusBadge status={invoice.status} ar={ar} /></td><td className="px-4 py-3 text-muted-foreground" data-label={ar ? "التاريخ" : "Date"}>{new Date(invoice.createdAt).toLocaleDateString(ar ? "ar-SA" : "en-GB")}</td><td className="px-4 py-3" data-label={ar ? "الضريبة" : "Tax"}>{money(invoice.tax, invoice.currency, ar)}</td><td className="px-4 py-3 font-semibold" data-label={ar ? "الإجمالي" : "Total"}>{money(invoice.total, invoice.currency, ar)}</td><td className="px-4 py-3" data-label={ar ? "المتبقي" : "Balance"}>{money(invoice.amountDue, invoice.currency, ar)}</td><td className="px-4 py-3"><button onClick={() => { setSelected(invoice); audit("viewed", invoice); }} className="rounded-md border border-border px-3 py-1.5 text-xs">{ar ? "التفاصيل" : "Details"}</button></td></tr>)}{!filtered.length && <tr><td colSpan={8} className="p-10 text-center text-muted-foreground">{ar ? "لا توجد فواتير مطابقة." : "No matching invoices."}</td></tr>}</tbody></table></div>
    <InvoiceDetailsDialog invoice={selected} onClose={() => setSelected(null)} ar={ar} onAudit={audit} />
  </div>;
}