import React, { useEffect, useState } from "react";
import { Ban } from "lucide-react";
import FlowSwipeAction from "@/components/flow/FlowSwipeAction";
import { PERMIT_REQUIREMENTS, PERMIT_TYPES } from "@/lib/safetyStandards";

const blank = { type: "excavation", description: "", team: "", validFrom: "", validUntil: "", requirements: [] };
export default function PermitWorkTab({ permits = [], canEdit, lang, signerName, onChange }) {
  const ar = lang === "ar"; const L = (a, e) => ar ? a : e; const [form, setForm] = useState(blank);
  const valid = form.description.trim() && form.team.trim() && form.validFrom && form.validUntil && form.validUntil >= form.validFrom && form.requirements.length;
  const create = () => { if (!valid) return; onChange([{ ...form, id: `permit_${Date.now()}`, status: "open", signedBy: signerName, signedAt: new Date().toISOString() }, ...permits]); setForm(blank); };
  const status = (p) => p.status === "cancelled" ? "cancelled" : new Date(p.validUntil).getTime() < Date.now() ? "expired" : "open";
  useEffect(() => {
    const next = permits.map((permit) => status(permit) === "expired" && permit.status !== "expired" ? { ...permit, status: "expired" } : permit);
    if (next.some((permit, index) => permit !== permits[index])) onChange(next);
  }, [permits]);
  return <div className="space-y-4">{canEdit && <div className="space-y-2 rounded-lg border border-border p-3"><select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })} className="w-full rounded-md border border-input px-2 py-1.5 text-xs">{PERMIT_TYPES.map(([id,a,e]) => <option key={id} value={id}>{ar?a:e}</option>)}</select><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder={L("وصف العمل", "Work description")} className="w-full rounded-md border border-input px-2 py-1.5 text-xs" /><input value={form.team} onChange={(e) => setForm({ ...form, team: e.target.value })} placeholder={L("الفريق", "Work team")} className="w-full rounded-md border border-input px-2 py-1.5 text-xs" /><div className="grid grid-cols-2 gap-2"><input type="datetime-local" value={form.validFrom} onChange={(e) => setForm({ ...form, validFrom: e.target.value })} className="rounded-md border border-input px-1 py-1.5 text-[10px]" /><input type="datetime-local" value={form.validUntil} onChange={(e) => setForm({ ...form, validUntil: e.target.value })} className="rounded-md border border-input px-1 py-1.5 text-[10px]" /></div><div className="grid grid-cols-2 gap-1.5">{PERMIT_REQUIREMENTS.map(([id,a,e]) => <label key={id} className="flex items-center gap-1 text-[10px]"><input type="checkbox" checked={form.requirements.includes(id)} onChange={(event) => setForm({ ...form, requirements: event.target.checked ? [...form.requirements,id] : form.requirements.filter((x)=>x!==id) })} />{ar?a:e}</label>)}</div>{valid ? <FlowSwipeAction sensitive label={L("اسحب للموافقة الرقمية", "Swipe for digital approval")} onAction={create} confirmLabel={L("اعتماد التصريح", "Approve permit")} cancelLabel={L("إلغاء", "Cancel")} /> : <p className="text-[10px] text-amber-600">{L("أكمل الحقول واختر اشتراطًا واحدًا على الأقل.", "Complete all fields and select at least one requirement.")}</p>}</div>}
    <div className="space-y-2">{permits.map((permit) => { const current = status(permit); return <div key={permit.id} className="rounded-lg border border-border p-3 text-xs space-y-1"><div className="flex justify-between gap-2"><strong>{PERMIT_TYPES.find(([id])=>id===permit.type)?.[ar?1:2]}</strong><span className={`rounded-full px-2 py-0.5 ${current === "open" ? "bg-emerald-100 text-emerald-700" : "bg-muted text-muted-foreground"}`}>{L(current === "open" ? "مفتوح" : current === "expired" ? "منتهي" : "ملغى", current)}</span></div><p>{permit.description}</p><p className="text-muted-foreground">{permit.team} · {new Date(permit.validUntil).toLocaleString(ar?"ar-SA":"en-GB")}</p><p className="text-[10px] text-accent">{L("اعتماد", "Signed")}: {permit.signedBy} · {new Date(permit.signedAt).toLocaleString(ar?"ar-SA":"en-GB")}</p>{canEdit && current === "open" && <button onClick={() => onChange(permits.map((p)=>p.id===permit.id?{...p,status:"cancelled"}:p))} className="flex items-center gap-1 text-[10px] text-destructive"><Ban className="h-3 w-3" />{L("إلغاء التصريح", "Cancel permit")}</button>}</div>; })}{permits.length === 0 && <p className="py-4 text-center text-xs text-muted-foreground">{L("لا توجد تصاريح عمل.", "No permits to work.")}</p>}</div>
  </div>;
}