import React, { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { riskTone } from "@/lib/safetyStandards";

const empty = { hazard: "", probability: 1, severity: 1, correctiveAction: "", owner: "", dueDate: "" };
export default function RiskAssessmentTab({ items = [], canEdit, lang, onChange }) {
  const ar = lang === "ar"; const L = (a, e) => ar ? a : e; const [form, setForm] = useState(empty);
  const ready = form.hazard.trim() && form.correctiveAction.trim() && form.owner.trim() && form.dueDate;
  const add = () => { if (!ready) return; onChange([...items, { ...form, id: `risk_${Date.now()}` }]); setForm(empty); };
  const patch = (id, field, value) => onChange(items.map((item) => item.id === id ? { ...item, [field]: value } : item));
  return <div className="space-y-3">
    {canEdit && <div className="grid grid-cols-2 gap-2 rounded-lg border border-border p-3"><input value={form.hazard} onChange={(e) => setForm({ ...form, hazard: e.target.value })} placeholder={L("وصف الخطر", "Hazard description")} className="col-span-2 rounded-md border border-input px-2 py-1.5 text-xs" /><select value={form.probability} onChange={(e) => setForm({ ...form, probability: Number(e.target.value) })} className="rounded-md border border-input px-2 py-1.5 text-xs">{[1,2,3,4,5].map((n) => <option key={n} value={n}>{L("الاحتمالية", "Probability")} {n}</option>)}</select><select value={form.severity} onChange={(e) => setForm({ ...form, severity: Number(e.target.value) })} className="rounded-md border border-input px-2 py-1.5 text-xs">{[1,2,3,4,5].map((n) => <option key={n} value={n}>{L("الخطورة", "Severity")} {n}</option>)}</select><input value={form.correctiveAction} onChange={(e) => setForm({ ...form, correctiveAction: e.target.value })} placeholder={L("الإجراء التصحيحي", "Corrective action")} className="rounded-md border border-input px-2 py-1.5 text-xs" /><input value={form.owner} onChange={(e) => setForm({ ...form, owner: e.target.value })} placeholder={L("المسؤول", "Owner")} className="rounded-md border border-input px-2 py-1.5 text-xs" /><input type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} className="rounded-md border border-input px-2 py-1.5 text-xs" /><button onClick={add} disabled={!ready} className="flex items-center justify-center gap-1 rounded-md bg-foreground px-2 py-1.5 text-xs text-background disabled:opacity-40"><Plus className="h-3.5 w-3.5" />{L("إضافة", "Add")}</button></div>}
    <div className="space-y-2">{items.map((item) => { const score = Number(item.probability) * Number(item.severity); return <div key={item.id} className="rounded-lg border border-border p-3 space-y-2"><div className="flex justify-between gap-2">{canEdit ? <input value={item.hazard} onChange={(e) => patch(item.id, "hazard", e.target.value)} className="min-w-0 flex-1 rounded border border-input px-1.5 py-1 text-xs font-semibold" /> : <strong className="text-xs">{item.hazard}</strong>}<span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${riskTone(score)}`}>{score}/25</span></div><div className="grid grid-cols-2 gap-2 text-[11px]"><label>P <select disabled={!canEdit} value={item.probability} onChange={(e) => patch(item.id, "probability", Number(e.target.value))} className="ms-1 rounded border border-input">{[1,2,3,4,5].map((n)=><option key={n}>{n}</option>)}</select></label><label>S <select disabled={!canEdit} value={item.severity} onChange={(e) => patch(item.id, "severity", Number(e.target.value))} className="ms-1 rounded border border-input">{[1,2,3,4,5].map((n)=><option key={n}>{n}</option>)}</select></label><input disabled={!canEdit} value={item.correctiveAction || ""} onChange={(e) => patch(item.id, "correctiveAction", e.target.value)} placeholder={L("الإجراء", "Action")} className="rounded border border-input px-1.5 py-1" /><input disabled={!canEdit} value={item.owner || ""} onChange={(e) => patch(item.id, "owner", e.target.value)} placeholder={L("المسؤول", "Owner")} className="rounded border border-input px-1.5 py-1" /><input disabled={!canEdit} type="date" value={item.dueDate || ""} onChange={(e) => patch(item.id, "dueDate", e.target.value)} className="rounded border border-input px-1.5 py-1" />{canEdit && <button onClick={() => onChange(items.filter((x) => x.id !== item.id))} className="justify-self-end text-destructive"><Trash2 className="h-4 w-4" /></button>}</div></div>; })}{items.length === 0 && <p className="py-4 text-center text-xs text-muted-foreground">{L("لا توجد مخاطر مسجلة.", "No risk items recorded.")}</p>}</div>
  </div>;
}