import React from "react";
import { ArrowLeft, CheckCircle2, CircleDollarSign, Rocket } from "lucide-react";
import { Link } from "react-router-dom";
import SapComparisonPdfPage from "@/components/comparison/SapComparisonPdfPage";
import SapPainPointCard from "@/components/comparison/SapPainPointCard";
import SapExecutiveTable from "@/components/comparison/SapExecutiveTable";
import SapComparisonStats from "@/components/comparison/SapComparisonStats";
import { comparisonRows, comparisonStats, sapPainPoints, sourceNote } from "@/lib/powerCareSapPainPoints";

export default function SapComparisonDocument() {
  return <>
    <SapComparisonPdfPage number="01" eyebrow="من المشكلة إلى الحل" title="تعبت من SAP؟ هذا ما تبحث عنه"><div className="rounded-xl bg-primary p-10 text-primary-foreground"><p className="text-sm leading-8 text-primary-foreground/75">منصة تشغيل عربية تمنحك ما تحتاجه فرقك كل يوم، دون سنوات من التنفيذ أو طبقات من التعقيد.</p><div className="my-10 h-px bg-accent/35" /><div className="grid grid-cols-2 gap-5"><div className="rounded-lg border border-red-300/25 bg-red-950/20 p-5"><CircleDollarSign className="mb-4 h-7 w-7 text-red-300" /><p className="text-xs text-primary-foreground/60">المشكلة</p><h3 className="mt-2 font-heading text-2xl !text-primary-foreground">تكلفة، تعقيد، وانتظار</h3></div><div className="rounded-lg border border-accent/40 bg-accent/10 p-5"><Rocket className="mb-4 h-7 w-7 text-accent" /><p className="text-xs text-accent">البديل</p><h3 className="mt-2 font-heading text-2xl !text-primary-foreground">تشغيل واضح يبدأ بسرعة</h3></div></div><div className="mt-10 flex gap-3"><Link to="/pricing" className="flex items-center gap-2 rounded-md bg-accent px-5 py-3 text-sm font-bold text-accent-foreground">ابدأ الآن مجاناً <ArrowLeft className="h-4 w-4" /></Link><Link to="/powercare-presentation" className="rounded-md border border-primary-foreground/25 px-5 py-3 text-sm">شاهد العرض التوضيحي</Link></div></div></SapComparisonPdfPage>
    <SapComparisonPdfPage number="02" eyebrow="SAP PAIN POINTS" title="كل نقطة ألم يقابلها حل عملي"><div className="space-y-3">{sapPainPoints.map((item) => <SapPainPointCard key={item.number} item={item} />)}</div></SapComparisonPdfPage>
    <SapComparisonPdfPage number="03" eyebrow="EXECUTIVE BOARD" title="مقارنة تفصيلية جنباً إلى جنب"><SapExecutiveTable rows={comparisonRows} /><p className="mt-5 rounded-md border border-accent/30 bg-accent/10 p-4 text-xs leading-6">PowerCare ليس ادعاءً باستبدال كل عمق SAP المالي العالمي؛ بل بديل تشغيلي مركز للشركات التي تريد سرعة ووضوحاً وملاءمة محلية.</p></SapComparisonPdfPage>
    <SapComparisonPdfPage number="04" eyebrow="THE NUMBERS SPEAK" title="الأرقام تتحدث"><SapComparisonStats stats={comparisonStats} /><div className="mt-7 rounded-xl bg-primary p-7 text-primary-foreground"><CheckCircle2 className="mb-4 h-8 w-8 text-accent" /><h3 className="font-heading text-3xl !text-primary-foreground">ابدأ بما تحتاجه اليوم، وتوسّع غداً</h3><p className="mt-3 text-sm leading-7 text-primary-foreground/70">جرّب PowerCare مجاناً، شاهد العرض، ثم اختر الخطة المناسبة لحجم عملياتك.</p><div className="mt-6 flex gap-3"><Link to="/pricing" className="rounded-md bg-accent px-5 py-3 text-sm font-bold text-accent-foreground">ابدأ الآن مجاناً</Link><Link to="/about" className="rounded-md border border-primary-foreground/25 px-5 py-3 text-sm">تواصل معنا</Link></div></div><p className="mt-6 text-[10px] leading-5 text-muted-foreground">{sourceNote}</p></SapComparisonPdfPage>
  </>;
}