import React from "react";
import { Link } from "react-router-dom";
import { Bot, CheckCircle2, ChevronRight, Sparkles } from "lucide-react";

export default function NiroPredictiveCenter({ data, metrics, alerts, lang }) {
  const ar = lang === "ar";
  const count = (category) => alerts.find((item) => item.category === category)?.count || 0;
  const expenses = (data.expenses || data.expenseClaims || []).filter((item) => ["submitted", "manager_approved"].includes(item.status)).length;
  const payroll = (data.payroll || []).filter((item) => ["pending", "draft"].includes(item.status)).length;
  const signing = (data.signatureRequests || []).filter((item) => item.status === "pending").length;
  const items = [
    ["attendance", metrics.absentCount, ar ? "ضغط متوقع على تغطية الورديات" : "Shift coverage pressure expected", ar ? `${metrics.absentCount} موظفين مجدولين لم يسجلوا حضورهم` : `${metrics.absentCount} scheduled employees have not checked in`, ar ? "راجع بدائل التغطية قبل تأثر التشغيل" : "Review coverage alternatives before operations are affected", "/app/attendance"],
    ["tasks", metrics.delayedTasks, ar ? "احتمال تصاعد تأخر المهام" : "Task delays may escalate", ar ? `${metrics.delayedTasks} مهام قريبة من الموعد أو متأخرة` : `${metrics.delayedTasks} tasks are due soon or overdue`, ar ? "راجع الأولويات والعوائق مع المسؤولين" : "Review priorities and blockers with assignees", "/app/tasks"],
    ["safety", metrics.safetySignals, ar ? "ارتفاع محتمل في المخاطر التشغيلية" : "Operational risk may increase", ar ? `${metrics.safetySignals} إشارات سلامة مفتوحة` : `${metrics.safetySignals} open safety signals`, ar ? "ابدأ بالمحطات الأعلى خطورة وراجع إجراءات المنع" : "Start with the highest-risk stations and review controls", "/app/safety"],
    ["reports", metrics.pendingReports, ar ? "تراكم متوقع في المراجعات" : "Review backlog may grow", ar ? `${metrics.pendingReports} تقارير تنتظر المراجعة` : `${metrics.pendingReports} reports await review`, ar ? "رتب المراجعات حسب الأثر والموعد" : "Prioritize reviews by impact and deadline", "/app/daily-report"],
    ["complaints", metrics.anonOpenCount, ar ? "احتمال استمرار مشكلات غير معالجة" : "Unresolved issues may persist", ar ? `${metrics.anonOpenCount} بلاغات مجهولة مفتوحة` : `${metrics.anonOpenCount} anonymous reports remain open`, ar ? "راجع الأنماط المتكررة مع حماية هوية المبلّغ" : "Review recurring patterns while protecting reporter identity", "/app/complaints"],
    ["inventory", count("stock") + count("requests"), ar ? "احتمال تعطل بسبب الإمداد" : "Supply disruption risk", ar ? `${count("stock")} نقص مخزون و${count("requests")} طلبات متأخرة` : `${count("stock")} low-stock signals and ${count("requests")} delayed requests`, ar ? "راجع المواد الحرجة والطلبات المعتمدة أولاً" : "Review critical materials and approved requests first", "/app/inventory"],
    ["expenses", expenses, ar ? "تأخر محتمل في دورة المصروفات" : "Expense cycle delay possible", ar ? `${expenses} مطالبات مالية قيد المراجعة` : `${expenses} expense claims are under review`, ar ? "راجع المطالبات الأقدم والأعلى قيمة" : "Review the oldest and highest-value claims", "/app/expenses"],
    ["payroll", payroll, ar ? "جاهزية الرواتب تحتاج مراجعة" : "Payroll readiness needs review", ar ? `${payroll} سجلات رواتب غير مكتملة` : `${payroll} payroll records are incomplete`, ar ? "تحقق من السجلات قبل موعد الإغلاق" : "Verify records before the closing date", "/app/payroll"],
    ["signing", signing, ar ? "احتمال تأخر المستندات" : "Document delays possible", ar ? `${signing} طلبات توقيع معلقة` : `${signing} signature requests are pending`, ar ? "راجع الطلبات الأقدم وتسلسل الموقّعين" : "Review oldest requests and signer order", "/app/signing"],
  ].filter(([, value]) => value > 0);
  return <section className="rounded-2xl border border-accent/30 bg-card p-5 shadow-sm sm:p-6"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-widest text-accent"><Sparkles className="h-3.5 w-3.5" />Niro Intelligence</p><h2 className="mt-1 font-heading text-2xl font-semibold">{ar ? "مركز نيرو التنبؤي" : "Niro Predictive Center"}</h2><p className="mt-1 text-xs text-muted-foreground">{ar ? "توقعات مفسّرة واقتراحات فقط — لا يتم تنفيذ أي إجراء تلقائياً" : "Explained forecasts and suggestions only — no action is executed automatically"}</p></div><span className="flex h-10 w-10 items-center justify-center rounded-full bg-accent/10 text-accent"><Bot className="h-5 w-5" /></span></div>{items.length === 0 ? <p className="flex items-center gap-2 rounded-xl bg-muted/60 p-4 text-sm text-muted-foreground"><CheckCircle2 className="h-4 w-4 text-emerald-600" />{ar ? "لا توجد مؤشرات حرجة حالياً عبر أقسام النظام." : "No critical signals across system areas right now."}</p> : <div className="grid gap-3 lg:grid-cols-2">{items.map(([key,, title, why, suggestion, to]) => <Link key={key} to={to} className="group rounded-xl border border-border bg-muted/30 p-4 hover:border-accent/40"><div className="flex items-start gap-3"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-accent" /><div className="min-w-0 flex-1"><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-xs text-muted-foreground"><strong>{ar ? "السبب: " : "Why: "}</strong>{why}</p><p className="mt-2 text-sm"><strong className="text-accent">{ar ? "اقتراح نيرو: " : "Niro suggests: "}</strong>{suggestion}</p></div><ChevronRight className={`h-4 w-4 shrink-0 text-muted-foreground group-hover:text-accent ${ar ? "rotate-180" : ""}`} /></div></Link>)}</div>}</section>;
}